"""Finalize the r2 ledgers (append-only, BYTE level).

1. evidence/rgm2/MANIFEST_r2.sha256 - every file under evidence/rgm2/ except
   the manifest itself (r1's evidence/MANIFEST.sha256 stays byte-identical and
   is never rewritten).
2. DELIVERABLES.sha256 - keeps r1's first 725 bytes VERBATIM (CRLF endings and
   all) and (re)writes this round's block below them.

Everything is done on bytes: a previous text-mode pass had silently turned
r1's CRLF line endings into LF and broken the prefix, which the prefix
self-check caught.  Running this script repairs and then keeps the prefix.
"""
from __future__ import annotations

import hashlib
from pathlib import Path

ATTEMPT = Path(__file__).resolve().parents[1]
RG2 = ATTEMPT / "evidence" / "rgm2"
MANIFEST_R2 = RG2 / "MANIFEST_r2.sha256"
DELIVERABLES = ATTEMPT / "DELIVERABLES.sha256"

MARKER = b"# ---- review_round_2 (r2) append-only additions ----"
R1_PREFIX_BYTES = 725
R1_PREFIX_SHA = "c7d8c583eeea3a754ae8272d54e36757896a93c71a977447370c53c5b4cb5ce8"


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    files = sorted(
        p for p in RG2.rglob("*")
        if p.is_file() and p != MANIFEST_R2
    )
    lines = [
        f"{sha(p)}  evidence/rgm2/{p.relative_to(RG2).as_posix()}"
        for p in files
    ]
    MANIFEST_R2.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"MANIFEST_r2 entries={len(lines)}")

    current = DELIVERABLES.read_bytes()
    r1_prefix = current[:R1_PREFIX_BYTES]
    if hashlib.sha256(r1_prefix).hexdigest() != R1_PREFIX_SHA:
        raise SystemExit(
            "r1 prefix of DELIVERABLES.sha256 does not hash to the r1 value; "
            "refusing to write"
        )

    block = [
        MARKER.decode("ascii"),
        "# r1's 9 lines above are the frozen r1 delivery shas; for the four paths",
        "# that grew in r2, prefix preservation of the r1 bytes is proved by",
        "# evidence/rgm2/prefix_selfcheck_r2.json (sha256 of the first r1_bytes of",
        "# each file == its r1 line). changes.diff was regenerated by card step 7;",
        "# its r1 preimage is archived at evidence/rgm2/changes_r1_preimage.diff.",
        f"{sha(ATTEMPT / 'commands.md')}  commands.md",
        f"{sha(ATTEMPT / 'decision.md')}  decision.md",
        f"{sha(ATTEMPT / 'handoff.md')}  handoff.md",
        f"{sha(ATTEMPT / 'changes.diff')}  changes.diff",
        f"{sha(ATTEMPT / 'handoff.json')}  handoff.json",
        f"{sha(MANIFEST_R2)}  evidence/rgm2/MANIFEST_r2.sha256",
        "",
    ]
    new_bytes = r1_prefix + b"\n" + "\n".join(block).encode("utf-8")
    if new_bytes != current:
        DELIVERABLES.write_bytes(new_bytes)
        print("rewrote the r2 block (r1 725-byte prefix kept byte-for-byte)")
    else:
        print("DELIVERABLES.sha256 already final (byte-identical)")
    check = hashlib.sha256(DELIVERABLES.read_bytes()[:R1_PREFIX_BYTES]).hexdigest()
    print(f"r1 prefix after write: {check == R1_PREFIX_SHA}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
