"""Round-2 prefix / read-only self-check for WC-4 = F12-RC120.

Discipline proved here (r2 must only append to r1 bytes):

  A. append-only paths   -> sha256(current[0:r1_bytes]) == r1 sha256
                            (prefix_bytes_preserved = true)
  B. frozen/read-only    -> sha256(current) == r1 sha256 (byte identical)
      * reviewer_report.md / reviewer_report.sha256  (the ruling source)
      * oracle.md / oracle.sha256                    (frozen, must never change)
      * every entry of evidence/MANIFEST.sha256's r1 portion (57 lines)
  C. r1 DELIVERABLES.sha256 first 9 lines -> re-derived from the current files
  D. changes.diff       -> regenerated by card step 7 (sanctioned); its r1
      preimage must still hash to the r1 DELIVERABLES line

The output is deterministic (no timestamps) so re-running it reproduces the
same bytes, which keeps evidence/rgm2/MANIFEST_r2.sha256 valid.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

ATTEMPT = Path(__file__).resolve().parents[1]
OUT = ATTEMPT / "evidence" / "rgm2" / "prefix_selfcheck_r2.json"

# r1 byte lengths measured at the start of the r2 round, before any append
R1_BYTES = {
    "oracle.md": 5166,
    "oracle.sha256": 76,
    "binding.json": 11320,
    "commands.md": 13251,
    "decision.md": 11542,
    "changes.diff": 8306,
    "handoff.md": 7077,
    "recovery.md": 5815,
    "evidence/MANIFEST.sha256": 5838,
    "DELIVERABLES.sha256": 725,
    "reviewer_report.md": 26073,
    "reviewer_report.sha256": 85,
}
R1_DELIVERABLES_LINES = 9
R1_MANIFEST_LINES = 57

# paths whose r1 sha is NOT listed inside DELIVERABLES.sha256 (the ledger does
# not list itself, and the reviewer report was written after r1 signed off)
R1_SHA_FALLBACK = {
    "DELIVERABLES.sha256": "c7d8c583eeea3a754ae8272d54e36757896a93c71a977447370c53c5b4cb5ce8",
    "reviewer_report.md": "9941660588641a31a22449365982392a28f4fc5b2451a69ca8587f38ad3074e8",
    "reviewer_report.sha256": "381efe271046e67f75a7cac31b0b019a99b8117f2d27ff75ddc57351e2efc490",
}

APPEND_ONLY = [
    "commands.md",
    "decision.md",
    "handoff.md",
    "binding.json",
    "DELIVERABLES.sha256",
    "evidence/MANIFEST.sha256",
    "recovery.md",
    "oracle.md",
    "oracle.sha256",
]
BYTE_IDENTICAL_REQUIRED = [
    "reviewer_report.md",
    "reviewer_report.sha256",
    "oracle.md",
    "oracle.sha256",
    "binding.json",
    "evidence/MANIFEST.sha256",
    "recovery.md",
]


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def split_ledger(path: Path, keep: int) -> list[str]:
    lines = path.read_text(encoding="utf-8").splitlines()
    return [line for line in lines[:keep] if line.strip() and not line.startswith("#")]


def parse_pair(line: str) -> tuple[str, str]:
    digest, _, name = line.partition("  ")
    return digest.strip(), name.strip()


def main() -> int:
    deliverables = ATTEMPT / "DELIVERABLES.sha256"
    manifest = ATTEMPT / "evidence" / "MANIFEST.sha256"

    r1_deliverables = [parse_pair(x) for x in
                       split_ledger(deliverables, R1_DELIVERABLES_LINES)]
    r1_manifest = [parse_pair(x) for x in
                   split_ledger(manifest, R1_MANIFEST_LINES)]

    def r1_sha_of(rel: str):
        return next((d for d, n in r1_deliverables if n == rel), None) or \
            R1_SHA_FALLBACK.get(rel)

    report: dict = {
        "card": "WC-4 = F12-RC120",
        "round": "r2",
        "purpose": "prefix preservation of append-only r1 bytes + byte-identity of frozen files",
        "append_only": [],
        "byte_identical": [],
        "deliverables_r1_lines": [],
        "manifest_r1_lines": {"total": len(r1_manifest), "match": 0, "mismatch": []},
        "changes_diff": {},
        "reviewer_report": {},
    }
    ok = True

    for rel in APPEND_ONLY:
        path = ATTEMPT / rel
        current = path.read_bytes()
        r1_len = R1_BYTES[rel]
        r1_line = r1_sha_of(rel)
        prefix = sha(current[:r1_len])
        entry = {
            "path": rel,
            "r1_bytes": r1_len,
            "now_bytes": len(current),
            "r1_sha256": r1_line,
            "prefix_sha256_of_first_r1_bytes": prefix,
            "prefix_bytes_preserved": prefix == r1_line,
            "grew_by_append": len(current) >= r1_len and prefix == r1_line,
        }
        report["append_only"].append(entry)
        ok = ok and entry["prefix_bytes_preserved"]

    for rel in BYTE_IDENTICAL_REQUIRED:
        path = ATTEMPT / rel
        current = path.read_bytes()
        r1_line = r1_sha_of(rel)
        same = sha(current) == r1_line
        report["byte_identical"].append({
            "path": rel, "r1_sha256": r1_line, "now_sha256": sha(current),
            "bytes": len(current), "byte_identical": same,
        })
        ok = ok and same

    for digest, name in r1_deliverables:
        path = ATTEMPT / name
        if name == "changes.diff":
            # regenerated on purpose (card step 7); r1 preimage is archived
            preimage = ATTEMPT / "evidence" / "rgm2" / "changes_r1_preimage.diff"
            entry = {
                "path": name, "r1_sha256": digest,
                "now_sha256": sha(path.read_bytes()),
                "regenerated_by_card_step7": True,
                "r1_preimage_archived_sha256": sha(preimage.read_bytes()),
                "r1_preimage_matches_r1_line": sha(preimage.read_bytes()) == digest,
            }
            ok = ok and entry["r1_preimage_matches_r1_line"]
        elif name in APPEND_ONLY:
            r1_len = R1_BYTES[name]
            current = path.read_bytes()
            entry = {
                "path": name, "r1_sha256": digest,
                "prefix_bytes_preserved": sha(current[:r1_len]) == digest,
                "now_bytes": len(current),
            }
            ok = ok and entry["prefix_bytes_preserved"]
        else:
            digest_now = sha(path.read_bytes())
            entry = {"path": name, "r1_sha256": digest, "now_sha256": digest_now,
                     "byte_identical": digest_now == digest}
            ok = ok and entry["byte_identical"]
        report["deliverables_r1_lines"].append(entry)

    for digest, name in r1_manifest:
        path = ATTEMPT / name
        digest_now = sha(path.read_bytes()) if path.exists() else None
        if digest_now == digest:
            report["manifest_r1_lines"]["match"] += 1
        else:
            report["manifest_r1_lines"]["mismatch"].append(
                {"path": name, "r1": digest, "now": digest_now})
            ok = False

    rr = ATTEMPT / "reviewer_report.md"
    rr_sha = ATTEMPT / "reviewer_report.sha256"
    report["reviewer_report"] = {
        "bytes": len(rr.read_bytes()),
        "sha256": sha(rr.read_bytes()),
        "expected_sha256": "9941660588641a31a22449365982392a28f4fc5b2451a69ca8587f38ad3074e8",
        "sidecar_sha256": sha(rr_sha.read_bytes()),
        "read_only_verified": sha(rr.read_bytes())
        == "9941660588641a31a22449365982392a28f4fc5b2451a69ca8587f38ad3074e8",
    }
    ok = ok and report["reviewer_report"]["read_only_verified"]

    report["all_checks_passed"] = ok
    OUT.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"append_only={len(report['append_only'])} all_prefix_ok="
          f"{all(e['prefix_bytes_preserved'] for e in report['append_only'])}")
    print(f"byte_identical_ok={all(e['byte_identical'] for e in report['byte_identical'])}")
    print(f"deliverables_r1_ok={all(bool(e.get('byte_identical', e.get('prefix_bytes_preserved', e.get('r1_preimage_matches_r1_line')))) for e in report['deliverables_r1_lines'])}")
    print(f"manifest_r1 {report['manifest_r1_lines']['match']}/{report['manifest_r1_lines']['total']}")
    print(f"reviewer_report_read_only={report['reviewer_report']['read_only_verified']}")
    print("PREFIX_SELFCHECK_OK" if ok else "PREFIX_SELFCHECK_FAIL")
    print(f"wrote {OUT}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
