"""I-08-A c6 helper: regenerate the attempt's canonical hash inventory and
refresh handoff.json.product_file_hashes for the files that CAN be hashed
without self-reference.

Excluded on purpose:
  * after/product_hashes.txt  - it is the inventory itself
  * handoff.json              - it embeds the other hashes; hashing it inside
                                itself is impossible (its content would change)

Run:  <attempt>/iso/venv/Scripts/python.exe -X utf8 -B refresh_hashes.py
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

ATTEMPT = Path(__file__).resolve().parent
EVAL_ATTEMPT = ATTEMPT / "a20260919-01"
ROOT = EVAL_ATTEMPT if EVAL_ATTEMPT.is_dir() else ATTEMPT


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


PRODUCTS = [
    "binding.json",
    "oracle.md",
    "decision.md",
    "commands.json",
    "review.md",
    "run_c3.py",
    "run_c3.cmd",
    "check_r2_consistency.py",
    "check_r3_pairs.py",
    "check_r4_citations.py",
    "check_r4_citation_targets.py",
    "check_r4_final_citations.py",
    "check_r4_anchors.py",
]
HELPERS = [
    "iso/probe_attestation.py",
    "iso/c2_source_hashes.py",
    "iso/c7_baseline_recompute.py",
    "iso/c9_compare.py",
]
ANCHORS = [
    "iso/rf/scripts/revenue_core.py",
    "iso/rf/scripts/revenue_publication.py",
    "iso/rf/scripts/revenue_report.py",
    "iso/rf/scripts/revenue_forecast.py",
    "iso/rf/scripts/publication_registry.py",
    "iso/rf/scripts/contracts/evidence.py",
    "iso/rf/scripts/contracts/constants.py",
    "iso/rf/scripts/contracts/document.py",
]

# 1. refresh handoff.json's own listing (handoff.json + inventory excluded)
handoff_path = ROOT / "handoff.json"
handoff = json.loads(handoff_path.read_text(encoding="utf-8"))
handoff["product_file_hashes"] = {
    rel: sha256(ROOT / rel) for rel in PRODUCTS + HELPERS
}
for rel in ("after/c3_probe.stdout.txt", "after/c7_baseline_recompute.stdout.txt",
            "after/c2_source_hashes.stdout.txt", "after/freeze_timestamps.txt",
            "after/git_status_after.txt", "after/git_delta_analysis.md",
            "after/c9_rerun_compare.stdout.txt",
            "before/git_status_before.txt"):
    handoff["product_file_hashes"][rel] = sha256(ROOT / rel)
handoff_path.write_text(
    json.dumps(handoff, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n"
)
print("handoff.json listing refreshed with " + str(len(handoff["product_file_hashes"])) + " entries")

# 2. regenerate the canonical inventory
lines = ["### sha256 of every product/evidence file of attempt a20260919-01 (read-only listing; canonical inventory)"]
lines.append("### regenerated by refresh_hashes.py after every deliverable was written; it lists itself as unhashable-by-construction")
lines.append("## product files (handoff.json is listed here; it cannot list itself)")
for rel in PRODUCTS + ["handoff.json"]:
    lines.append(f"{sha256(ROOT / rel)}  {rel}")
lines.append("## helper scripts under iso/")
for rel in HELPERS + ["refresh_hashes.py"]:
    lines.append(f"{sha256(ROOT / rel)}  {rel}")
lines.append("## before/after evidence (after/product_hashes.txt excluded: it is this inventory)")
for folder in ("before", "after"):
    for path in sorted((ROOT / folder).glob("*")):
        if path.is_file() and path.name != "product_hashes.txt":
            lines.append(f"{sha256(path)}  {folder}/{path.name}")
lines.append("## iso/rf/scripts anchors (copies of production; must equal the production sha256 in binding.json)")
for rel in ANCHORS:
    lines.append(f"{sha256(ROOT / rel)}  {rel}")
(ROOT / "after" / "product_hashes.txt").write_text(
    "\n".join(lines) + "\n", encoding="utf-8", newline="\n"
)
print("product_hashes.txt regenerated with " + str(len(lines)) + " lines")
