"""Versioned, side-effect-free contracts for immutable upstream sources."""

from .announcement_collector import (
    ANNOUNCEMENT_COLLECTION_ID_PREFIX,
    ANNOUNCEMENT_COLLECTION_SCHEMA_VERSION,
    ANNOUNCEMENT_COLLECTOR_NAME,
    ANNOUNCEMENT_COLLECTOR_VERSION,
    DEFAULT_MAX_BYTES,
    OFFICIAL_EXCHANGE_DOMAINS,
    AnnouncementCollectionError,
    AnnouncementCollectionReceipt,
    AnnouncementConflictError,
    AnnouncementContentError,
    AnnouncementDownloadError,
    AnnouncementURLPolicyError,
    DownloadedAnnouncement,
    collect_announcement,
    download_announcement,
    validate_official_announcement_url,
)

from .compatibility import (
    MINIMUM_DEPRECATION_NOTICE_DAYS,
    MINIMUM_MINOR_OVERLAP_RELEASES,
    SOURCE_CONTRACT_COMPATIBILITY_POLICY_VERSION,
    SOURCE_CONTRACT_NAMES,
    ContractNegotiationError,
    SourceContractCompatibilityError,
    canonical_compatibility_policy_json,
    compatibility_policy_sha256,
    load_compatibility_policy,
    negotiate_contract_versions,
    validate_compatibility_policy,
)

from .evidence_span import (
    EVIDENCE_SPAN_ID_PREFIX,
    EVIDENCE_SPAN_SCHEMA_VERSION,
    EvidenceCoordinates,
    EvidenceSpan,
    EvidenceSpanError,
    ParseStatus,
    QualityFlag,
    evidence_span_id_for,
    output_sha256_for,
)
from .schema import load_evidence_span_schema, load_source_manifest_schema
from .source_export import (
    SOURCE_EXPORT_ID_PREFIX,
    SOURCE_EXPORT_SCHEMA_VERSION,
    SourceExportBundle,
    SourceExportConflictError,
    SourceExportError,
)
from .source_manifest import (
    SOURCE_MANIFEST_SCHEMA_VERSION,
    ImmutableStatus,
    SourceManifest,
    SourceManifestError,
    SourceManifestMismatchError,
    SourceType,
    source_id_for_sha256,
)

__all__ = [
    "ANNOUNCEMENT_COLLECTION_ID_PREFIX",
    "ANNOUNCEMENT_COLLECTION_SCHEMA_VERSION",
    "ANNOUNCEMENT_COLLECTOR_NAME",
    "ANNOUNCEMENT_COLLECTOR_VERSION",
    "EVIDENCE_SPAN_ID_PREFIX",
    "EVIDENCE_SPAN_SCHEMA_VERSION",
    "MINIMUM_DEPRECATION_NOTICE_DAYS",
    "MINIMUM_MINOR_OVERLAP_RELEASES",
    "SOURCE_CONTRACT_COMPATIBILITY_POLICY_VERSION",
    "SOURCE_CONTRACT_NAMES",
    "SOURCE_MANIFEST_SCHEMA_VERSION",
    "SOURCE_EXPORT_ID_PREFIX",
    "SOURCE_EXPORT_SCHEMA_VERSION",
    "DEFAULT_MAX_BYTES",
    "OFFICIAL_EXCHANGE_DOMAINS",
    "AnnouncementCollectionError",
    "AnnouncementCollectionReceipt",
    "AnnouncementConflictError",
    "AnnouncementContentError",
    "AnnouncementDownloadError",
    "AnnouncementURLPolicyError",
    "DownloadedAnnouncement",
    "EvidenceCoordinates",
    "EvidenceSpan",
    "EvidenceSpanError",
    "ContractNegotiationError",
    "ImmutableStatus",
    "ParseStatus",
    "QualityFlag",
    "SourceManifest",
    "SourceManifestError",
    "SourceManifestMismatchError",
    "SourceType",
    "SourceExportBundle",
    "SourceExportConflictError",
    "SourceExportError",
    "SourceContractCompatibilityError",
    "canonical_compatibility_policy_json",
    "collect_announcement",
    "compatibility_policy_sha256",
    "evidence_span_id_for",
    "download_announcement",
    "load_evidence_span_schema",
    "load_compatibility_policy",
    "load_source_manifest_schema",
    "negotiate_contract_versions",
    "output_sha256_for",
    "source_id_for_sha256",
    "validate_compatibility_policy",
    "validate_official_announcement_url",
]
