#!/usr/bin/env python3
"""W06A2 fail-able case suite — I-06-A / a20260922-02.

Frozen expectations live in ../oracle.md §2 + §2-补 (W06A2-P1..N10, W06A2-C8),
frozen BEFORE any run and never generated by the code under test.

One suite, three trees:
  --target before       the pristine production copies   -> RED run
  --target iso          the candidate (fixed) copies     -> GREEN run
  --target iso-mutant   one guard flipped                -> mutation run

Cross-process cases spawn real child processes of THIS file (--child ...).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import sqlite3
import subprocess
import sys
import tempfile
import threading
import time
import traceback
import types
from pathlib import Path

ATTEMPT = Path(__file__).resolve().parents[1]
BLOCK_VERDICT = "prompt_injection_status=not_reviewed (safety block, unchanged by registration)"


# --------------------------------------------------------------------------
# module loading (per tree; bypasses the heavy source_catalog/__init__ while
# importing the real store/processing_demand/prompt_injection modules)
# --------------------------------------------------------------------------
def load_tree(root: Path) -> dict:
    root = Path(root)
    for name in list(sys.modules):
        if name == "company_wiki" or name.startswith("company_wiki."):
            del sys.modules[name]
    src = str(root / "cw" / "src")
    sys.path[:] = [p for p in sys.path if p != src]
    sys.path.insert(0, src)
    import company_wiki  # noqa: F401  (trivial package init)

    stub = types.ModuleType("company_wiki.source_catalog")
    stub.__path__ = [str(root / "cw" / "src" / "company_wiki" / "source_catalog")]
    sys.modules["company_wiki.source_catalog"] = stub
    import company_wiki.source_catalog.processing_demand as pd_mod
    import company_wiki.source_catalog.prompt_injection as pi_mod
    import company_wiki.source_catalog.prompt_injection_guard as pig_mod
    import company_wiki.source_catalog.store as store_mod

    return {
        "root": root,
        "store": store_mod,
        "pd": pd_mod,
        "pi": pi_mod,
        "pig": pig_mod,
    }


class CaseFailure(AssertionError):
    pass


def check(cond: bool, msg: str) -> None:
    if not cond:
        raise CaseFailure(msg)


def expect_error(exc_types, fn, needle: str = ""):
    """Run fn; REQUIRE a coded exception of exc_types (never None / bare)."""
    try:
        result = fn()
    except exc_types as exc:  # noqa: PERF203 - probe harness
        if needle and needle not in f"{type(exc).__name__}: {exc}":
            raise CaseFailure(
                f"wrong refusal message: {type(exc).__name__}: {exc} "
                f"(expected to contain {needle!r})"
            ) from exc
        return exc
    except BaseException as exc:  # noqa: BLE001
        raise CaseFailure(
            f"uncoded/bare refusal: {type(exc).__name__}: {exc}"
        ) from exc
    raise CaseFailure(f"expected a coded refusal, got result {result!r}")


# --------------------------------------------------------------------------
# fixtures
# --------------------------------------------------------------------------
def sample_registration(
    *,
    as_of_date: str = "2026-09-19",
    target: str = "Zijin Mining",
    payload_digest: str = "d" * 64,
    source_sha256: str = "a" * 64,
    review_policy: str = "b" * 64,
    role_set: str = "sections,normalized",
    request_note: str = "r1",
    gaps=None,
    now: float = 1_758_000_000.0,
) -> dict:
    identity = {
        "as_of_date": as_of_date,
        "target": target,
        "payload_digest": payload_digest,
    }
    request_obj = {
        "entity": target,
        "as_of_date": as_of_date,
        "document_kind": "annual",
        "payload_digest": payload_digest,
        "note": request_note,
    }
    request_json = json.dumps(request_obj, ensure_ascii=False, sort_keys=True)
    if gaps is None:
        gaps = [
            {
                "item": "prompt_injection_review",
                "kind": "missing",
                "detail": "observed=not_reviewed",
            },
            {"item": "verified_bytes", "kind": "missing", "detail": "blocked"},
            {"item": "consumer_analysis", "kind": "missing", "detail": "GAP-2 blocked"},
        ]
    return dict(
        kind="source_preparation_blocked",
        source_id="src-1",
        source_sha256=source_sha256,
        review_policy=review_policy,
        role_set=role_set,
        request_identity=identity,
        request_json=request_json,
        gaps=gaps,
        next_action="review source then re-run source preparation",
        now=now,
    )


def request_sha256_of_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def insert_doc_source(t: dict, store, *, document_id="doc-1", source_id="src-1"):
    with store.transaction() as conn:
        conn.execute(
            "INSERT INTO sources (source_id, content_sha256, byte_size, mime_type,"
            " first_seen_at) VALUES (?,?,?,?,?)",
            (source_id, "c" * 64, 12, "text/plain", "2026-09-19T00:00:00Z"),
        )
        conn.execute(
            "INSERT INTO documents (document_id, primary_source_id, title,"
            " source_type, document_kind, published_date, source_status,"
            " metadata_priority, metadata_json, first_seen_at, last_seen_at)"
            " VALUES (?,?,?,?,?,?,?,?,?,?,?)",
            (
                document_id,
                source_id,
                "fixture",
                "filing",
                "annual",
                None,
                "active",
                0,
                "{}",
                "2026-09-19T00:00:00Z",
                "2026-09-19T00:00:00Z",
            ),
        )


def fresh_db(t: dict) -> Path:
    tmp = Path(tempfile.mkdtemp(prefix="w06a2-"))
    return tmp / "catalog.sqlite3"


def child(target: Path, *args: str) -> dict:
    proc = subprocess.run(
        [sys.executable, str(Path(__file__).resolve()), "--target", str(target), "--child", *args],
        capture_output=True,
        text=True,
        timeout=120,
    )
    if proc.returncode != 0:
        raise CaseFailure(f"child failed rc={proc.returncode}: {proc.stderr[-800:]}")
    return json.loads(proc.stdout)


# --------------------------------------------------------------------------
# cases
# --------------------------------------------------------------------------
CASES: list[tuple[str, object]] = []


def case(case_id: str):
    def deco(fn):
        CASES.append((case_id, fn))
        return fn

    return deco


@case("W06A2-P1")
def case_p1_register_before_block(t: dict) -> dict:
    """not_reviewed: durable demand registered BEFORE the block; recoverable
    from a second process; zero fabricated review rows."""
    db = fresh_db(t)
    dstore = t["pd"].CatalogDemandStore(db)
    insert_doc_source(t, dstore._store)
    reg = sample_registration()
    block = t["pd"].register_before_block(dstore, reg, security_verdict=BLOCK_VERDICT)
    check(block.blocked, "block must stay a block")
    check(block.demand is not None, "demand row must exist BEFORE the block is reported")
    check(block.security_verdict == BLOCK_VERDICT, "security verdict must pass through untouched")
    check(block.clause.startswith("demand_queued "), f"clause: {block.clause}")
    demand = block.demand
    check(demand.status == "pending", "registered demand is open (recoverable)")
    check(len(demand.gaps) == 3, "gaps carried")
    check(
        [g.kind for g in demand.gaps] == ["missing", "missing", "missing"],
        "gap three-value semantics recorded",
    )
    check(demand.request_sha256 == request_sha256_of_text(reg["request_json"]),
          "request_sha256 == actual hash of the request bytes")
    check(bool(demand.next_action), "next_action carried")
    # recoverable from a real second process
    seen = child(t["root"], "query", "--db", str(db))
    check(seen["count"] == 1, f"second process must see exactly 1 demand: {seen}")
    row = seen["demands"][0]
    check(row["demand_id"] == demand.demand_id, "same durable id across processes")
    check(row["source_sha256"] == reg["source_sha256"], "source/hash/policy binding")
    check(row["review_policy"] == reg["review_policy"], "policy binding")
    check(row["request_sha256"] == demand.request_sha256, "request binding persisted")
    # zero fabricated review rows (card: 没有伪造 review)
    receipt = t["pi"].read_prompt_injection_review(dstore._store, "doc-1")
    check(receipt is None, "no review receipt may be fabricated by registration")
    return {"demand_id": demand.demand_id, "clause": block.clause, "cross_process": seen["count"]}


@case("W06A2-P2")
def case_p2_cross_process_idempotent(t: dict) -> dict:
    """Identical request resubmitted from another process -> SAME demand id,
    exactly one active todo (not per-process pd-0 pseudo-sameness)."""
    db = fresh_db(t)
    dstore = t["pd"].CatalogDemandStore(db)
    reg = sample_registration()
    first = dstore.register(**reg)
    spec = Path(db.parent / "spec.json")
    spec.write_text(json.dumps(reg), encoding="utf-8")
    again = child(t["root"], "register", "--db", str(db), "--spec", str(spec))
    check(again["demand_id"] == first.demand_id,
          f"same demand id across processes: {again['demand_id']} vs {first.demand_id}")
    seen = child(t["root"], "query", "--db", str(db))
    check(seen["count"] == 1, f"exactly one todo: {seen['count']}")
    check(again["demand_id"].startswith("demand-") and again["demand_id"] != "pd-0",
          "durable identity, not per-process pd-0")
    return {"demand_id": first.demand_id, "rows": seen["count"]}


@case("W06A2-P3")
def case_p3_n1_upgrade(t: dict) -> dict:
    """N-1 upgrade path through the production _apply_additive_migrations
    shape (FIX-W06-GAPS P1 defect class must not recur)."""
    out = {}
    # ---- variant A: N-1 catalog built by the PREVIOUS build (before tree) ----
    db = fresh_db(t)
    old = load_tree(ATTEMPT / "before")
    old_store = old["store"].CatalogStore(db)
    insert_doc_source(old, old_store)
    del old_store
    tables_before = _table_names(db)
    check("processing_demands" not in tables_before, "fixture is genuinely N-1")
    t2 = load_tree(t["root"])  # back to the target tree
    dstore = t2["pd"].CatalogDemandStore(db)
    demand = dstore.register(**sample_registration())
    claimed = dstore.claim(demand_id=demand.demand_id, owner="w1", lease_seconds=30, now=2_000.0)
    check(claimed.status == "running", "register+claim work on the upgraded DB")
    with sqlite3.connect(db) as conn:
        kept = conn.execute("SELECT COUNT(*) FROM documents").fetchone()[0]
    check(kept == 1, "pre-existing rows preserved across the upgrade")
    out["variant_a"] = "table added, old rows preserved, register+claim ok"

    # ---- variant B: N-1 catalog with an OLDER, NARROWER processing_demands
    # table (the exact P1 shape: missing request_sha256 / lease_until) ----
    db2 = fresh_db(t)
    old = load_tree(ATTEMPT / "before")
    old_store = old["store"].CatalogStore(db2)
    insert_doc_source(old, old_store)
    del old_store
    with sqlite3.connect(db2) as conn:
        conn.execute("DROP TABLE IF EXISTS processing_demands")
        conn.execute("DROP TABLE IF EXISTS processing_demand_events")
        conn.execute(
            "CREATE TABLE processing_demands ("
            " demand_id TEXT PRIMARY KEY, demand_key TEXT NOT NULL UNIQUE,"
            " kind TEXT NOT NULL, status TEXT NOT NULL, source_id TEXT,"
            " source_sha256 TEXT NOT NULL, review_policy TEXT NOT NULL,"
            " role_set TEXT NOT NULL, request_json TEXT NOT NULL,"
            " gaps_json TEXT NOT NULL, next_action TEXT NOT NULL,"
            " created_at REAL)"
        )
        conn.execute(
            "INSERT INTO processing_demands VALUES (?,?,?,?,?,?,?,?,?,?,?,?)",
            ("demand-legacy000000", "k" * 64, "legacy", "pending", None,
             "a" * 64, "b" * 64, "normalized,sections", "{}", "[]", "legacy", 1.0),
        )
    t3 = load_tree(t["root"])
    dstore2 = t3["pd"].CatalogDemandStore(db2)
    cols = _columns(db2, "processing_demands")
    check("request_sha256" in cols and "lease_until" in cols,
          f"P1 class: N-1 columns must be ADDED by the migration, got {sorted(cols)}")
    rows = dstore2.list()
    check(any(r.demand_id == "demand-legacy000000" for r in rows), "legacy row preserved")
    demand2 = dstore2.register(**sample_registration(as_of_date="2027-03-31"))
    dstore2.claim(demand_id=demand2.demand_id, owner="w1", lease_seconds=30, now=2_000.0)
    out["variant_b"] = f"columns backfilled {sorted(cols)}, legacy row kept, register+claim ok"
    return out


@case("W06A2-P4")
def case_p4_claim_lease_lifecycle(t: dict) -> dict:
    """Explicit single-shot claim; exactly one winner; in-lease complete/fail;
    terminal_failed carries a reason."""
    db = fresh_db(t)
    dstore = t["pd"].CatalogDemandStore(db, max_attempts=3, backoff_base=60.0)
    d1 = dstore.register(**sample_registration())
    running = dstore.claim(demand_id=d1.demand_id, owner="worker-a", lease_seconds=30, now=100.0)
    check(running.status == "running" and running.lease_owner == "worker-a",
          "claim grants a lease")
    done = dstore.complete(demand_id=d1.demand_id, owner="worker-a", now=110.0)
    check(done.status == "completed", "in-lease complete succeeds")
    with sqlite3.connect(db) as conn:
        events = [r[0] for r in conn.execute(
            "SELECT event_type FROM processing_demand_events ORDER BY rowid")]
    check(events == ["register", "claim", "complete"], f"lifecycle trail: {events}")

    d2 = dstore.register(**sample_registration(as_of_date="2026-12-31"))
    dstore.claim(demand_id=d2.demand_id, owner="worker-a", lease_seconds=30, now=200.0)
    failed = dstore.fail(demand_id=d2.demand_id, owner="worker-a", now=210.0)
    check(failed.status == "failed" and failed.retry_at is not None, "failed is retryable")
    dstore.claim(demand_id=d2.demand_id, owner="worker-a", lease_seconds=30, now=300.0)
    failed2 = dstore.fail(demand_id=d2.demand_id, owner="worker-a", now=310.0)
    check(failed2.status == "failed", "second attempt still retryable")
    dstore.claim(demand_id=d2.demand_id, owner="worker-a", lease_seconds=30, now=500.0)
    exc = expect_error(
        t["pd"].DemandStateError,
        lambda: dstore.fail(demand_id=d2.demand_id, owner="worker-a", now=510.0),
        needle="reason",
    )
    check(isinstance(exc, t["pd"].DemandQueueError), "coded refusal")
    terminal = dstore.fail(demand_id=d2.demand_id, owner="worker-a", now=520.0,
                           reason="upstream document withdrawn")
    check(terminal.status == "terminal_failed" and terminal.terminal_reason,
          "terminal_failed MUST carry a reason")
    return {"events": events, "terminal": terminal.status}


@case("W06A2-N1")
def case_n1_request_identity_in_key(t: dict) -> dict:
    """c8/c9/c10 counterexample must now pass: same source/policy/roles with a
    different as_of_date = TWO demand rows; row request_sha256 == its own
    request hash; changed source hash = new demand, old demand stays open."""
    db = fresh_db(t)
    dstore = t["pd"].CatalogDemandStore(db)
    reg_a = sample_registration(as_of_date="2026-09-19")
    reg_b = sample_registration(as_of_date="2027-03-31")  # c10: ONLY as_of_date
    d_a = dstore.register(**reg_a)
    d_b = dstore.register(**reg_b)
    check(d_a.demand_id != d_b.demand_id,
          f"as_of_date-divergent requests must be TWO rows: {d_a.demand_id} vs {d_b.demand_id}")
    check(d_a.demand_key != d_b.demand_key, "distinct frozen keys")
    check(d_a.request_sha256 == request_sha256_of_text(reg_a["request_json"]),
          "row A binds request A (not the first request of the pair)")
    check(d_b.request_sha256 == request_sha256_of_text(reg_b["request_json"]),
          "row B binds request B")
    check(d_a.request_sha256 != d_b.request_sha256, "no silent absorption (c8/c9)")
    # c8/c9 variant: entity AND as_of_date change
    reg_c = sample_registration(as_of_date="2026-09-19", target="Zijin Mining H")
    d_c = dstore.register(**reg_c)
    check(len({d_a.demand_id, d_b.demand_id, d_c.demand_id}) == 3, "c8/c9: three rows")
    # resubmission of A is still idempotent
    d_a2 = dstore.register(**reg_a)
    check(d_a2.demand_id == d_a.demand_id, "identical request reuses its demand")
    # changed source hash -> new demand, old demand NOT closed
    reg_d = sample_registration(as_of_date="2026-09-19", source_sha256="e" * 64)
    d_d = dstore.register(**reg_d)
    check(d_d.demand_id != d_a.demand_id, "changed source => new demand")
    check(dstore.get(d_a.demand_id).status == "pending", "old demand stays open")
    active = [r for r in dstore.list() if r.status in ("pending", "running", "failed")]
    check(len(active) == 4, f"four independent active demands: {len(active)}")
    seen = child(t["root"], "query", "--db", str(db))
    check(seen["count"] == 4, "cross-process view agrees")
    return {"rows": len(active), "ids": [d_a.demand_id, d_b.demand_id, d_c.demand_id, d_d.demand_id]}


@case("W06A2-N2")
def case_n2_store_write_failure(t: dict) -> dict:
    """DB write failure: NO demand_queued; security verdict + demand_store_error=
    clause; no memory fallback; row count unchanged."""
    db = fresh_db(t)
    dstore = t["pd"].CatalogDemandStore(db)
    dstore.register(**sample_registration())
    with sqlite3.connect(db) as conn:
        conn.execute("DROP TABLE processing_demands")
        conn.execute("DROP TABLE processing_demand_events")
        conn.execute("DROP TABLE IF EXISTS probe_rows")
        conn.execute("CREATE TABLE probe_rows (n INTEGER)")
        conn.execute("INSERT INTO probe_rows VALUES (7)")
    reg = sample_registration(as_of_date="2027-03-31")
    block = t["pd"].register_before_block(dstore, reg, security_verdict=BLOCK_VERDICT)
    check(block.blocked and block.demand is None, "no demand reported as queued")
    check("demand_queued" not in block.clause, f"must not report demand_queued: {block.clause}")
    check(block.clause.startswith("demand_store_error="), f"clause: {block.clause}")
    check(block.security_verdict == BLOCK_VERDICT, "security verdict unchanged on failure")
    with sqlite3.connect(db) as conn:
        rows = conn.execute("SELECT n FROM probe_rows").fetchall()
    check(rows == [(7,)], "row count unchanged (no half write)")
    check(isinstance(block.demand, type(None)), "no memory fallback object handed back")
    return {"clause": block.clause}


@case("W06A2-N3")
def case_n3_paused_no_auto_resume(t: dict) -> dict:
    """Registration/query must not auto-resume, auto-claim or start any
    background scheduler/thread (OPEN-3)."""
    threads_before = sorted(th.name for th in threading.enumerate())
    db = fresh_db(t)
    dstore = t["pd"].CatalogDemandStore(db)
    d = dstore.register(**sample_registration())
    listed = dstore.list()
    threads_after = sorted(th.name for th in threading.enumerate())
    check(threads_before == threads_after, f"no thread/scheduler started: {threads_before} -> {threads_after}")
    row = dstore.get(d.demand_id)
    check(row.status == "pending" and row.lease_owner is None,
          "registration must not claim/advance the demand")
    check(len(listed) == 1, "query is read-only")
    return {"threads_before": threads_before, "threads_after": threads_after}


@case("W06A2-N4")
def case_n4_defined_refusals(t: dict) -> dict:
    """Coded refusals everywhere: no bare None, no bare sqlite3 exceptions
    (P2-B / P3-B / P6-B defect classes)."""
    pd_mod = t["pd"]
    db = fresh_db(t)
    dstore = pd_mod.CatalogDemandStore(db)
    # unknown id
    expect_error(pd_mod.DemandNotFoundError,
                 lambda: dstore.get("demand-nope"), needle="no demand")
    expect_error(pd_mod.DemandNotFoundError,
                 lambda: dstore.claim(demand_id="demand-nope", owner="w", lease_seconds=10, now=1.0))
    d = dstore.register(**sample_registration())
    # invalid claim parameters
    expect_error(pd_mod.DemandStateError,
                 lambda: dstore.claim(demand_id=d.demand_id, owner="", lease_seconds=10, now=1.0))
    expect_error(pd_mod.DemandStateError,
                 lambda: dstore.claim(demand_id=d.demand_id, owner="w", lease_seconds=0, now=1.0))
    expect_error(pd_mod.DemandStateError,
                 lambda: dstore.claim(demand_id=d.demand_id, owner="w", lease_seconds=-5, now=1.0))
    # second claimant while the lease is active -> DEFINED rejection, not None
    dstore.claim(demand_id=d.demand_id, owner="worker-a", lease_seconds=30, now=100.0)
    exc = expect_error(pd_mod.DemandStateError,
                       lambda: dstore.claim(demand_id=d.demand_id, owner="worker-b",
                                            lease_seconds=30, now=105.0), needle="running")
    check(isinstance(exc, pd_mod.DemandQueueError) and not isinstance(exc, sqlite3.Error),
          "refusal is coded, not a bare sqlite3 error")
    # lease-expired operations refuse (and point at explicit reclaim)
    expect_error(pd_mod.DemandStateError,
                 lambda: dstore.complete(demand_id=d.demand_id, owner="worker-a", now=200.0),
                 needle="expired")
    expect_error(pd_mod.DemandStateError,
                 lambda: dstore.claim(demand_id=d.demand_id, owner="worker-b",
                                      lease_seconds=30, now=200.0))
    # explicit reclaim (P3 stranding class) then a fresh claim works
    n = dstore.reclaim_expired(now=200.0)
    check(n == 1, "explicit reclaim returns the stranded row")
    again = dstore.claim(demand_id=d.demand_id, owner="worker-b", lease_seconds=30, now=201.0)
    check(again.status == "running", "row is claimable again after explicit reclaim")
    # wrong-owner lifecycle calls
    expect_error(pd_mod.DemandStateError,
                 lambda: dstore.complete(demand_id=d.demand_id, owner="worker-a", now=205.0),
                 needle="owned by")
    # invalid registration input -> coded refusal
    bad = sample_registration()
    bad["gaps"] = [{"item": "x", "kind": "ok"}]
    expect_error(pd_mod.DemandRegistrationError, lambda: dstore.register(**bad), needle="missing")
    bad2 = sample_registration()
    bad2["request_identity"] = {}
    expect_error(pd_mod.DemandRegistrationError, lambda: dstore.register(**bad2))
    return {"refusals": "all coded"}


@case("W06A2-N5")
def case_n5_concurrent_conflict_defined(t: dict) -> dict:
    """Concurrent writes never silently lose data: same-key/different-payload
    = coded conflict (P6-A class); concurrent claim = one winner + coded
    rejection for the loser (P2-B class)."""
    pd_mod = t["pd"]
    db = fresh_db(t)
    dstore = pd_mod.CatalogDemandStore(db)
    reg_a = sample_registration(request_note="payload-A")
    reg_b = sample_registration(request_note="payload-B")  # same identity, other bytes
    first = dstore.register(**reg_a)
    exc = expect_error(pd_mod.DemandIdempotencyViolation,
                       lambda: dstore.register(**reg_b), needle="silent merge")
    check(isinstance(exc, pd_mod.DemandStateError), "coded idempotency conflict")
    kept = dstore.get(first.demand_id)
    check(kept.request_sha256 == request_sha256_of_text(reg_a["request_json"]),
          "existing row NOT overwritten (no silent merge of the c8/c9 family)")
    check(len(dstore.list()) == 1, "no extra row, no lost write")

    # concurrent claim: exactly one winner, loser gets a coded refusal
    target = dstore.register(**sample_registration(as_of_date="2027-03-31"))
    barrier = threading.Barrier(2)
    wins: list[str] = []
    losses: list[BaseException] = []

    def racer(name: str):
        store2 = pd_mod.CatalogDemandStore(db)
        barrier.wait()
        try:
            store2.claim(demand_id=target.demand_id, owner=name, lease_seconds=30, now=100.0)
            wins.append(name)
        except BaseException as exc:  # noqa: BLE001
            losses.append(exc)

    threads = [threading.Thread(target=racer, args=(f"w{i}",)) for i in (1, 2)]
    for th in threads:
        th.start()
    for th in threads:
        th.join(timeout=60)
    check(len(wins) == 1, f"exactly one claim winner: {wins}")
    check(len(losses) == 1 and isinstance(losses[0], pd_mod.DemandStateError),
          f"loser must get a coded refusal, not None: {losses!r}")
    # concurrent identical registration: idempotent, exactly one row
    reg = sample_registration(as_of_date="2028-12-31")
    barrier2 = threading.Barrier(2)
    ids: list[str] = []
    errs: list[BaseException] = []

    def reg_racer():
        store2 = pd_mod.CatalogDemandStore(db)
        barrier2.wait()
        try:
            ids.append(store2.register(**reg).demand_id)
        except BaseException as exc:  # noqa: BLE001
            errs.append(exc)

    threads = [threading.Thread(target=reg_racer) for _ in range(2)]
    for th in threads:
        th.start()
    for th in threads:
        th.join(timeout=60)
    check(not errs and len(set(ids)) == 1, f"identical concurrent register is idempotent: {ids} {errs}")
    return {"winner": wins[0], "loser": type(losses[0]).__name__}


@case("W06A2-N6")
def case_n6_receipt_invalidation_independence(t: dict) -> dict:
    """OPEN-4 semantics: receipt invalidation does NOT close/modify a demand;
    closing a demand does NOT rewrite the receipt."""
    pd_mod, pi_mod, pig_mod, store_mod = t["pd"], t["pi"], t["pig"], t["store"]
    db = fresh_db(t)
    dstore = pd_mod.CatalogDemandStore(db)
    insert_doc_source(t, dstore._store)
    source_sha = "c" * 64
    policy_hash = "b" * 64
    with dstore._store.transaction() as conn:
        pi_mod.record_prompt_injection_review(
            conn, "doc-1", status="not_detected", reviewer="zr302-test",
            evidence_sha256="e" * 64, now="2026-09-19T00:00:00Z",
            source_sha256=source_sha, policy_hash=policy_hash,
        )
    demand = dstore.register(**sample_registration(source_sha256=source_sha,
                                                   review_policy=policy_hash))
    row_before = _demand_row_dump(db, demand.demand_id)
    receipt_before = _metadata_of(db, "doc-1")
    # invalidate the receipt (policy changed since review => not_reviewed)
    ev = pig_mod.evaluate_review(
        dstore._store, "doc-1", source_sha256=source_sha,
        policy_hash="f" * 64, now="2026-09-20T00:00:00Z", ttl_seconds=86400,
    )
    check(ev.status == "not_reviewed" and ev.cache_state == "ignored",
          f"receipt invalidated: {ev}")
    row_after = _demand_row_dump(db, demand.demand_id)
    check(row_after == row_before, f"demand row must survive receipt invalidation unchanged: {row_before} -> {row_after}")
    check(dstore.get(demand.demand_id).status == "pending", "demand still open")
    # close the demand; the receipt must be untouched
    dstore.claim(demand_id=demand.demand_id, owner="w1", lease_seconds=30, now=100.0)
    dstore.complete(demand_id=demand.demand_id, owner="w1", now=110.0)
    receipt_after = _metadata_of(db, "doc-1")
    check(receipt_after == receipt_before, "closing a demand never rewrites the receipt")
    return {"receipt_cache_state": ev.cache_state, "demand_status_after": "completed"}


@case("W06A2-N7")
def case_n7_gaps_three_values(t: dict) -> dict:
    """missing / unsupported / not_applicable are distinguishable and survive a
    round-trip; anything else is refused (no silent states)."""
    pd_mod = t["pd"]
    check(pd_mod.GAP_KINDS == {"missing", "unsupported", "not_applicable"},
          f"closed three-value vocabulary: {pd_mod.GAP_KINDS}")
    db = fresh_db(t)
    dstore = pd_mod.CatalogDemandStore(db)
    gaps = [
        {"item": "prompt_injection_review", "kind": "missing", "detail": "not_reviewed"},
        {"item": "consumer_analysis", "kind": "unsupported", "detail": "no producer"},
        {"item": "sections", "kind": "not_applicable", "detail": "role not requested"},
    ]
    d = dstore.register(**sample_registration(gaps=gaps))
    back = dstore.get(d.demand_id).gaps
    check([g.kind for g in back] == ["missing", "unsupported", "not_applicable"],
          f"three values preserved and distinguishable: {back}")
    check(len({g.kind for g in back}) == 3, "distinguishable")
    for bad_kind in ("ok", "clean", "reviewed_ok", "MISSING", None, ""):
        bad = sample_registration(gaps=[{"item": "x", "kind": bad_kind}])
        expect_error(pd_mod.DemandRegistrationError, lambda b=bad: dstore.register(**b),
                     needle="missing")
    clean_claim = sample_registration(gaps=[{"item": "x", "kind": "detected_and_ignored"}])
    expect_error(pd_mod.DemandRegistrationError, lambda: dstore.register(**clean_claim),
                 needle="missing")
    check(all(g.kind in pd_mod.GAP_KINDS for g in back), "no clean/ok silent state exists")
    return {"kinds": sorted(pd_mod.GAP_KINDS)}


@case("W06A2-N8")
def case_n8_ttl_policy_cap(t: dict) -> dict:
    """Owner option A: 30d policy cap; callers may only tighten (OPEN-6 C6)."""
    pig_mod, pi_mod, pd_mod = t["pig"], t["pi"], t["pd"]
    check(pig_mod.RECEIPT_TTL_POLICY_CAP_SECONDS == 86400 * 30,
          f"owner TTL option A constant: {pig_mod.RECEIPT_TTL_POLICY_CAP_SECONDS}")
    check(pig_mod.effective_receipt_ttl(10 ** 30) == 86400 * 30, "ttl=inf clipped to the cap")
    check(pig_mod.effective_receipt_ttl(3600.0) == 3600.0, "tightening allowed")
    db = fresh_db(t)
    dstore = pd_mod.CatalogDemandStore(db)
    insert_doc_source(t, dstore._store)
    source_sha, policy_hash = "c" * 64, "b" * 64
    reviewed_epoch = time.time() - pig_mod.RECEIPT_TTL_POLICY_CAP_SECONDS - 120
    reviewed_at = _iso(reviewed_epoch)
    with dstore._store.transaction() as conn:
        pi_mod.record_prompt_injection_review(
            conn, "doc-1", status="not_detected", reviewer="zr302-test",
            evidence_sha256="e" * 64, now=reviewed_at,
            source_sha256=source_sha, policy_hash=policy_hash,
        )
    # ttl=inf + now in the past must NOT revive the expired receipt
    ev = pig_mod.evaluate_review(
        dstore._store, "doc-1", source_sha256=source_sha, policy_hash=policy_hash,
        now=_iso(reviewed_epoch + 1), ttl_seconds=10 ** 30,
    )
    check(ev.status == "not_reviewed" and ev.cache_state == "expired",
          f"expired receipt must stay expired: {ev}")
    # tightening works: a 1h TTL expires a 2h-old review
    with dstore._store.transaction() as conn:
        pi_mod.record_prompt_injection_review(
            conn, "doc-1", status="not_detected", reviewer="zr302-test",
            evidence_sha256="e" * 64, now=_iso(time.time() - 7200),
            source_sha256=source_sha, policy_hash=policy_hash,
        )
    ev2 = pig_mod.evaluate_review(
        dstore._store, "doc-1", source_sha256=source_sha, policy_hash=policy_hash,
        now=_iso(time.time()), ttl_seconds=3600,
    )
    check(ev2.status == "not_reviewed" and ev2.cache_state == "expired",
          f"caller-tightened TTL respected: {ev2}")
    return {"cap": pig_mod.RECEIPT_TTL_POLICY_CAP_SECONDS, "expired": ev.cache_state}


@case("W06A2-N9")
def case_n9_prune_archival_exemption(t: dict) -> dict:
    """OPEN-5 4.3: demand rows are exempt from document prune/archival."""
    store_mod, pd_mod = t["store"], t["pd"]
    db = fresh_db(t)
    dstore = pd_mod.CatalogDemandStore(db)
    insert_doc_source(t, dstore._store)
    d = dstore.register(**sample_registration())
    store_mod.retire_document(dstore._store, document_id="doc-1",
                              reason="retired", created_by="w06a2")
    # archival deletion pattern of the real cleanup paths (prune_retired_evidence /
    # reconcile_retire_state.py:195-199 / focus_cleanup.py:538-543): the
    # document's dependent rows are purged in FK order — and the demand tables
    # are NEVER in that set (lifecycle exemption, OPEN-5 ruling 4.3).
    with dstore._store.transaction() as conn:
        for table in ("document_fingerprint_state", "document_retire_audit",
                      "evidence_spans", "artifacts", "locations"):
            conn.execute(f"DELETE FROM {table} WHERE document_id=?", ("doc-1",))
        conn.execute("DELETE FROM documents WHERE source_status='retired'")
        conn.execute("DELETE FROM sources WHERE source_id=?", ("src-1",))
    rows = dstore.list()
    check(len(rows) == 1 and rows[0].demand_id == d.demand_id,
          f"non-terminal demand row survives prune/archival: {rows}")
    check(rows[0].status == "pending", "status unchanged")
    claimed = dstore.claim(demand_id=d.demand_id, owner="w1", lease_seconds=30, now=5.0)
    check(claimed.status == "running", "demand still usable after archival")
    return {"rows_after_archival": len(rows)}


@case("W06A2-C8")
def case_c8_error_contract_pinned(t: dict) -> dict:
    """c7/c8 error contract: clause strings pinned verbatim."""
    pd_mod = t["pd"]
    record = pd_mod.ProcessingDemandRecord(
        demand_id="demand-0123456789abcdef",
        demand_key="k" * 64,
        kind="source_preparation_blocked",
        status="pending",
        source_id="src-1",
        source_sha256="a" * 64,
        review_policy="b" * 64,
        role_set="normalized,sections",
        request_identity={"as_of_date": "2026-09-19"},
        request_sha256="0" * 64,
        request_json="{}",
        gaps=(
            pd_mod.DemandGap(item="g1", kind="missing"),
            pd_mod.DemandGap(item="g2", kind="missing"),
        ),
        next_action="review source then re-run source preparation",
        priority=0, attempts=0, lease_owner=None, lease_until=None,
        retry_at=None, terminal_reason=None, created_at=0.0, updated_at=0.0,
    )
    expected_queued = (
        "demand_queued demand_id=demand-0123456789abcdef gaps=2 "
        "next_action=review source then re-run source preparation"
    )
    check(pd_mod.demand_queued_clause(record) == expected_queued,
          f"PINNED demand_queued clause: {pd_mod.demand_queued_clause(record)!r}")
    err = pd_mod.DemandStoreUnavailable("sqlite3.OperationalError: database is locked")
    expected_err = "demand_store_error=DemandStoreUnavailable: sqlite3.OperationalError: database is locked"
    check(pd_mod.demand_store_error_clause(err) == expected_err,
          f"PINNED demand_store_error clause: {pd_mod.demand_store_error_clause(err)!r}")
    check(expected_queued[:14] == "demand_queued " and expected_err[:19] == "demand_store_error=",
          "contract prefixes")
    return {"queued_clause": expected_queued, "error_clause": expected_err}


@case("W06A2-N10")
def case_n10_state_domain_disambiguation(t: dict) -> dict:
    """cache_state='ignored' (cache domain) vs detected_and_ignored (review
    domain): explicit state_domain assertion field, fail-closed."""
    pig_mod = t["pig"]
    check(pig_mod.state_domain_of("ignored") == pig_mod.STATE_DOMAIN_CACHE, "ignored = cache domain")
    check(pig_mod.state_domain_of("detected_and_ignored") == pig_mod.STATE_DOMAIN_REVIEW,
          "detected_and_ignored = review domain")
    check(pig_mod.state_domain_of("ignored") != pig_mod.state_domain_of("detected_and_ignored"),
          "the two senses are distinguishable")
    expect_error(pig_mod.PromptInjectionGuardError,
                 lambda: pig_mod.require_state_domain("detected_and_ignored", "cache"),
                 needle="never be conflated")
    expect_error(pig_mod.PromptInjectionGuardError,
                 lambda: pig_mod.require_state_domain("ignored", "review"),
                 needle="never be conflated")
    expect_error(pig_mod.PromptInjectionGuardError,
                 lambda: pig_mod.ReviewEvaluation(status="not_reviewed", cache_state="hit",
                                                  state_domain="bogus"),
                 needle="state_domain")
    expect_error(pig_mod.PromptInjectionGuardError,
                 lambda: pig_mod.ReviewEvaluation(status="not_reviewed", cache_state="hit",
                                                  state_domain="review"),
                 needle="never be conflated")
    ok = pig_mod.ReviewEvaluation(status="not_reviewed", cache_state="ignored",
                                  reason="policy ruleset changed since review")
    check(ok.state_domain == "cache", "evaluations carry the assertion field")
    return {"cache_domain": pig_mod.STATE_DOMAIN_CACHE, "review_domain": pig_mod.STATE_DOMAIN_REVIEW}


@case("W06A2-N8b")
def case_n8b_nonfinite_gate(t: dict) -> dict:
    """F1 (review BLOCKING): non-finite ttl/now must never WIDEN the freshness
    window (OPEN-6 C6).  Pre-fix, ttl=NaN sailed past `NaN < 0`, survived
    `min(NaN, cap) = NaN`, and made `age > NaN` always False — an expired
    receipt became immortal = caller-widening.  Frozen contract (remediation
    option (a), rationale in decision.md; CLIP-vs-REJECT stays with the
    parent): non-finite input is INVALID => coded PromptInjectionGuardError;
    finite over-cap values keep the CLIP mechanism unchanged."""
    pig_mod, pi_mod, pd_mod = t["pig"], t["pi"], t["pd"]
    db = fresh_db(t)
    dstore = pd_mod.CatalogDemandStore(db)
    insert_doc_source(t, dstore._store)
    source_sha, policy_hash = "c" * 64, "b" * 64
    reviewed_epoch = time.time() - pig_mod.RECEIPT_TTL_POLICY_CAP_SECONDS - 120
    with dstore._store.transaction() as conn:
        pi_mod.record_prompt_injection_review(
            conn, "doc-1", status="not_detected", reviewer="zr302-test",
            evidence_sha256="e" * 64, now=_iso(reviewed_epoch),
            source_sha256=source_sha, policy_hash=policy_hash,
        )
    # (1) end-to-end: ttl=NaN on an ALREADY-EXPIRED receipt.  A silent result
    # is a revival (the F1 fail-open); the fixed contract is a coded refusal.
    revived = None
    refusal = None
    try:
        revived = pig_mod.evaluate_review(
            dstore._store, "doc-1", source_sha256=source_sha,
            policy_hash=policy_hash, now=_iso(time.time()),
            ttl_seconds=float("nan"),
        )
    except pig_mod.PromptInjectionGuardError as exc:
        refusal = exc
    if revived is not None:
        check(
            False,
            f"NaN ttl revived an already-expired receipt (F1 fail-open, OPEN-6 C6): {revived!r}",
        )
    check(refusal is not None and "finite" in str(refusal),
          f"non-finite ttl must be a coded refusal carrying 'finite': {refusal!r}")
    # (2) helper level: every non-finite input refused with the coded error
    expect_error(pig_mod.PromptInjectionGuardError,
                 lambda: pig_mod.effective_receipt_ttl(float("nan")), needle="finite")
    expect_error(pig_mod.PromptInjectionGuardError,
                 lambda: pig_mod.effective_receipt_ttl(float("inf")), needle="finite")
    expect_error(pig_mod.PromptInjectionGuardError,
                 lambda: pig_mod.effective_review_instant(float("nan")), needle="finite")
    # (3) finite over-cap values STILL clip to the cap — the mechanism itself
    # is unchanged (the CLIP-vs-REJECT standardization stays with the parent).
    check(pig_mod.effective_receipt_ttl(10 ** 30) == pig_mod.RECEIPT_TTL_POLICY_CAP_SECONDS,
          "finite over-cap must stay CLIPped to the policy cap")
    # (4) garbage STRING `now` keeps the frozen tamper path (fail-closed, no hit)
    ev_str = pig_mod.evaluate_review(
        dstore._store, "doc-1", source_sha256=source_sha,
        policy_hash=policy_hash, now="nan", ttl_seconds=86400.0,
    )
    check(ev_str.status == "not_reviewed" and ev_str.cache_state == "tampered",
          f"unparseable now must fail closed as tampered: {ev_str!r}")
    return {"nonfinite": "coded refusal", "finite_over_cap": "clipped"}


@case("W06A2-N11")
def case_n11_identity_covers_three(t: dict) -> dict:
    """F6 (review low -> tightened): request_identity must COVER all three
    ruled fields (as_of_date / target / payload digest — OPEN-2 option A
    wording is 覆盖 the three).  The old any-of rule let a partial identity
    pass, so divergence in an OMITTED field collided at one key
    (DemandIdempotencyViolation) where the ruling promises two demand rows."""
    pd_mod = t["pd"]
    db = fresh_db(t)
    dstore = pd_mod.CatalogDemandStore(db)
    ok = dstore.register(**sample_registration())
    check(bool(ok.demand_id), "positive control: full three-field identity is accepted")
    partials = [
        {"as_of_date": "2026-09-19", "target": "Zijin Mining"},
        {"as_of_date": "2026-09-19", "payload_digest": "d" * 64},
        {"target": "Zijin Mining", "payload_digest": "d" * 64},
        {"as_of_date": "2026-09-19"},
        {"as_of_date": "2026-09-19", "target": "Zijin Mining", "payload_digest": ""},
        {"as_of_date": "2026-09-19", "target": "Zijin Mining", "payload_digest": None},
    ]
    for partial in partials:
        reg = sample_registration()
        reg["request_identity"] = partial
        reg["request_json"] = json.dumps({"variant": partial}, sort_keys=True)
        expect_error(pd_mod.DemandRegistrationError,
                     lambda r=reg: dstore.register(**r), needle="cover")
    check(len(dstore.list()) == 1,
          "partial identities create ZERO rows (garbage in, no tasks out)")
    return {"partials_refused": len(partials), "rows": len(dstore.list())}


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------
def _table_names(db: Path) -> set[str]:
    with sqlite3.connect(db) as conn:
        return {r[0] for r in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")}


def _columns(db: Path, table: str) -> set[str]:
    with sqlite3.connect(db) as conn:
        return {r[1] for r in conn.execute(f"PRAGMA table_info({table})")}


def _demand_row_dump(db: Path, demand_id: str) -> dict:
    with sqlite3.connect(db) as conn:
        conn.row_factory = sqlite3.Row
        row = conn.execute(
            "SELECT * FROM processing_demands WHERE demand_id=?", (demand_id,)
        ).fetchone()
    return {k: row[k] for k in row.keys()}


def _metadata_of(db: Path, document_id: str) -> str:
    with sqlite3.connect(db) as conn:
        return str(conn.execute(
            "SELECT metadata_json FROM documents WHERE document_id=?", (document_id,)
        ).fetchone()[0])


def _iso(epoch: float) -> str:
    from datetime import datetime, timezone

    return datetime.fromtimestamp(epoch, tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# --------------------------------------------------------------------------
# child (cross-process) entry points
# --------------------------------------------------------------------------
def run_child(target: str, argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("op", choices=["register", "query", "claim"])
    parser.add_argument("--db", required=True)
    parser.add_argument("--spec")
    parser.add_argument("--demand-id")
    parser.add_argument("--owner", default="child-worker")
    parser.add_argument("--lease", type=float, default=30.0)
    parser.add_argument("--now", type=float, default=100.0)
    args = parser.parse_args(argv)
    t = load_tree(Path(target))
    dstore = t["pd"].CatalogDemandStore(Path(args.db))
    if args.op == "register":
        spec = json.loads(Path(args.spec).read_text(encoding="utf-8"))
        block = t["pd"].register_before_block(dstore, spec, security_verdict=BLOCK_VERDICT)
        out = {
            "demand_id": block.demand.demand_id if block.demand else None,
            "clause": block.clause,
        }
    elif args.op == "query":
        rows = dstore.list()
        out = {
            "count": len(rows),
            "demands": [
                {
                    "demand_id": r.demand_id,
                    "status": r.status,
                    "source_sha256": r.source_sha256,
                    "review_policy": r.review_policy,
                    "request_sha256": r.request_sha256,
                    "next_action": r.next_action,
                }
                for r in rows
            ],
        }
    else:
        try:
            row = dstore.claim(demand_id=args.demand_id, owner=args.owner,
                               lease_seconds=args.lease, now=args.now)
            out = {"ok": True, "status": row.status, "lease_owner": row.lease_owner}
        except t["pd"].DemandQueueError as exc:
            out = {"ok": False, "error": f"{type(exc).__name__}: {exc}"}
    # Self-evidence for the cross-process claim (review finding 3): every
    # child reports its own pid and literal argv in its output envelope.
    out["pid"] = os.getpid()
    out["argv"] = list(sys.argv)
    sys.stdout.write(json.dumps(out, ensure_ascii=False))
    return 0


# --------------------------------------------------------------------------
# main
# --------------------------------------------------------------------------
def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--target", required=True)
    parser.add_argument("--out")
    parser.add_argument("--child", dest="child_args", nargs=argparse.REMAINDER)
    args = parser.parse_args()
    if args.child_args:
        return run_child(args.target, args.child_args)
    target = Path(args.target)
    results = []
    for case_id, fn in CASES:
        started = time.time()
        try:
            t = load_tree(target)
            measurement = fn(t) or {}
            results.append({
                "case": case_id,
                "result": "PASS",
                "measurement": measurement,
                "seconds": round(time.time() - started, 3),
            })
        except BaseException as exc:  # noqa: BLE001 - evidence collection
            results.append({
                "case": case_id,
                "result": "FAIL",
                "error": f"{type(exc).__name__}: {exc}",
                "traceback": traceback.format_exc()[-1500:],
                "seconds": round(time.time() - started, 3),
            })
    summary = {
        "target": str(target),
        "passed": sum(1 for r in results if r["result"] == "PASS"),
        "failed": sum(1 for r in results if r["result"] == "FAIL"),
        "results": results,
    }
    text = json.dumps(summary, ensure_ascii=False, indent=2)
    if args.out:
        Path(args.out).write_text(text, encoding="utf-8")
    for r in results:
        line = f"{r['case']:12s} {r['result']}"
        if r["result"] == "FAIL":
            line += f"  {r['error'][:140]}"
        print(line)
    print(f"== {summary['passed']} passed / {summary['failed']} failed  ({target})")
    return 0 if summary["failed"] == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
