"""I-03-C independent canonical serialization reference (step 1, frozen BEFORE
any implementation is touched).

Rules (card I-03-C 步骤1):
- The canonical bytes and SHA-256 for plan P0 are computed HERE with THIS
  file's own serialization code. It NEVER imports the gap_plan module under
  test and NEVER calls `_hash_gap` — the expected must not be generated by
  the function under test (禁止共享待测 hash helper).
- Serialization contract (I-03-A D6, frozen): canonical JSON with
  recursively object-key-sorted, no whitespace (`,`/`:` separators),
  ensure_ascii=False, UTF-8 encoded, SHA-256 hex.
- The implementation must reproduce these bytes; w03c_cases.py compares
  the planner's gap_hash against the SHA frozen in canonical/p0.expected.json.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

A = Path(__file__).resolve().parents[1]

POLICY_HASH_P = hashlib.sha256(b"policy-epoch:P").hexdigest()
REQUEST_ID = "req-p0"
AS_OF = "2026-07-31"
POLICY_EPOCH_NAME = "P"
URL_P0 = "https://fixture.invalid/a"
FILED_P0 = "2026-04-01"


def cjson(obj) -> str:
    """Independent canonical-JSON serializer (own code, NOT the production
    helper path). Walks the structure: dicts with sorted keys, lists in
    given order, leaf strings escaped via leaf-level json.dumps,
    ints/bools/None rendered as canonical literals."""
    if obj is None:
        return "null"
    if obj is True:
        return "true"
    if obj is False:
        return "false"
    if isinstance(obj, int):
        return str(obj)
    if isinstance(obj, str):
        return json.dumps(obj, ensure_ascii=False)
    if isinstance(obj, (list, tuple)):
        return "[" + ",".join(cjson(x) for x in obj) + "]"
    if isinstance(obj, dict):
        return (
            "{"
            + ",".join(
                json.dumps(k, ensure_ascii=False) + ":" + cjson(obj[k])
                for k in sorted(obj)
            )
            + "}"
        )
    raise TypeError(f"not canonicalizable: {type(obj)!r}")


def _qual(
    provider,
    pid,
    *,
    entity="ACME",
    market="US",
    kind="annual_report",
    ps="2024-07-01",
    pe="2025-06-30",
    fy=2025,
    filed=FILED_P0,
    accepted="",
    revision="",
    amended=False,
    url=URL_P0,
):
    return {
        "entity": entity,
        "market": market,
        "kind": kind,
        "period_start": ps,
        "period_end": pe,
        "fiscal_year": fy,
        "provider": provider,
        "id": pid,
        "filed_at": filed,
        "accepted_at": accepted,
        "revision": revision,
        "amended": amended,
        "url": url,
    }


def payload_p0() -> dict:
    acme_qual = _qual("test", "a-new")
    return {
        "hash_schema_version": 1,
        "request_id": REQUEST_ID,
        "as_of_date": AS_OF,
        "document_kind": "annual_report",
        "entity": "ACME",
        "market": "US",
        "latest_status": "newer_remote_available",
        "not_published": False,
        "provider_unavailable": False,
        "provider_reason": None,
        "no_gap": False,
        "policy_hash": POLICY_HASH_P,
        "reuse": [],
        "missing": [acme_qual],
        "newer_revision": [],
        "future": [],
        "superseded_remote": [],
        "unusable_local": [],
        "ambiguous_candidates": [],
        "conflicting_candidates": [],
        "unknown_candidates": [],
    }


def main() -> None:
    payload = payload_p0()
    blob = cjson(payload)
    # cross-check the independent serializer against stdlib canonical form
    canonical = json.dumps(
        payload, sort_keys=True, ensure_ascii=False, separators=(",", ":")
    )
    if blob != canonical:
        raise SystemExit("independent serializer != stdlib canonical form")
    canon_bytes = blob.encode("utf-8")
    sha = hashlib.sha256(canon_bytes).hexdigest()
    out = {
        "card": "I-03-C",
        "attempt": "a20260919-01",
        "frozen": True,
        "plan": "P0",
        "fields_declaration": {
            "entity": "ACME",
            "market": "US",
            "kind": "annual_report",
            "period_triple": ["annual_report", "2024-07-01", "2025-06-30"],
            "fiscal_year_label": "FY2025 (derived, period_end year)",
            "fiscal_year": 2025,
            "policy_epoch": "P",
            "policy_hash": POLICY_HASH_P,
            "provider": "test",
            "id": "a-new",
            "filed_at": FILED_P0,
            "accepted_at": "",
            "revision": "",
            "amended": False,
            "url": URL_P0,
            "as_of_date": AS_OF,
            "request_id": REQUEST_ID,
        },
        "canonical_json": blob,
        "canonical_bytes_hex": canon_bytes.hex(),
        "canonical_bytes_len": len(canon_bytes),
        "sha256": sha,
    }
    dest = A / "canonical" / "p0.expected.json"
    dest.write_text(
        json.dumps(out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(f"POLICY_HASH_P={POLICY_HASH_P}")
    print(f"canonical_bytes_len={len(canon_bytes)}")
    print(f"P0.sha256={sha}")
    print(f"written: {dest}")


if __name__ == "__main__":
    sys.exit(main())
