"""Produce changes.diff: the full delta of iso/ against its I-04-B baseline.

Header paths are POSIX-relative to the attempt root (iso/filing-fetch/...), as the
card requires, and the diff is generated by file-by-file comparison so it stays
readable and reproducible without git.
"""

from __future__ import annotations

import difflib
import hashlib
from pathlib import Path

ATTEMPT = Path(__file__).resolve().parents[1]
BASELINE = (
    ATTEMPT.parents[1] / "I-04-B" / "a20260919-01" / "iso" / "filing-fetch"
)
CURRENT = ATTEMPT / "iso" / "filing-fetch"
OUT = ATTEMPT / "changes.diff"

SKIP_DIRS = {"__pycache__", ".i04d-test-runs"}
SKIP_SUFFIX = {".pyc"}


def rel_files(root: Path) -> dict[str, Path]:
    found: dict[str, Path] = {}
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        parts = set(path.relative_to(root).parts)
        if parts & SKIP_DIRS or path.suffix in SKIP_SUFFIX:
            continue
        found[path.relative_to(root).as_posix()] = path
    return found


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    base = rel_files(BASELINE)
    cur = rel_files(CURRENT)
    lines: list[str] = []
    lines.append("# I-04-D changes.diff")
    lines.append("#")
    lines.append("# Scope: this attempt's iso/ copy against its baseline (the I-04-B accepted output).")
    lines.append("# Paths are POSIX-relative to the attempt root.")
    lines.append("# Production repos are NOT part of this delta and were not written.")
    lines.append("#")
    lines.append(
        "# baseline: execution_runs/I-04-B/a20260919-01/iso/filing-fetch/  "
        "(scripts/fetch_filing.py sha256 dc593a75cae991b1d5c54114ef22e9616c9276c070afdaabcdad758e0c13af1c)"
    )
    lines.append("# current : execution_runs/I-04-D/a20260919-01/iso/filing-fetch/")
    lines.append("")

    added = sorted(set(cur) - set(base))
    removed = sorted(set(base) - set(cur))
    modified = sorted(
        name for name in set(base) & set(cur) if sha256(base[name]) != sha256(cur[name])
    )

    lines.append(f"# added   : {len(added)}")
    for name in added:
        lines.append(f"#   iso/filing-fetch/{name}  sha256={sha256(cur[name])}")
    lines.append(f"# removed : {len(removed)}")
    for name in removed:
        lines.append(f"#   iso/filing-fetch/{name}")
    lines.append(f"# modified: {len(modified)}")
    for name in modified:
        lines.append(
            f"#   iso/filing-fetch/{name}  "
            f"{sha256(base[name])[:12]} -> {sha256(cur[name])[:12]}"
        )
    lines.append("")

    for name in modified:
        old = base[name].read_text(encoding="utf-8", errors="replace").splitlines(keepends=True)
        new = cur[name].read_text(encoding="utf-8", errors="replace").splitlines(keepends=True)
        lines.append("=" * 78)
        lines.append(f"# MODIFIED iso/filing-fetch/{name}")
        lines.append("=" * 78)
        lines.extend(
            difflib.unified_diff(
                old, new, fromfile=f"a/iso/filing-fetch/{name}", tofile=f"b/iso/filing-fetch/{name}", n=3
            )
        )
        lines.append("")

    for name in added:
        body = cur[name].read_text(encoding="utf-8", errors="replace").splitlines(keepends=True)
        lines.append("=" * 78)
        lines.append(f"# ADDED iso/filing-fetch/{name}")
        lines.append("=" * 78)
        lines.append(f"--- /dev/null\n+++ b/iso/filing-fetch/{name}\n")
        lines.append(f"@@ -0,0 +1,{len(body)} @@\n")
        lines.extend("+" + line if not line.endswith("\n") else "+" + line for line in body)
        lines.append("")

    OUT.write_text("".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")
    print(f"added={len(added)} removed={len(removed)} modified={len(modified)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
