"""CW-TEST-DEBT deliverable generator: changes.diff + binding.json + evidence summaries.

No git anywhere — python difflib only (card: 「no git」).
usage: python gen_deliverables.py <attempt-dir>
"""
from __future__ import annotations

import difflib
import hashlib
import json
import pathlib
import re
import sys
from datetime import datetime, timezone

A = pathlib.Path(sys.argv[1])
CW = pathlib.Path(r"C:\Users\郑曾波\Projects\company-wiki")
RUNS = pathlib.Path(
    r"C:\Users\郑曾波\Projects\revenue-forecast\.planning"
    r"\2026-09-19-three-project-history-audit\execution_runs")
GM_ISO = RUNS / "GUARD-MERGE" / "a20260922-01" / "iso"
CW_SRC = "src/company_wiki/source_catalog"
CW_TESTS = "tests/unit"

TARGETS = [
    ("test_readiness_graph.py",
     "71893f5d0db8ca675e05ebcda6d7feebefde7ee9a7a19350461efc0ece4708a7",
     "a5db0c9c6959d9c8cbd68d606eec0dc9368ab09f93168a2b892e3fd459f368c2"),
    ("test_prompt_injection_guard.py",
     "c05e25fb4f2e3e1c72143ee3a7c56eccf8a7bddf750efb0394984561484f9bae",
     "d3bde1a3d5ec2495474aae5b91595362b2caad4c8a0178c6927bf2d8023eec3f"),
]

PROD_BEFORE = {
    "prompt_injection_guard.py":
        "f900a13d7c22fe3bd742485c6b603de11b92a56d2414a2a046216ccd3b0b9c08",
    "prompt_injection.py":
        "7b22f23918d5e6b083a3c5272de2ed26c8a0c420b007f1268c664c0c86139618",
    "readiness_graph.py":
        "3f4c43b0049eca71fde4f7d9152b02674a26679b4470f6607383eb1820685acc",
}
ISO_PIN = {
    "prompt_injection_guard.py":
        "d71254782c10cd6d58c768eeb50e220de5e3d8047709e26f0604b5c59e67df0d",
    "prompt_injection.py":
        "88154de4ab7630606c2545cdcdf9c3ac44faf32bcae0f83f33a1cebc6d490f33",
    "readiness_graph.py":
        "50c94de28f328d125bd4834b2cda8a46794cba5f5f3f01c5415b4060b2d8c97b",
}


def sha(p: pathlib.Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def read_text(p: pathlib.Path) -> str:
    raw = p.read_bytes()
    for enc in ("utf-8-sig", "utf-16", "utf-8"):
        try:
            return raw.decode(enc)
        except UnicodeDecodeError:
            continue
    return raw.decode("utf-8", "replace")


def parse_summary(name: str) -> dict:
    """Extract the pytest summary counts + FAILED names from one raw file."""
    text = read_text(A / "evidence" / "raw" / name).replace("\r\n", "\n").replace("\r", "\n")
    m = re.findall(r"^(?:=+ )?(\d+) failed(?:, (\d+) passed)?(?:, (\d+) errors)?"
                   r"[^\n]*?(?:=+)?$", text, re.M)
    tail = re.search(r"(\d+) failed, (\d+) passed", text)
    only_pass = re.search(r"(\d+) passed", text)
    if tail:
        failed, passed = int(tail.group(1)), int(tail.group(2))
    elif only_pass:
        failed, passed = 0, int(only_pass.group(1))
    else:
        failed, passed = None, None
    names = re.findall(r"^FAILED (\S+?)(?:\s+-\s+.*)?$", text, re.M)
    return {"evidence": f"evidence/raw/{name}", "failed": failed,
            "passed": passed, "failed_tests": names}


# ---------------------------------------------------------------- changes.diff
sections = []
for name, before_pin, after_pin in TARGETS:
    before = A / "before" / name
    after = CW / CW_TESTS / name
    b_lines = before.read_text(encoding="utf-8").splitlines(keepends=True)
    a_lines = after.read_text(encoding="utf-8").splitlines(keepends=True)
    diff = list(difflib.unified_diff(
        b_lines, a_lines,
        fromfile=f"company-wiki:{CW_TESTS}/{name} (before {sha(before)})",
        tofile=f"company-wiki:{CW_TESTS}/{name} (after {sha(after)})",
        n=3))
    hunks = [line for line in diff if line.startswith("@@")]
    sections.append(
        f"==== REPO company-wiki :: {CW_TESTS}/{name} ====\n"
        "==== authority: GUARD-MERGE reviewer condition-1 (oracle.md \u00a74 edit set E1-E5) ====\n"
        f"==== before sha256: {sha(before)}  after sha256: {sha(after)} ====\n"
        + "".join(diff)
        + f"==== hunks: {len(hunks)} ====\n\n")

header = (
    "CW-TEST-DEBT/a20260922-01 \u2014 changes.diff (the two unit-test files only)\n"
    "generated by python difflib (scripts/gen_deliverables.py) \u2014 NO GIT\n"
    f"generated_utc: {datetime.now(timezone.utc).isoformat()}\n"
    "before = CW live bytes at attempt start (read-only copy-out into before/)\n"
    "after  = CW live bytes after the authorized test edits\n"
    "production sources are NOT part of this diff (they land in the same commit separately)\n\n")
(A / "changes.diff").write_text(header + "".join(sections), encoding="utf-8",
                                newline="\n")

# ---------------------------------------------------------------- evidence summaries
runs = {
    "red_unedited_on_merged": parse_summary("red_unedited_on_merged.txt"),
    "green_a_readiness": parse_summary("green_a_readiness.txt"),
    "green_b_prompt_injection_guard": parse_summary("green_b_prompt_injection_guard.txt"),
    "green_combined": parse_summary("green_combined.txt"),
    "mut1_seed_tag_removed": parse_summary("mut1_seed_tag_removed.txt"),
    "mut2_payload_removed": parse_summary("mut2_payload_removed.txt"),
    "mut_restored_confirm_green": parse_summary("mut_restored_confirm_green.txt"),
}
RED_READYNESS4 = [
    "tests/unit/test_readiness_graph.py::test_ready_source_all_stages",
    "tests/unit/test_readiness_graph.py::test_safety_guard_drives_graph",
    "tests/unit/test_readiness_graph.py::test_safety_tampered_blocks_with_action",
    "tests/unit/test_readiness_graph.py::test_safety_ignored_blocks_with_action",
]
RED_PI11 = [
    "tests/unit/test_prompt_injection_guard.py::test_record_with_binding_fields",
    "tests/unit/test_prompt_injection_guard.py::test_record_without_binding_keeps_legacy_shape",
    "tests/unit/test_prompt_injection_guard.py::test_record_bad_binding_hash_rejected",
    "tests/unit/test_prompt_injection_guard.py::test_evaluate_hit",
    "tests/unit/test_prompt_injection_guard.py::test_evaluate_ignored_when_policy_changed",
    "tests/unit/test_prompt_injection_guard.py::test_evaluate_expired",
    "tests/unit/test_prompt_injection_guard.py::test_evaluate_ttl_boundary_equality_is_still_hit",
    "tests/unit/test_prompt_injection_guard.py::test_evaluate_tampered_when_source_changed",
    "tests/unit/test_prompt_injection_guard.py::test_evaluate_absent",
    "tests/unit/test_prompt_injection_guard.py::test_evaluate_legacy_unbound_receipt_is_tampered_not_hit",
    "tests/unit/test_prompt_injection_guard.py::test_evaluate_input_validation",
]
M2_7 = [
    "tests/unit/test_prompt_injection_guard.py::test_record_with_binding_fields",
    "tests/unit/test_prompt_injection_guard.py::test_evaluate_hit",
    "tests/unit/test_prompt_injection_guard.py::test_evaluate_ignored_when_policy_changed",
    "tests/unit/test_prompt_injection_guard.py::test_evaluate_expired",
    "tests/unit/test_prompt_injection_guard.py::test_evaluate_ttl_boundary_equality_is_still_hit",
    "tests/unit/test_prompt_injection_guard.py::test_evaluate_tampered_when_source_changed",
    "tests/unit/test_prompt_injection_guard.py::test_evaluate_input_validation",
]

mutation = {
    "M1": {"what": "mirror-local deletion of the E1 line "
                   "\"state_domain\": \"review\" from _seed",
           "expected": "the same 4 readiness failures return (4 failed / 5 passed)",
           **runs["mut1_seed_tag_removed"],
           "matches_oracle": runs["mut1_seed_tag_removed"]["failed"] == 4
                             and sorted(runs["mut1_seed_tag_removed"]["failed_tests"])
                             == sorted(RED_READYNESS4)},
    "M2": {"what": "mirror-local deletion of evidence_payload=_EVIDENCE_PAYLOAD "
                   "from _write_receipt",
           "expected": "the 7 payload-dependent failures return (7 failed / 10 passed)",
           **runs["mut2_payload_removed"],
           "matches_oracle": runs["mut2_payload_removed"]["failed"] == 7
                             and sorted(runs["mut2_payload_removed"]["failed_tests"])
                             == sorted(M2_7)},
    "R": {"what": "restore mirror copies from the delivered CW files "
                  "(sha256 == after-pins), rerun both files",
          "expected": "26 passed",
          **runs["mut_restored_confirm_green"],
          "matches_oracle": runs["mut_restored_confirm_green"]["failed"] == 0},
}
(A / "evidence" / "raw" / "mutation_summary.json").write_text(
    json.dumps(mutation, ensure_ascii=False, indent=2), encoding="utf-8")

checks = {
    "red_matches_reviewer_run1": (runs["red_unedited_on_merged"]["failed"] == 15
                                  and runs["red_unedited_on_merged"]["passed"] == 11
                                  and sorted(runs["red_unedited_on_merged"]["failed_tests"])
                                  == sorted(RED_READYNESS4 + RED_PI11)),
    "green_a_9_of_9": runs["green_a_readiness"]["failed"] == 0
                      and runs["green_a_readiness"]["passed"] == 9,
    "green_b_0_failed_17_passed": runs["green_b_prompt_injection_guard"]["failed"] == 0
                                  and runs["green_b_prompt_injection_guard"]["passed"] == 17,
    "green_combined_26": runs["green_combined"]["failed"] == 0
                         and runs["green_combined"]["passed"] == 26,
    "mutations_as_oracle_pinned": all(mutation[k]["matches_oracle"] for k in ("M1", "M2", "R")),
}
(A / "evidence" / "raw" / "oracle_checks.json").write_text(
    json.dumps({"checks": checks, "runs": runs}, ensure_ascii=False, indent=2),
    encoding="utf-8")

# ---------------------------------------------------------------- close pins
close = {"production_sources_read_only": {}, "write_targets": {},
         "merged_iso_faces": {}}
for name, pin in PROD_BEFORE.items():
    live = sha(CW / CW_SRC / name)
    close["production_sources_read_only"][name] = {
        "expected_before_pin": pin, "close_live_sha256": live,
        "unchanged": live == pin}
for name, before_pin, after_pin in TARGETS:
    live = sha(CW / CW_TESTS / name)
    close["write_targets"][name] = {
        "before_sha256": before_pin, "after_sha256": after_pin,
        "close_live_sha256": live,
        "matches_after_pin": live == after_pin,
        "before_copy_sha256": sha(A / "before" / name),
        "before_copy_matches_live_before_pin": sha(A / "before" / name) == before_pin}
for name, pin in ISO_PIN.items():
    live = sha(GM_ISO / name)
    close["merged_iso_faces"][name] = {
        "pinned": pin, "live_sha256": live, "matches": live == pin}
close["git_commands_run"] = 0
close["generated_utc"] = datetime.now(timezone.utc).isoformat()
(A / "evidence" / "raw" / "live_pins_close.json").write_text(
    json.dumps(close, ensure_ascii=False, indent=2), encoding="utf-8")

# ---------------------------------------------------------------- binding.json
binding = {
    "card": "CW-TEST-DEBT",
    "attempt": "a20260922-01",
    "authority": "GUARD-MERGE reviewer_report.md \u00a78.1 condition 1 "
                 "(ACCEPT 2a26aaae): the single CW commit = 3 merged source files "
                 "+ the two measured unit-test debt fixes, via this separate pass",
    "binding_rule": "every edit binds to (a) the frozen oracle \u00a74 edit set, "
                    "(b) reviewer condition-1 wording, (c) the raw RED/GREEN/"
                    "mutation artifact, (d) a before/after pin. Nothing else changed.",
    "oracle": {"path": "oracle.md",
               "sha256": json.loads((A / "oracle_freeze.json").read_text(
                   encoding="utf-8-sig"))["oracle_sha256"]},
    "write_targets_before_after": [
        {"path": f"tests/unit/{name}",
         "before_sha256": before_pin,
         "before_copy_in_attempt": f"before/{name}",
         "before_copy_sha256": sha(A / "before" / name),
         "after_sha256": sha(CW / CW_TESTS / name),
         "before_matches_live_before_pin": sha(A / "before" / name) == before_pin,
         "after_matches_close_live": sha(CW / CW_TESTS / name) == after_pin,
         "only_product_writes_of_this_card": True}
        for name, before_pin, after_pin in TARGETS],
    "merged_faces_used_for_verification": [
        {"face": name, "path": f"execution_runs/GUARD-MERGE/a20260922-01/iso/{name}",
         "sha256": sha(GM_ISO / name), "expected": pin,
         "matches_reviewer_accept_pin": sha(GM_ISO / name) == pin}
        for name, pin in ISO_PIN.items()],
    "production_sources_read_only": [
        {"path": f"{CW_SRC}/{name}", "before_pin": pin,
         "start_live_sha256": json.loads((A / "evidence" / "raw" /
                                          "live_pins_start.json").read_text(
             encoding="utf-8-sig") if False else "{}") or None,
         "close_live_sha256": sha(CW / CW_SRC / name),
         "unchanged": sha(CW / CW_SRC / name) == pin}
        for name, pin in PROD_BEFORE.items()],
    "verification_scope": {
        "runs_against": "%TEMP%/cwtd-a20260922-01 mirror: production src copy + "
                        "the 3 merged iso faces overlaid + prod conftest.py/"
                        "pytest.ini/tests copied",
        "runs_against_unmerged_production": "NEVER — production lacks evidence_payload "
                                            "binding, state_domain and the C7 read gate, "
                                            "so the edited tests would fail there for the "
                                            "wrong reason (oracle \u00a71, decision.md \u00a74)",
        "rf_tree_written": False, "cw_tree_written_by_any_run": "only the 2 authorized test edits",
    },
    "read_only_assertions": {
        "production_source_writes": 0,
        "git_commands": 0,
        "other_cw_files_written": 0,
        "sibling_attempts_written": 0,
        "writes_outside_attempt": "%TEMP%/cwtd-a20260922-01 + pytest's %TEMP% basetemp only",
    },
    "generated_utc": datetime.now(timezone.utc).isoformat(),
}
# fill the start pins properly
start = json.loads((A / "evidence" / "raw" / "live_pins_start.json").read_text(
    encoding="utf-8-sig"))
for row in binding["production_sources_read_only"]:
    live_start = [v for k, v in start.items()
                  if k.replace("\\", "/").endswith(CW_SRC + "/" + row["path"].split("/")[-1])
                  and "company-wiki" in k]
    row["start_live_sha256"] = live_start[0] if live_start else None
    row["start_matches_before_pin"] = row["start_live_sha256"] == row["before_pin"]

(A / "binding.json").write_text(json.dumps(binding, ensure_ascii=False, indent=2),
                                encoding="utf-8")
print(json.dumps({
    "changes_diff_sha256": sha(A / "changes.diff"),
    "binding_sha256": sha(A / "binding.json"),
    "checks": checks,
    "targets": {name: {"before": before_pin, "after": sha(CW / CW_TESTS / name)}
                for name, before_pin, _ in TARGETS},
    "prod_unchanged": {k: v["unchanged"] for k, v in
                       close["production_sources_read_only"].items()},
}, ensure_ascii=False, indent=2))
