"""Human review notes after full text reading; not a completeness or PASS generator."""
import hashlib,json
from pathlib import Path
OUT=Path(__file__).resolve().parent; ROOT=OUT.parents[3]
G='assurance/runs/2026-09-02_remaining-gap-closure/'
REVIEWS={
G+'task_plan.md':('insufficient_evidence','GP001-010 are heterogeneous obligations, not ten equivalent tests. GP002 production integration remains unproved by fixture flags; GP003 owner-approved public-root configuration is legitimate. GP004 receipt structural repair and GP005 scenario counts do not prove original revenue journeys. GP006 successor makes junction checks blocking but self-hosted real-catalog CI is still separate. GP008 registration was followed by real action-argument repairs. GP009 natural counts must be separated from manual monthly runs and predictions. GP010 six accepted summaries plus one safely rejected company is not seven business goldens.'),
G+'findings.md':('supported_scoped','Records actual coverage gaps and predecessor status inflation, not just product defects. N-1 closure relies on approved successor scope and is administrative unless old consumers execute. Privacy on all public roots is explicitly an authorized configuration, not proof private-root enforcement ran. 141/192/197 green cases are narrower than real parser/LLM/consumer behavior; real traces later show section coverage can remain zero. Natural schedule and real-root gates require timestamp/version-bound evidence.'),
G+'progress.md':('insufficient_evidence','Chronology overlays multiple latest statuses: flag/CLI registration, schema fixes, missing --run-daily repair, real runs, skipped/blocked and predicted future completion. Preserve each timestamp. 62 samples with bridge disabled do not measure all production traffic. Initial monthly 7/7 is manual, first natural monthly was scheduled later; weekly reruns in the same period do not satisfy separated weekly windows. September19 cloud-directory size change demonstrates a host-sensitive digest, not the cause of every old flake. Later GP006 blocking and GP008 flags are real fixes, so original failures cannot simply be reasserted.'),
G+'ci_root_fix.md':('supported_scoped','Documents actual Windows-path/fixture-order/LF and runner-root failures missed by local tests. Explicit period/kind selection improves the fixture but still needs business assertions. Mandatory local command mapping is useful; two suites do not equal all CI quality gates. CI passing the same assertions is a separate environment check, not an independent financial oracle. Auto-install sync before tests may disseminate an unaccepted working tree and must bind installed revision to evidence.'),
G+'gp008_009_deployment_guide.md':('superseded','Registration verification does not equal execution verification. First argument correction was insufficient until --run-daily was added; later actual run logs support deployment better than inaccessible schtasks query. Unknown query is correctly treated as unknown, not success. Daily, weekly, monthly and drill need distinct natural-time evidence; manual acceptance of a report checks report mechanics only. Subsequent observed runs supersede old deployment-pending statements without satisfying every interval by prediction.'),
G+'gp_tail_closure_2026-09-08.md':('insufficient_evidence','Improves launch/junction and readiness wiring and honestly separates some pending windows. Closure based on expected September12 observation is prospective; the later September10 near-boundary run missed the full interval. Restricting deletion gate to the legacy bridge and owner-approved batch1/2 is authorization history, not universal proof of every original B-prefix obligation. Explicit rollback/maintenance/consumer-route evidence remains required. GP010 selected artifact presence does not establish semantic earnings/risk/business-driver quality.'),
G+'gp010_cohort_cutover_request.md':('supported_scoped','Owner-approved seven-company cohort is clear. Actual broad kind sweep reached752 eligible items/214 artifacts; retain that scope difference. Six successful summaries, one rejected output and three retries contradict any unqualified seven-company one-call success, but rejection is a useful safety result. Section existence is not BR01 golden correctness. SQL rollback can remove state, not undo calls, cost or disclosures. Current root deployment and consumer usable flags are separate from the proposed cutover.'),
G+'n1_r9_removal_request.md':('insufficient_evidence','Records authorized deprecation request and predecessor/successor mapping, not permission to claim semantic N-1 equivalence. Reachability limited to imports misses own CLI and frozen FC901/906 usage. Actual evidence packet is in RF, not the referenced wiki location. Later owner revocation of artifact-backfill removal supersedes the old batch3a proposal. New canonical-writer/daily callsites require a fresh current graph. Skipped-by-default R9 tests are unexecuted removal gates.'),
G+'r9_batch3_checklist.md':('superseded','Seven-object removal checklist is a planned gate. Four default skips and old import-only graph do not prove all objects removable. September10 owner revocation and subsequent new callers supersede old permission assumptions. Test-reference relocation must preserve the tested public contract and evidence hashes; declaring a caller legacy is not proving its replacement works. Natural window and rollback clauses remain distinct from source deletion.'),
G+'r9_batch3_prerequisites.md':('insufficient_evidence','Prerequisites correctly separate reachability, natural observation, owner approval and rollback, but planned dates or retagged test references do not meet them. Packet path and source versions must be verified from actual RF artifacts. Batch-level authorization cannot be substituted for availability of each retirement successor; repeat graph/current production-route analysis immediately before execution. This audit performs no deletion.'),
'assurance/unified_completion/README.md':('historical_only','Bootstrap51 tests are an old subset, not present completion. A dirty working-tree audit copied into a clean checkout does not independently reproduce the committed release; hashes/commit/install binding are required. Relaxing mtimes for portability is reasonable if content bindings remain. Later CA002/004 receipt manifests are successors, not evidence every original requirement was implemented.'),
'assurance/backup/README.md':('insufficient_evidence','Explicit placeholder for readability; no backup bytes or restore exercise is supplied by this README. Its existence must not count as a tested recovery path. ZR1001 metadata checks and later backup hashes do not establish end-to-end restored consumer behavior.'),
'docs/proposals/headwind-driver-schema.md':('supported_scoped','Proposal correctly identifies nonnegative weight/sum constraints that excluded headwinds and suggests signed weights. Schema3.6 support is an implementation result, not causal or empirical forecast validation. A positive driver may need weight above1 to offset one negative driver, and multiplying negative growth by negative weight can invert interpretation; these are model feasibility/definition questions requiring explicit regression examples, not a claimed new execution failure.'),
'docs/proposals/segment-refinement-backlog.md':('historical_only','Explicit backlog contains proposed finer cohorts and quarterly extrapolation, not claims of completed implementation. More parameters do not inherently increase accuracy. GMV times take rate or price/volume needs independent observations; calibration to reported base revenue is an identity check rather than predictive validation. Historical company figures are reviewed as method examples, not freshly verified investment facts.'),
'docs/session-checklist.md':('insufficient_evidence','Useful gates for source hashes, sensitivity levels, residual explanation and immutable versions. Fixed HK-blocked/CN-US-normal statement is dated environment evidence, not a current routing rule. Three failed calls and self-declared trust boundary do not by themselves authorize lower-provenance publication. Numerical/language lint and digits checks do not establish economic correctness. Current F11 unsigned host-mode and ZR710 output-failure registry gaps remain material to its promised publication guarantees.'),
 'docs/templates/trust-boundary.md':('supported_scoped','Template explicitly admits tool_call_id is self-declared and source authenticity unproved, a sound limitation. Hash, schema and recomputation can support reproducibility without proving empirical calibration or original disclosure truth. Compare stronger formal-mode claims with current F11 capability check: an arbitrary existing provider file yields host_signed without a signature. Do not treat the template as proof that mode is enforced or source bytes were attested.')}

REVIEWS.update({
'AUDIT_REPORT.md':('superseded','Old268-green audit correctly separates internal self-consistency from input-bound validation, distinguishes filesystem reuse from catalog-first and observes acquisition double ownership. Its P0/P1 list is not current defect proof: F01 sequencing and F02 embedded-input strong path now fixed; source horizon, rationale_support and actuals/effective-revenue have successors. Host execution proof still fails current F11 probe, publication atomicity current ZR710 probe. Model registries/coverage and unit passes do not prove forecasts accurate. invest boundary claims require current downstream evidence separately and are not recreated by a repository-local audit.'),
'FILING_FETCH_AUDIT.md':('superseded','Historical v1.0 thirteen-test report identifies explicit-identity bypass, shallow handles, schema999 acceptance, Boolean authorization, duplicate identify orchestration, per-call deadline and main-guard false test. Successor filing ledger independently tests current1.1 identity/schema/deep-byte validation and authorization rather than inheriting these old defects. Single acquisition ownership is now explicit, but scan/resolve and qualification remain end-to-end gaps. Parent filing agent has a current isolated total-deadline overrun counterexample. Historic absence ofgit/packaging is timestamp-local, not current.'),
'CHANGELOG.md':('insufficient_evidence','Each version is history, not cumulative current proof. v3.8 external owner thenv3.10 in-skill owner thenv4 removal shows repeated architecture reversal. v4.1 model and backtest improvements are97tests216subtests scoped, no out-of-sample accuracy demonstration; it correctly discloses this. v3.9 patents/capacity reserve analogy is superseded by4.1 guidance. v4 host-signing promise exceeds envfile capability proof; two-phase publication is genuinely present but registry/output transaction incomplete. Legacy schemas with pinned emitting runtimes are a justified boundary. Bottom Phase17 not-implemented3.6 is historical and must not be interpreted as current contradiction after later implementation.'),
'SKILL.md':('insufficient_evidence','Current workflow materially improves lifecycle selection, independent management benchmark, source/period/perimeter gates and calibrated-probability disclaimers. Model ledger31 and97tests216subtests support formulas, not investment usefulness or empiricalaccuracy. Source_preparation realchain stops at metadata roles and planned producerDAG; counters may be historical; qualification/bundle_usable and consumer provenance are not enforced there despite indexed-is-not-reusable statement. host_signed envfile can be arbitrary unsigned; registry precedes output commit. Opened citations, exhaustive communications, materiality and causal soundness are analyst checks not machine-understood. PowerShell example uses POSIX backslash continuation. Information freshness and source locator/page1 need actual extraction trace. Current4.1 installation remains a separate release task.'),
'review_audit/task_plan.md':('supported_scoped','Explicit completed_audit_only/superseded_execution_plan is a correct bounded status; it must not imply product completion. LaterR1/R2/R9 evidence changes old N01/N02/N04 state. Phase3 E2E truthful subprocess description is explicitly engine-singlefixture, not source pipeline. Numeric sixty-percent repair estimate is not a measurable current denominator. Historical permission to defer implementation is legitimate. Structural CodeGraph gaps and shell exit mistakes are documented evidence-quality lessons.'),
'review_audit/roadmap.md':('insufficient_evidence','R1 binding and R9 physical split have actual successors. R1.2 local editable chained hashes are tamper-evident against local accidental edits, not independent user-approval authority; reconstruction from artifacts weakens claimed external trust root. R2 separates optional signature from capability but current environment existence check leaves unsigned host_signed path. R3 AST download-name guard covers known syntax, not all possibleowners. R4 before/afterconfig hash and live skip do not prove production behavior. R5 command/count/date text is not semantic completion. R6 fixed10mutations are finite attack families not fuzzy universal protection, and promised three-repo/three-entry coverage must matchactualCI. R7 release checklist downgraded registry conflicts while structure tests still red; authorization/scope cannot be hidden by releasable label. R9 five-modelgoldens preserve behavior, including any old error, and caller existence need production nottests.'),
'review_audit/progress.md':('supported_scoped','Chronology establishes real positive fixes N01 binding, singleowner removal and3960to468line split. It also shows R2 seven/eight test-count ambiguity and no-signature-still-valid assertion, golden updates and explicit fixturehost_signed, explaining green attestation tests without actual signer invocation. R5 marked complete beforeCI wiring; R8 moved15phaseheaders to reopened so completed-only verifier passed. R7 releasable despite2intentionalred and registryconflict downgradedtoRELEASE-NOTE; laterR9 fixesstructure. R6 tenmutations found3realbugs, useful but narrow. LaterFC505 fixesv1pairing and exactZijin reuse whileStarLakeblocked, notuniversalexternalrootreuse. Branch/hash repair and Windowsbytecode mutation issues are preserved rather than silently treating allreceiptsoriginallyvalid.'),
'audit_review/README.md':('contradicted','Current authority page simultaneously says completed/current_nextCA201 and onlyCA001 maystart; latermachinepriority cannot make every humanstartupinstructiontrue. Six inseparable conditions explicitly requirecurrenttriplet,reallevels,naturaltime,thirdcompany/provider/worker; finalCA/ZRcards largely accepted narrowerhelpers andstructuralreceipts. 117stateclosure isadministrative evidence, not those sixoutcomes. §4 oldfailuresneedcurrentdelta (F01/F02fixed, F11/ZR710remain); §9 rejects skip/xfail/textIDyet accepted pathways retainthese. Original rootpolicy allroots andsuccessfulexternal reuse unmet bynegativeDropboxrun. Singlewriter/CAS areuseful, butterminaladvance missing requiredmanualCAS andCA306noticeslaterbackfill. No newexecutionauthority is drawn fromthishistoricalfile.'),
'audit_review/task_plan.md':('superseded','Audit-only closure and explicit deferred implementation are legitimate. A1 strongestinput/snapshot contract nowimplemented, A2 signer-execution andformalsensitivity guarantees are not provenbyfieldpresence. B1 CLIhardfail initially leftlibraryowner thenlaterR3 removedit. B2 versionmatrix andB3sync are scoped positive; historicalassertions aboutsameworktree/head andcache-freeinstall requirecurrentmanifest. C1 per-module90thresholdvsC2live-skipsneedsdistinctcoverage; C3 repeat50/crashcleanup cannot be certifiedbythreepasses. D1 receiptshape/hash doesnotattestuserauthorization. Current FILING ledger handlesprotocol/deadline. CodeGraphmissingedgesexplicitlynotproofnocalls, a good guardagainst false structuralclaims.'),
'assurance/runs/session-2026-08-13/findings.md':('insufficient_evidence','All43numbered findings plus terminalA/B andC-G read. Numerous genuine reviews caughttypeleaks,hasherrors,wrongcwdvacuousoracle andschema3.8capturebypass. Yet fixes moved inf protection tocommercialterms leavingminehelper; <=1accepted/nullconflict termedresolved; finite numbers termednotfakeincome; genericoperationalfraction calledaccounting; thirdmine/company structuralfixture calledreal. ZR713 mine-volume wapeNone is honest gap not completedbacktest. ZR409 Dropbox53uniquefilingsnonecapture-ready andnegativejourney is safetypositive not successfulreuse. BReadiness isshadow; canonicalconfig3loaderdeferred. CurrentFC904rolelist,counter,qualificationgapsremain. CA306 noticesabsentdespiteaccepted andterminalstate requiredmanualCAS. Claim402no-verifycommitsneedspercommitverification givenpriorprecommitruns; owner hadexplicitlyforbiddenpush so noCIuntilpush wasauthorizedscope, notdisobedience.'),
'assurance/runs/session-2026-08-13/task_plan.md':('insufficient_evidence','Read all519lines; repeated datedlateststates retained ashistory, notcurrenttaskauthority. Per-ID117ledger governscomponentjudgments. Originalnaturalsoak→13calculator tests, 3companyjourney→Zijin+helpers, R9delete→freeze/verify gate, finalsixquestions→existence/hash mapping, precedingCA305pass beforefinalCA201 CI wiring: acceptance cascade changesmeasurement level. Last22cards productzerochange validation/absorption cannotbyitself prove deployment. Explicitownerstop/localnopush instructions legitimate. Reviewerapproval and count ofcommands not independentfinancialoracle. 8/31noticebackfill and9/1 crossplatformfixes supersedesome failures butdo notretroactively make8/23 CIvalidated.'),
})

REVIEWS.update({
'IMPLEMENTATION_PLAN.md':('insufficient_evidence','All130lines read. The superseded banner correctly blocks new execution; summarycompleted vsbodypending vsR9alreadyapproved shows this is datedmirror notsinglecurrentstate. R1anchor repair andR9physicalsplit are realsuccessors; publicationJSONL is authorizedlocalrecord notindependentapprovalauthority. R2 no-signerformalreject goal stillcounterexamplethroughenvfilecapability. R5 verifiergreen afterreopenedheaders isaccurate syntaxbehavior, notoriginalobjectivesmet. R6fixedmutationfamilies, R7releasewith2structurered thenlaterR9fix all retain dates. AuthorisedlocalJSONL choice isnotdefectitself; currenttransaction/securityboundarymustexplicit.'),
'PLANNING_STATUS.md':('superseded','All84lines read. Datedtopoverlays improve recovery but retain contradictorycurrentinstructions below. P9 23:59:52 legitimatelyfails24h; predictedSeptember12pass isnotactualobservedgate. LaterAction/--run-daily fixes genuinelysupersedeoldGPfailure. Zero-shmclaimwaswithdrawn;mtimecorrelationdoesnotbyitselfidentifyprocesswriter. 62sample/legacybridgeoff/naturalrun counts qualifyobservation, notproductionallroots. R4 andworker5PLAN_ONLY planningcompletion muststaydistinctfromruntimeimplementation; ownerlaterauthorizedBso9/11not-authorizedisnotcurrentpermission.'),
'review_audit/findings.md':('supported_scoped','All184lines read. N01 oldembeddedinputanchorswap, N02 unconnectedextraction, N03libraryowner, N04structuredhostselfreport are historicalspecificcounterexamples. R1/R3/R9successorsreallyfixedanchor/singleowner/physicalsplit; currentF11existsenvfilebypasssamebroadertrustgapnotoldnocapabilityclaim. N05productionconfigdrift andN06install differences datebound, notcausedbythisaudit. N07thresholdsettoobservedbaseline,N09CIsubset,N10engineonlyE2E explainwhytrue280passcoexistsknownfailures. VerificationContextisrecomputableselfconsistency asdocumented;inputhashbindingalone cannotproveexternalfacts. Correctsnapshot/recompute/compatibilitypositives retained.'),
'docs/buy_side_model_audit_2026-09-18.md':('supported_scoped','31modelrows andlifecycle choices independentlyreviewed inmodel_ledger;97tests216subtests reproduce scopedformula/domain work. Unitnormalization/recognition/zero-base/timing/mix/perimeter/optionalothers are correctlylimited; registeredquantitydimensiondoesnotproveunits. fsumhelpsadditionnotinput/multiplicationprecision. Signedrates/negativegrowth/stockbridges materiallybroaden support; everydomainboundaryandconditionalcommerciallaunch separatedfromprobabilities. IFRSlinkedclaims arehistoricalmethodcontents, notnewlegal/financialadvice. All31 lackrealout-of-sampleaccuracyimprovement evidence; docitselfhonestlystatesnoaccuracypercentage. Lifecycleformulachoiceandconstrainedfallbackrequireactualcompanyparametersources.'),
'docs/buy_side_review_2026-09-18.md':('supported_scoped','Methodreview distinguishes drivercausality,economicstocks,managementguidancebenchmark,evidencerelevance,sensitivityandprobabilitycalibration. Expanded31models aremechanismcoverage notcompleteindustries/populations. Rollingoriginwithfrozenasof, baselines, scale-awareerrorsandcalibrationis appropriate plan; actualrealcompanyforecastdistribution hasnotbeenbacktestedhere. Conditionalqualitativeclaims/counterevidence mustmapparameters; sourceIDsandhashescanonlyverifybinding. Latestrealrun0/3shows researchengineenhancementdoesnotrepairsourcepipelineoragentworkflow automatically. Claimedsoftwaretests confirmed97+216, noimplicitaccuracyclaim.'),
'assurance/runs/2026-09-11_r4-phase-b/task_plan.md':('superseded','All108lines read. OriginalB01-B10, L01-L12/DR/VR/AR andownerS1-S13 crosscheckedagainst65R4docreviews. HeadstillB03pending/B06B07designonly whiletableimplemented andlater9/18B10complete; snapshotscannotdrivecurrentauthority. ExplicitownerconsumerC/N-1outsideB/canonicalmetadatafallback/overwriteknownlimit is legitimate scope, notoriginalgoalclosed. Oldstoprequiringauthorization supersededbylaterownerpermissions. Equalpolicyhashat4currentrootconfigonlysupportsboundedblast-radius. B08/B09pendinginoldtable supersededbyrealreadonlyrunsbutfourroot+fifthcoexistencenotdone. Complexitynewhelperspreservetablebut do not automaticallyreducewholeflowcomplexity.'),
'assurance/runs/session-2026-08-13/panorama.md':('insufficient_evidence','Full539line current-state map repeats117accepted while its detailed route exclusions preserve original gaps. Per-ID unit ledger independently qualifies every CA/ZR outcome; metadata/status/hash routing is not producer execution, three-company journeys or natural deployment. RootPolicy/readiness and legacy deletion repeatedly move to successors. Final six-question mapping uses accepted receipts as both premise and conclusion. Historical user stop/no-push boundaries are legitimate; later9/1CI does not retroactively validate8/23 acceptance.'),
'assurance/runs/session-2026-08-13/progress.md':('contradicted','Full1119lines read. Reviewers repeatedly accepted explicit minor/info gaps: CA202orTrue, CA302sameZijindata/reconcile(x,x), ZR1102tests-as-production, CA306not-deployed notices. Missing new test filename was repeatedly RED, not reproduced behavior. A53Dropbox pool had0capture-ready positives, so safeMISSING is not successfulreuse. Existing no-WAL assertion narrowed afterSQLiteauxcreation; 49GBtracemalloc is notOSRSS. Terminal closure requiredmanualCAS; noticesonlybackfilled8/31; 9/1CI ignores25files andpermitskips. These are historical acceptance-scope defects, not evidence all later fixes fail. Genuine concurrency, identity, validation andplatform corrections remain scoped positives.'),
'audit_review/2026-08-08_adversarial_plan/closure_ledger.md':('insufficient_evidence','All142lines read. Individual F/N/P/C rows retain partials and later successors; no oldresolved is inherited as currentPASS. Summary saysFonlyonepartialF034 butF015also partial. Consumer actualreuse andhostattestation closure require currentFC904/F11 probes; hash/field/selector success does not satisfy them. Dropbox negativeonly anddownloadexcluded were owner-approved scope, so legitimate narrow acceptance must remain distinct from original positivejourney. FloatingCI and28day/7day observation are explicitlyunfinished; broad enumerated-known-problems-allfixed language exceeds table.'),
'audit_review/2026-08-08_adversarial_plan/task_plan.md':('superseded','All655lines read; 74WU original ledger preserves every listedscenario/subgate. Strong originalbar requiredartifactactualuse, currenttriplet, threeCLIcrossrepo, realnatural7day andknownpartialsblockrelease; subsequentcardsnarrow many requirements. WU2Anegative-only ownerdecision is legitimate andconfig-enabled notproduction-reuse-verified distinction is excellent; noeligibleDropboxpositive remains gap. WU2B futurepolicy explicitlyseparateauthorization anddoesnotjustify retrofitaccusation. 5.4/6.2 consumerrole reads/counts and5.1SectionQuery bypass are currentcounterevidence; 95%modulecoverage/noignore originally differs later acceptedCI. This planitselfhonestlyaudit-only thenarchitectureinvestigation, notproductcompletion.'),
'task_plan.md':('insufficient_evidence','Entire2680lines reviewed using prior567checkbox/context ledger plus remaining prose. Original formalhost/nooptout, overallremainingdeadline, actualconsumerreuse andallquality gates were changed in finalstatus table: 1623explicitcompletedwithoutallsubsteps;1627/1628atomic/authorizationcalledoverengineering,1612hostoutsidephase. LaterA1 stronginput/two-phase genuinefix; laterA2onlyhost_receiptpresence is nottrustedexecution (currentF11probe). Totalcoverage/green andpartialmoduleextraction notoriginalallcontracts. Fifteen-minute inputbuild/<=2rounds are predictions requiring measurednewcompanies. Phase17truthboundarytemplate doesnotenforce draft; opted-offdigitwarningcannotproveallclaimsemantics. Fiveuncitednumberslaterrepaired to0, so donotrepeatoldfailureascurrent. Approved18.3skip andstop/nopush respected. Currentdeadline/provenance/transaction/callcount counterexamplesboundtheoriginalclaims; investmentsiblingfulltestsnotrecreatedhere.'),
})

def main():
 rows=[]
 for file,(verdict,reason) in REVIEWS.items():
  p=ROOT/file; raw=p.read_bytes()
  rows.append({'source_file':file,'read_sha256':hashlib.sha256(raw).hexdigest(),'read_lines':len(raw.decode('utf-8-sig').splitlines()),'full_text_read':True,'conclusion':verdict,'review_reason':reason,'boundary':'Document-level assessment; atomic claim ledger and source occurrence mapping are separate.'})
 (OUT/'additional_document_ledger.jsonl').write_text(''.join(json.dumps(x,ensure_ascii=False)+'\n' for x in rows),encoding='utf8')
 print(len(rows),'full-read human document assessments')
if __name__=='__main__':main()
