"""Incremental, human-authored R4 source dispositions. Read completeness != product proof."""
import hashlib,json
from pathlib import Path
OUT=Path(__file__).resolve().parent; ROOT=OUT.parents[3]
A='assurance/runs/2026-09-11_r4-phase-a/'
B='assurance/runs/2026-09-11_r4-phase-b/'
REVIEWS={
A+'task_plan.md':('superseded','A01-A04 design/help completion and G2 owner directions are not A05/A06 real corpus or B implementation. Later A06-D0 and B decisions supersede pending rows; six gate prerequisites were legitimately outstanding at that timestamp. Count/hash/help checks are historical limited evidence, not real read/forecast outcomes.'),
A+'baseline-map.md':('supported_scoped','Explicitly retracts docstring-as-call evidence, default-argument-as-spawn counting and no-DB-touch claim. Current code must be checked by symbol rather than stale line. 52 help calls prove parser surface only; listed 8 CI exclusions and production DB reads during collection explain environment divergence. Location representative choice does not itself alter content identity.'),
A+'root-contract.md':('superseded','Evolution correctly separates loader from live export, three reuse predicates, read/write/egress/quality axes, and fake configuration guarantees. Several old status/default/count statements remain alongside corrections. B01 successor aligns reuse and rejects string booleans; R1/R4 intentionally excluded from B, so old fail-open must not be copied as all-current nor B acceptance used to close privacy/symlink policy.'),
A+'operation-contract.md':('insufficient_evidence','47 leaves are mapped with flag conditions and writable-store side effects, but help is not execution and remaining R-row summary incorrectly uses subprocess empty for startup-status despite baseline startup schtasks runner. Five error labels are a design vocabulary, distinct from ResolutionStatus and consumer outcome enums; B03/B07 later document deviations. Complete OS-level side-effect proof remains absent.'),
A+'identity-contract.md':('insufficient_evidence','Document logically distinguishes exact copies/revisions and retracts append-only alias/current-version-selection claims, yet retains contradictory owner-pending and document_id logical-versus-content-addressed wording. R5 same entity+period alone is not sufficient to merge materially different reports. B04 later accepts overwrite/no-copy as an explicit limitation; old-reference availability is not universally delivered.'),
A+'owner-rulings-2026-09-11.md':('supported_scoped','Owner directions are historical authorization context; R3 was narrowed to loader after three reviews proved export live. R2 fixes actual false semantics, R4 default change is inert on four explicitly public roots. Later B scope consciously excludes R1/R4; do not call these unauthorized omissions or completed protections.'),
A+'a05-corpus-sample-plan.md':('insufficient_evidence','Independent raw-byte oracle, four-root/revision/local-import matrix is sound aspiration; same document_id with different source hashes conflicts with content-addressed identity description. Later B.AR sample of12 and isolated fifth root do not satisfy full original simultaneous four-root/revision distribution. This file alone contains no corpus execution.'),
A+'a06-baseline-plan.md':('supported_scoped','Clearly distinguishes existing tests, D0 mechanisms and R1 real traces. The list is not measured coverage; later D0 report is the appropriate successor. Binding later tests to the same cases/isolation is necessary, and no-trace gaps remain gaps.'),
A+'baseline/a06-d0-baseline.md':('supported_scoped','787 unit +1748 contract +7 skips is a historical measured subset, not all mechanisms or L01-L12 real acceptance. It correctly exposes symlink skip, coverage-gate skips and R9 skips, and collection-phase production DB opening. Repeated green therefore leaves host/security and real-root failure modes uncovered.'),
A+'boundary-audit.md':('supported_scoped','Independent observation successfully falsified zero-touch self-report and prompted WAL/SHM coverage. Later corrections distinguish historical stamps from current ambient activity. Size/mtime/no-WAL-change only give absence of observed durable writes, not universal no-write/no-open or per-process causation. External CI timestamp correlation is supporting, not OS writer attribution.'),
A+'findings.md':('supported_scoped','F-A01-1..12 record real audit improvements and repeated incorrect structural claims: docstrings, module-vs-symbol callers, real export, dormant defaults, schema and CLI surfaces. Follow-up B code supersedes selected defects; maps and corrected prose do not themselves implement those controls. Original repeated counts are historical snapshots, not current certification.'),
A+'progress.md':('supported_scoped','Chronology preserves multiple rejected reviews, truthful post-push side effects, CRLF/blob correction and empty-checklist weakness. Later A06 and owner decisions supersede pending rows. P10 natural24h is reported observation; next-day expectation is not a completed second window. No broad product completion follows from documentation/CI status.'),
A+'a08-goal-bridge.md':('supported_scoped','13 unassigned old-unit rows are routed through O06/U117/C-D, reverse set correctly deduplicates to11. Explicitly says routing does not close any ID and B cannot sign E/U117/FC903 requirements. This is a useful traceability artifact, not evidence old obligations ran.'),
A+'a08-disposition.md':('insufficient_evidence','Preserves frozen-receipt corrections and admits A-AR-04 requested reviewer-record missing; event-based closure cannot replace that missing evidence. Its summary says5 closed but enumerates6 IDs; counts are not reliable closure evidence. Historical timestamp counts should remain timestamp-scoped rather than erased as inherently unstable.'),
B+'b-design.md':('superseded','Initial hard hash gate relaxed by approved S10/S11 because four old fixtures have inconsistent bytes/hash/size; B03 later supplies a separate hard byte API, consumer wiring moved C. B04 broad completed claim conflicts with overwrite limitation; B06 preview unreachable and B07 N-1 removed. Read each final successor: accepted scoped work does not close original end-to-end requirements.'),
B+'file-scope.md':('supported_scoped','Explicit allowed/prohibited surfaces explain why writer preservation, external safety and consumer wiring were deferred. Do not infer inability from arbitrary line allowlists as a product solution. Hashes are pre-change inputs; old proposed/unapproved headings are superseded by owner approvals. New helpers can satisfy per-function complexity without reducing system complexity.'),
B+'test-acceptance-map.md':('insufficient_evidence','L01-L12 full matrix is wider than delivered B tests: metadata/byte/consumer/OS layers remain separate. It explicitly labels consumer qualification unverified and identity/sidecar trigger unreachable. Required-no-skip completion definition conflicts with reported host skips unless scoped exception remains attached. Payload same-config byte equality is weaker than policy semantic equivalence.'),
B+'risk-and-stop-rules.md':('supported_scoped','Sound negative controls and R6 metadata-observation limits. Bad hash unconditional failure in early rules is superseded by approved S10 metadata-handle exception; hard-byte refusal only at B03. No-delete/no-egress design does not prove runtime unreachability. The self-check against prose-only fixes addresses actual recurrent process failure.'),
B+'b-vr-protocol.md':('insufficient_evidence','This is a pending protocol with two isolation levels and per-case independent OS/network observations, stronger than many eventual receipts. Its L09 preview, L11 consumer and L12 second-read no-spawn goals cannot be marked completed by pure rule tests or parser help. Later B08/BAR evidence must be compared clause by clause.'),
B+'owner-scope-decisions-2026-09-12.md':('supported_scoped','Explicit user-approved scoped tradeoffs S1-S13: frozen assertions, safety work separate, consumer C, two-level isolation, no ratchet weakening, canonical-unverified fallback and overwrite limitation. They justify B boundary but do not meet removed original objectives. Simplification reduces repeated permission/review overhead; must not resurrect old approval gates after authorization.'),
B+'owner-scope-decisions-2026-09-13.md':('supported_scoped','Ten authorized decisions maintain preview unreachable and ValueError behavior, stage taxonomy/malformed work separately, and authorize daily tiering. Later9/16 supersedes real-byte/manifest pending permission. The record is authorization history, not technical proof or a reason to keep asking after later approval.'),
B+'operator-reviewer-assignment.md':('supported_scoped','Owner-confirmed separate-session assignment is evidence of review responsibility. It explicitly cannot establish distinct model/operator or authenticate every execution; original session evidence remains stronger. Do not confuse identity stamp with independent correctness.'),
B+'owner-directive-2026-09-16.md':('superseded','Continue-until-complete interpreted as activating readonly manifest and real bytes, then independently adjudicated and explicitly confirmed in successor authorization. Scope does not itself prove execution stayed within budget; BAR found102calls vs25. Preserve chronology instead of calling all subsequent reads unauthorized.'),
B+'owner-authorisation-and-my-adjudication-2026-09-16.md':('supported_scoped','User explicitly delegated adjudication; records retained overreach and selftest guard introduction. Keeping reproducible evidence does not erase102/25 and84 retries. Five selftests strengthen executor bounds but are not OS enforcement; observed metadata unchanged cannot prove absence of all writes, acknowledged in final section.'),
B+'owner-scope-decisions-2026-09-18.md':('supported_scoped','Corrects mistaken fifth-root premise: future_lake was fourth, new isolated r4_fifth_root follows its shape. Owner chose isolated registry, four-root coexistence remains unverified. R4 readonly fetch and R5 three cloud byte reads separately authorized; later blanket not-authorized statements are stale.'),
B+'r4-final-status.md':('insufficient_evidence','Specific B05/B08/B10 scoped fixes and mutations have useful evidence; B09 only limited12sample/8identity confirmations, isolated fifth root not production coexistence. Section4 records9/18 readonly end-to-end and cloud bytes done while section5 still says requirewrite/unverified. Registered/unimplemented residuals cannot be equated with original task fully achieved; normalize missing-file abort remains disclosed.'),
B+'evidence/b01-implementation.md':('supported_scoped','Real reuse-policy alignment and candidate-level filtering are useful; wrong export hash, wrong mutation attribution and empty-set escape were caught and corrected in successor disposition. Original all-production none blast-radius only applies four-root config. Six-case sidecar probe shows old RED passed for unrelated kind-gate, not identity protection.'),
B+'evidence/b01-review-disposition.md':('supported_scoped','Reviewer distinguishes actual consumer export, conflict-config semantic test, portable hash and string-bool fail-open; these are substantive fixes. Strict-xfail AssertionError narrowing still allows unrelated assertion failures, and sidecar expected behavior remains unimplemented rather than completed. E2E explicitly unverified.'),
B+'evidence/b03-plan.md':('superseded','Planned returned-buffer hash/timeout/containment functions are relevant but source-byte snapshot does not exist and consumer wiring excluded. Final implementation adds handle-version binding/cancel tail. Read path before-and-after stat is diagnostics, hash of returned bytes is integrity mechanism.'),
B+'evidence/b03-implementation.md':('supported_scoped','18 local tests plus host symlink skip support byte helper scope. Explicitly does not protect consumers reopening canonical_path; original B07 wiring promise corrected to C. Cloud flags synthetic, ACL untested, snapshot unreachable, later disposition fixes version/cancel issues. Current source/consumer verification is separately required.'),
B+'evidence/b03-review-disposition.md':('supported_scoped','Strong review caught forged expected-version binding, EOF cancellation, drive-root containment and null bool behavior; mutation survived first test then improved. Resolved-path name opening still lacks object-handle provenance and hardlink guarantees. Taxonomy debt honestly deferred, not fixed by borrowing reason names.'),
B+'evidence/b04-plan.md':('superseded','Plan correctly forbids broadening read eligibility to recover physically destroyed old bytes; write-side snapshot solution outside current step. A test recording unavailable old revision demonstrates a limitation, not satisfaction of universal stable-reference promise.'),
B+'evidence/b04-implementation.md':('supported_scoped','PDF+sidecar movement works; provider_document_id gate, not source-group filtering, explains revision-negative pass. Without provider id another revision can be reused_equivalent. Metadata handle survival is not readable bytes. Same-path overwrite no othercopy limitation explicitly approvedS12; cannot count as full originalL07.'),
B+'evidence/b06-plan.md':('superseded','Plan distinguishes three status enums and routes blocked into additive qualification so old consumers keep accepting. This preserves wire compatibility but not new permission semantics. Stale sidecar identity cannot be detected by F2-only read layer; necessary response rule is not sufficient provenance validation.'),
B+'evidence/b06-implementation.md':('superseded','Initial published_date-as-period rule wrong and later corrected. Preview only rule-level, identity/source also not reachable through real resolver; both roots equal priority fixture hides skipped metadata merge at other priorities. Additive key accepted by old client does not mean blocked prevents consumption.'),
B+'evidence/b07-plan.md':('supported_scoped','Current-only contract and same-project-root export-byte comparison are scoped positives. N-1 and consumer adapter/byte wiring excluded. Docstring absence/presence is not runtime no-fallback proof, and original zero-write test listing was later corrected as no actualL12case.'),
B+'evidence/b0607-review-disposition.md':('supported_scoped','P1 period rule fixed with real latest_as_of path; envelope gap wiring mutation now caught. Consumer ignores qualification, unavailable-store conflict_check only signals gap, preview/identity-source still rule-only. B07 canonical exception and bareValueError accepted explicitly; selected-config payload equality does not prove full semantics. These explain accepted component work with unresolved end-to-end needs.')}
REVIEWS.update({
B+'evidence/b02-implementation.md':('supported_scoped','Successor revisions genuinely repaired fallback ordering, cleanup annotation regression and cancellation. S10 deliberately retains unverified canonical when all byte checks fail because four frozen fixtures are internally inconsistent; S11 budget also falls back.30tests/mutations support final scoped selection, not universal hash eligibility. Section8 pending successor/owner text stale versus later approvals; 31/32 claim counts differ.'),
B+'evidence/b02-ci-runs.md':('supported_scoped','Run-ID/head table is stronger than remembered statuses and preserves failures and tip-only runs. Linux CI caught host-specific hash/path/symlink and gate-selfwriter faults missed by local prepush subset. Remote success executes same assertions, not independent business oracle; baseline exceptions and8ignoredfiles remain. Old payload-blocked footer superseded by B07 pure-function comparison.'),
B+'evidence/b05-plan.md':('superseded','Shared-column read-modify-write/provenance/declared-vs-derived are valid requirements. Per-file max-complexity was misinterpreted as any-new-branch prohibition; plan corrects140belongslegacyfunc. Atomic merge and source attribution need actual concurrent/write/consumer evidence beyond count/rate floors. Parent table constraint correction itself supports evidence-before-plan choices.'),
B+'evidence/b05-implementation.md':('supported_scoped','Separate extraction/additivekeys/columnmerge and laterP1 fixes preserve review receipt and fiscal filter; initial samepriority fixtures missed scan-order erasure. Rejected review discovered persistence and declaration-binding faults despite2700+pass. Current successor disposition/B01 fixes must replace oldpending; original response-level blocked and production root tests not delivered by this step.'),
B+'evidence/b05-review-disposition.md':('supported_scoped','SpecificP1/P2 repairs bind declarations to values, retain conflict candidates, accumulate attribution and correct case-sensitive classification in successorB01. Low-entropy short hashes/key names are not confidentiality, explicitly residual. Fresh coverage required; stalecoverage skip is not a passing gate. No separate rev2 perowner is legitimate but leaves evidence/next-review dependent closure.'),
B+'b08-mechanism-plan.md':('supported_scoped','Plans minimal tempcatalog and two-sided observation, prohibits synthetic-as-real. Buildschema fixture is not itself testusedcontainer unless commandsbindit. Snapshot absence ofchange cannot prove allprocessnoopen; later report narrows realcoverage. Realbyte phase separately authorizedlater.'),
B+'b08-mechanism-report.md':('supported_scoped','74tests across6files omitB03andL02/L12explicitly; not fullB08. Guard pathparentsbug caused real production-subdirectory creation, deleted ownartifact then5selftestsfixed; no evidence ofmainDBdamage. SHMunchanged evenflatbaseline means noobservedopen, not universalnoopen. LaterL2 independentjunction/adversarialtests support repairedguard.'),
B+'b08-level2-report.md':('supported_scoped','Two verified4.17MBreads againstindependenthash are positive realbyte evidence. Wrongexpectedhash is rejected beforefileopen, reader-heldfileisnotwriterTOCTOU, oneexternalrootisnotfourrootmatrix. IndependentPython audithook narrowerthanOS; exactbeforeaftermstatcannotproveallwrites. UnresolvedexternalentityandPDFsidecaras2docs are reportedproductlimits;85emptysections preventsL10.'),
B+'evidence/b-vr-b08l2-disposition.md':('supported_scoped','Independent raw replay and12path/4junction negatives support repairedtempguard and recursive snapshot. ItcorrectlydowngradesL12andwrongexpectedhashclaims anddistinguishesconfiguredintentfromDBobservations.28claims listed21+4+2=27soaggregatecountneedsrawclaimlist, nottrusted asdenominator. OS/ACL/cloud/content-replacement/consumer gaps remain explicit.')})
REVIEWS.update({
B+'b-ar-record.md':('insufficient_evidence','66 candidate documents are 0.28% of23530, but actual12sample is0.051%; sixrawhashes are0.0255%.39/19/4/4 ends with NO LOCATION, not fourth root.102calls vs25 budget retained and subsequently owner-ratified, not unauthorized forever.18artifact hashes verify byte consistency not schema/usability; sidecar and acquisition metadata are same-source,8/12 later exchange-register identity checks improve independence but do not validate PDF issuer/content. Legacy store duplicates opens writer schema path; later R4 resolve uses readonlyreader, do not conflate. Later isolated fifthroot and filing reuse supersede oldnotdone rows without delivering fullfourroot+forecast.'),
B+'evidence/b-vr-bar-disposition.md':('supported_scoped','Eight dispositions genuinely improve sample denominator, same-source identity qualification, original85calls/66docs distinction and mechanical manifest bounds. Owner ratification later supersedes pendingauthorization; absent fourth-root bytes/fullforecast cannot be closed by limitedacceptance. MainDBstat proof remains scoped; 0/66sections limitsL10.'),
B+'evidence/b-ar-cross-repo-reuse.md':('supported_scoped','Real filing-fetch→wiki Alibaba reuse and FY2019/unknownidentity negatives are useful recorded execution, not revenue forecast or downloadpath. Current filing_contracts validate_handle does read_bytes+SHA/size and policy containment; RF build_revenue_source_record separatelyhashes. Qualification/bundleusability are not consumed there. LLM/parser counts explicitlyhistoricaljournal, downloadsinitialized0 not live instrumentation.11invariants include a descriptivecompanies_digest_scope field, not11independentassertions. Root3/4movement and readonly reader correctly supersede earlierstore-touch claim.'),
B+'evidence/b-ar-dropbox-bytes.md':('supported_scoped','Three543/567/567B sidecars hash correctly, not three financialreportPDFs. Cloudmetadata instruments are materiallybetter than Pythonstat, but already-local tinyfiles do not test actualhydration/coldPDFpartialresident conditions.0.28% repeats candidate-pool denominator, not actualsample. SamecatalogSHA/documentid are oneprovenance,exchangeidentity does not independently corroborate PDFcontenthash. No current investment facts inferred.'),
B+'evidence/b-ar-fifth-root-isolated.md':('supported_scoped','One newconfiguredroot with2tiny59B fixtures proves scannerregistration/APIresolve/read in isolation; fourstandins neverenterroots table, so nofive-rootcoexistence or actualfiling/revenueconsumer. Fiveharnessmutations support listednegativecontrols only. deny-byte bypass shown here was subsequently repairedbarfix/BA1, not currentbug.39/19/4/4 repeatedfourrootsclaim false:last4lacklocation; oldR4/R5pending superseded.'),
B+'evidence/b-vr-r3-disposition.md':('supported_scoped','Review correctly narrows denydecisions vsbyteentry, capturesunknown-IDmixedbranch, falsehardcodedisolationflag and missingactualledger edits. Laterbarfixclosesbytepolicygap. Scope isisolatedconfigplusAPI, notfullproductioncoexistence. Capturedsnapshot variesupdated_at legitimately; notallhashvariationisdefect.'),
B+'evidence/b-vr-r4-disposition.md':('supported_scoped','Eight realcorrections: readonlyreader vswriterstore, initializeddownload0/vacuouskey, inertpauseflag, wrongrunwindow/head,untrackedrewrites,pycache,shallowfiledigest. Repeatedsame4stdout andrawhash supportboundedfilingreuse. Nooperatingsystemcalltraceorformalforecast/downloadproof; addingliteraldescriptivefield doesnotcreate11independentinvariants.'),
B+'evidence/b-vr-r5-disposition.md':('supported_scoped','Five corrections expose genuineinstrument/recordfaults andalready-localcloudsidecars. Allocation4096 andtinyEOF543/567 supportthesefiles; universalallocation>0 meansfullyresident maynotgeneralizepartialcloudPDF. Doesnotprovehydrationbehavior orcorrectreportclassification. Currentdeclared-adapter scannerfixdoesnotretroactivelymigrate oldcatalogsidecarrows.'),
B+'packages/b05-read-side-malformed-columns.md':('superseded','Good explicitstate/no-crashrequirements, butfirst28passand4mutationsmissedSQLfiscalfilter,deepnest,sqliteUTF8,andotherreaders. Existingtestprotectedfail-open; successorchangesdirectioncorrectly. InitialNOTjson_valid includeinvalidrowsfix causedlimitshadowing andwasrevertedinsecondreview. B10/barfixlaterfixlistedreaders; exactfield/pathqualificationconsumer remainsseparate.'),
B+'evidence/b-vr-b05malformed-disposition.md':('supported_scoped','Independentreview detectedP0SQLbeforePython,deepnestdriverlayer,wrongdocumentvsartifactscope,missinglogs. Secondreviewcaughtnewinvalid-rowlimitshadowing; revisedSQLexcludesunprovableperiodmatches. SummarizerfixtureJOINempty madeguardvacuous untilartifact/locationseed.15mutations+57tests supportlistedshapes, notallmalformedfutureinputs; laterB10successorsmustreplaceoldresiduals.'),
B+'packages/fc1301-taxonomy-coverage.md':('superseded','InitialreasonAST+versionbumpgoalnarrowedafterN-1unitpin; zerocrossrepoimports doesnotmeanzeroconstraint. Proposed33positionalinventorymissed17 throughsame-namefirstdefinitionbug sharedbygateandinventory. Successor114codes49siteshascounterexampleandidentitycheck. Historicalnotstartedheadersarenotcurrentstatus.'),
B+'evidence/b-vr-fc1301-disposition.md':('supported_scoped','IndependentP0counterexamplerevealscorrelatedoracle:firstdefinition signaturemisbind inbothgate/evidencetool. Newall-definitionmatching+same-copyregistryidentity materiallyimprovesguard; names/signatures alone stillsyntacticclassificationnotfullruntimecode-flowcoverage. Stageassignmentmattersbecausewrongstage drops events. Version1.1retainedbyexplicitN-1pin andtwoCIsuitesrequired; failedoldbumpnotcurrentbug.'),
B+'packages/b10-plan.md':('superseded','Startswithbyte-return-chainbutexecutionmainlymetadataJSONparserunification; consumerwiringexplicitlyexcluded. Claimsbundle neveropensfiles/catchequivalence werefalsifiedlater. All-knownparserregistration canreduce duplication withoutfulfillingstablebytesorqualification end-to-end. Stoponbehaviorchange notliterallyfollowedwhereapprovedrobustnesschangesgiveunreadableflags; recordscopeauthorizations, donotmislabelintentionalfixesregressions.'),
B+'packages/b10-recon.md':('superseded','21parsepoints/10confirmed initialsyntacticinventorynotcomplete; parametersrenamed/helper/methodscope/tableambiguity causedmiss/falsepositive. B10successoraddedhandoffcountsandannotations; sectionqueryexceptionremainsnotverifiedartifactqualification (independentwiki_legacyprobe). No-callerclaimmustbeexactfunction+commit; bundletransitivelyreadsartifactbytes.'),
B+'evidence/b10-implementation.md':('supported_scoped','Genuinesuccessivefixesbutmajororaclelessons:Protocolstubselectedinsteadofimplementation, inventedheuristicsymbols,nonrecursivegate, parse-by-helperandwithin-scopebypass,syntaxerrorcountedasmutationkill, fakeinside-tryclaimprotectedbytest,identityemptyfixturevacuous,metadata_sibling/manifestexceptionsmissed. Finalknownparse sitesunifiedorregistered,12mutationsscoped. Current9/19barfixsupersedesoldmissingfile/scriptsresidual; intermediaryvariable/alternativeparsergateblindnessstilldocumented. Endsection contradictsreviewdone vs onlyreviewpending; latestauthoritativeversionneeded.'),
B+'evidence/barfix-product-fixes.md':('supported_scoped','9/19successoraddssecondfetchallandtransactioninjection (firstprobehadtestedotheringestsite),17mutationsselfcheckduplicateID/ambiguousanchor/no-op. Earlier8/8wasnotreproducible; BA1subsequentlycorrected. Bytepolicynestedrootfixedviahandlelocationroot,adapterdispatchfixedforDECLAREDadapters; actualproductionno-adapterroots stillfailunder shadow (independentwikiagent). Additivebundle_usabledoesnotforceconsumerreject. Source changedfrom66inventorylines duringaudit; readversionhashpreserved, cannotapplyoldcurrentclaims.'),
B+'evidence/b-vr-ba1-disposition.md':('supported_scoped','ReviewfoundstalemutationanchorandNameErrorkill,owning-pathvsroot_id mismatch,unimplementedadapterabort,unanchoredcoverage,partialsiblings,stale buildtree.15mutationslater17 fixesreported, nofreshwholeproductionrunhere. CoverageSHAwithoutretainedfilewasstillunreproducibleuntil9/19dualanchor+filecapture. Remainingrootconfig/consumer/readbackgapsnotclosedbythisscope.'),
B+'findings.md':('supported_scoped','Fullchronologyreadincluding9/19successors. Repeatedclaimed-done-but-not-edited,greenwrongpredicate,scopeallowlistchanges,fixturepins,incompleteparameter/consumerwiring,testharnessblindspots,concurrentresources/coverageoverwrites androllingrecordcounts explainfailure. Historicalclosedcontrols realbutlimited. Keynewproblem: L-ID completeness justinsertedfromtableintotestdocstrings, sozeroIDgapdoesnotmeasurebehavior.9/19newlyretainedcoverageanchor fixespriorlostfile; clouddirectorysizewatch supportscurrenthostoracleissue butcannotprovecauseofunloggedpastfailures. BARsampleroot/denominatorerrorsremain.'),
B+'progress.md':('supported_scoped','Entirechronologyread. Technicalsuccessesandfailedreviews retained, butpasttense green/checkpoint oftenprecededindependentreview; still-finalfooter saysreviewunpassed despiteacceptedr4, and initialno-provenance/bytes-hardgatepromises superseded.9/19newfetchall/transactiontests improvepreviousmisattributedcoverage; coverageartifactnowretained. TwoCIteststeps still omittedcoveragegatestep andignoredrealrootfile, so localtwo-stepgreenwasnotCIequivalence.8/8→15/15→17/17mutationcounts need version/filebinding. Temporalstatusandownerapproval notpresent-statecertification.'),
})
def main():
 rows=[]
 for source,(verdict,reason) in REVIEWS.items():
  p=ROOT/source
  rows.append({'review_id':'RF-R4-DOC-'+str(len(rows)+1).zfill(3),'source_file':source,'start_line':1,'end_line':len(p.read_text(encoding='utf-8-sig').splitlines()),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'full_text_read':True,'conclusion':verdict,'reason':reason,'evidence_scope':'Independent comparison of original design, explicit owner scope and implementation/reviewer successor records; not a new execution or blanket certification of historical command output.','current_technical_proof':'See unit/deep-clause/current-probe ledgers where applicable; historical execution count or unsupported current invariants remain insufficient_evidence.'})
 (OUT/'r4_document_ledger.jsonl').write_text('\n'.join(json.dumps(x,ensure_ascii=False) for x in rows)+'\n',encoding='utf8')
 print('R4 full-text document dispositions:',len(rows))
if __name__=='__main__':main()
