"""Multi-root source catalog, normalization, summary, and index API."""

from .config import CatalogConfigError, load_catalog_config
from .models import (
    CATALOG_SCHEMA_VERSION,
    CatalogConfig,
    NORMALIZER_VERSION,
    ProcessingReport,
    ROOT_KINDS,
    RootSpec,
    SCANNER_VERSION,
    SUMMARIZER_VERSION,
    ScanReport,
    SECTION_EXTRACTOR_VERSION,
)
from .service import SourceCatalog
from .resolver import (
    ResolutionResult,
    ResolutionStatus,
    SOURCE_RESOLVER_SCHEMA_VERSION,
    SourceHandle,
    SourceRequest,
    SourceResolutionError,
    SourceResolver,
)
from .lock import CatalogOperationLockedError
from .llm_summarizer import LLMSummaryError
from .acquisition import (
    ACQUISITION_SCHEMA_VERSION,
    AcquisitionCoordinator,
    AcquisitionError,
    AcquisitionResult,
    AcquisitionStatus,
    AdapterRegistry,
    DownloadAdapter,
    DownloadCandidate,
    DownloadReceipt,
    MarketRoutingError,
)
from .canonical_writer import (
    CANONICAL_IMPORT_SCHEMA_VERSION,
    CanonicalImportError,
    CanonicalImportResult,
    CanonicalImportStatus,
    CanonicalSourceWriter,
)
from .acquisition_journal import (
    ACQUISITION_JOURNAL_SCHEMA_VERSION,
    ACQUISITION_OUTCOMES,
    AcquisitionAttempt,
    AcquisitionJournal,
)
from .acquisition_service import (
    SOURCE_ENSURE_SCHEMA_VERSION,
    SourceAcquisitionService,
    SourceEnsureResult,
    SourceEnsureStatus,
)
from .adapter_process import AdapterProcessError, JsonCommandAdapter
from .acquisition_config import (
    AcquisitionConfig,
    AcquisitionConfigError,
    AdapterCommandSpec,
    load_acquisition_config,
)
from .duplicate_cleanup import (
    DUPLICATE_CLEANUP_SCHEMA_VERSION,
    DuplicateCleanupError,
    DuplicateCleanupJournal,
    DuplicateCleanupService,
    recycle_to_windows_bin,
)
from .focus_cleanup import (
    FOCUS_CLEANUP_SCHEMA_VERSION,
    FocusScopeCleanupService,
)
from .evidence_query import (
    EVIDENCE_QUERY_SCHEMA_VERSION,
    MAX_EVIDENCE_QUERY_LIMIT,
    EvidenceLocationRef,
    EvidenceQueryError,
    EvidenceQueryInputError,
    EvidenceQueryIntegrityError,
    EvidenceQueryNotFoundError,
    EvidenceQueryPage,
    EvidenceQueryResult,
    EvidenceQueryService,
    EvidenceQueryUnavailableError,
)
from .extraction_quality import (
    EXTRACTION_QUALITY_SCHEMA_VERSION,
    MAX_QUALITY_LOCATOR_REFERENCES,
    ExtractionLocatorReference,
    ExtractionQualityAmbiguousError,
    ExtractionQualityError,
    ExtractionQualityInputError,
    ExtractionQualityIntegrityError,
    ExtractionQualityNotFoundError,
    ExtractionQualityReport,
    ExtractionQualityService,
    ExtractionQualityState,
    ExtractionQualityUnavailableError,
)
from .section_extractor import SectionSlice
from .scheduler_policy import (
    SOURCE_ONLY_SCHEDULER_POLICY_SCHEMA_VERSION,
    SourceOnlySchedulerPolicy,
    SourceOnlySchedulerPolicyError,
    SourceOnlyStage,
    SourceOnlyStageContract,
)
from .dayu_cli_adapter import DayuCliAdapterError, DayuCliDownloadAdapter
from .security_identity import (
    CNINFO_STOCK_URL,
    HKEX_ACTIVE_STOCK_URL,
    HKEX_INACTIVE_STOCK_URL,
    HKEX_SECURITIES_URL,
    HKEX_STANDARD_TRANSFER_URL,
    NASDAQ_LISTED_URL,
    NASDAQ_OTHER_LISTED_URL,
    SEC_TICKER_URL,
    IdentityCandidate,
    IdentityResult,
    IdentityStatus,
    OfficialSecurityMasterRefresher,
    SecurityIdentityError,
    SecurityIdentityResolutionError,
    SecurityIdentityResolver,
    SecurityMaster,
    SecurityMasterStore,
    SecurityMasterUnavailableError,
    SecurityRecord,
    load_identity_master,
)


__all__ = [
    "ACQUISITION_SCHEMA_VERSION",
    "ACQUISITION_JOURNAL_SCHEMA_VERSION",
    "ACQUISITION_OUTCOMES",
    "AcquisitionCoordinator",
    "AcquisitionConfig",
    "AcquisitionConfigError",
    "AcquisitionError",
    "AcquisitionResult",
    "AcquisitionStatus",
    "AcquisitionAttempt",
    "AcquisitionJournal",
    "AdapterRegistry",
    "AdapterCommandSpec",
    "AdapterProcessError",
    "CANONICAL_IMPORT_SCHEMA_VERSION",
    "CATALOG_SCHEMA_VERSION",
    "CatalogConfig",
    "CatalogConfigError",
    "CatalogOperationLockedError",
    "CanonicalImportError",
    "CanonicalImportResult",
    "CanonicalImportStatus",
    "CanonicalSourceWriter",
    "CNINFO_STOCK_URL",
    "DownloadAdapter",
    "DownloadCandidate",
    "DownloadReceipt",
    "DayuCliAdapterError",
    "DayuCliDownloadAdapter",
    "DUPLICATE_CLEANUP_SCHEMA_VERSION",
    "DuplicateCleanupError",
    "DuplicateCleanupJournal",
    "DuplicateCleanupService",
    "FOCUS_CLEANUP_SCHEMA_VERSION",
    "FocusScopeCleanupService",
    "EVIDENCE_QUERY_SCHEMA_VERSION",
    "EXTRACTION_QUALITY_SCHEMA_VERSION",
    "EvidenceLocationRef",
    "EvidenceQueryError",
    "EvidenceQueryInputError",
    "EvidenceQueryIntegrityError",
    "EvidenceQueryNotFoundError",
    "EvidenceQueryPage",
    "EvidenceQueryResult",
    "EvidenceQueryService",
    "EvidenceQueryUnavailableError",
    "ExtractionLocatorReference",
    "ExtractionQualityAmbiguousError",
    "ExtractionQualityError",
    "ExtractionQualityInputError",
    "ExtractionQualityIntegrityError",
    "ExtractionQualityNotFoundError",
    "ExtractionQualityReport",
    "ExtractionQualityService",
    "ExtractionQualityState",
    "ExtractionQualityUnavailableError",
    "LLMSummaryError",
    "HKEX_ACTIVE_STOCK_URL",
    "HKEX_INACTIVE_STOCK_URL",
    "HKEX_SECURITIES_URL",
    "HKEX_STANDARD_TRANSFER_URL",
    "IdentityCandidate",
    "IdentityResult",
    "IdentityStatus",
    "JsonCommandAdapter",
    "MarketRoutingError",
    "MAX_EVIDENCE_QUERY_LIMIT",
    "MAX_QUALITY_LOCATOR_REFERENCES",
    "NORMALIZER_VERSION",
    "NASDAQ_LISTED_URL",
    "NASDAQ_OTHER_LISTED_URL",
    "OfficialSecurityMasterRefresher",
    "ProcessingReport",
    "ResolutionResult",
    "ResolutionStatus",
    "ROOT_KINDS",
    "RootSpec",
    "SCANNER_VERSION",
    "SEC_TICKER_URL",
    "SOURCE_RESOLVER_SCHEMA_VERSION",
    "SOURCE_ONLY_SCHEDULER_POLICY_SCHEMA_VERSION",
    "SOURCE_ENSURE_SCHEMA_VERSION",
    "SUMMARIZER_VERSION",
    "ScanReport",
    "SECTION_EXTRACTOR_VERSION",
    "SectionSlice",
    "SourceCatalog",
    "SourceOnlySchedulerPolicy",
    "SourceOnlySchedulerPolicyError",
    "SourceOnlyStage",
    "SourceOnlyStageContract",
    "SourceAcquisitionService",
    "SourceEnsureResult",
    "SourceEnsureStatus",
    "SourceHandle",
    "SourceRequest",
    "SourceResolutionError",
    "SourceResolver",
    "SecurityIdentityError",
    "SecurityIdentityResolutionError",
    "SecurityIdentityResolver",
    "SecurityMaster",
    "SecurityMasterStore",
    "SecurityMasterUnavailableError",
    "SecurityRecord",
    "load_catalog_config",
    "load_acquisition_config",
    "load_identity_master",
    "recycle_to_windows_bin",
]
