"""Format reviewer-authored dispositions after complete engineering-text reading.

No keyword classifier, test execution, or inferred PASS. Each tuple is an
independently authored obligation or bounded family of examples in the text.
"""
from pathlib import Path
import json, hashlib
H=Path(__file__).resolve().parent
W=Path('C:/Users/郑曾波/Projects/company-wiki')
rows=[json.loads(s) for s in (H/'item_ledger.jsonl').read_text(encoding='utf-8').splitlines() if s.strip()]
rows=[r for r in rows if not r['id'].startswith('WIKI-CTX-')]
new=[]
def add(path, line, promise, verdict, assessment, recommendation='保留原范围；实施/运行通过须由实际入口、配置和独立输出证据另行证明。', severity=None):
    p=W/path; lines=p.read_text(encoding='utf-8').splitlines()
    assert 1<=line<=len(lines),(path,line)
    r={'id':f'WIKI-CTX-{len(new)+1:03d}','original':{'repo':'company-wiki','path':path,'line':line},'promise':promise,
       'historical_status':'工程指南/设计或历史结果，按原文状态判定；不把设计措辞提升为已运行',
       'historical_evidence':{'source_line':lines[line-1],'sha256':hashlib.sha256(p.read_bytes()).hexdigest()},
       'current_independent_evidence':assessment,'verdict':verdict,'recommendation':recommendation,
       'scope':'engineering context: manually read prose; current static corroboration where explicitly named',
       'assessment_limit':'未执行文档内命令、未重跑历史外部服务、未验证业务正文事实；supported_scoped 仅代表所述限定命题。'}
    if severity:r['severity']=severity
    new.append(r)
def group(path, data, default='superseded'):
    for x in data:
        line,promise,assessment,*rest=x
        add(path,line,promise,rest[0] if rest else default,assessment)

# Current ADR scope is the authority for interpreting the old research system.
boundary='现行 docs/adr/README.md:3–19 与 contracts/legacy-caller-reachability-v1.md:34–55 已将研究、估值、Wiki writer 退役/移交；本历史接口不能据 accepted 或示例命令恢复生产许可。'
group('docs/adr/README.md',[
 (3,'ADR accepted 是历史接受状态，适用范围由现行 source-only note 收窄', '原文明确区分历史 accepted 与投资判断；是可用的范围约束，而非所有入口已受控的运行证明。','supported_scoped'),
 (7,'canonical 仅 raw/manifest/span/quality/index/projection，只读 export 不跨仓写入','原文边界一致；当前 SourceExportBundle.build:200–248 重验 merged manifests，不能推出下游全部消费。','supported_scoped'),
 (9,'投资命题、Question/Claim、估值/SOTP/正式报告移交下游',boundary,'supported_scoped'),
 (15,'ADR001 至 ADR006 按表收窄，不继承旧研究语义',boundary,'supported_scoped'),
 (23,'新 ADR 声明 schema/兼容性影响；恢复旧 writer 需新 owner 决策','文档条款明确；本轮未做恢复授权，旧执行计划不是授权。','supported_scoped')])
group('docs/adr/ADR-001-knowledge-compiler.md',[(8,'四层 knowledge compiler 与可重建派生视图',boundary),(18,'clean clone 可重建所有派生视图','未提供本轮 clean-clone 重建；原研究视图已退役，来源视图需独立重建验证。','insufficient_evidence')])
group('docs/adr/ADR-002-canonical-ingest-service.md',[(8,'Canonical IngestService 作为唯一摄取入口','唯一 owner 是设计约束；legacy reachability 列多种受控兼容入口，图结构不是全部实际安装/调用证明。','supported_scoped'),(14,'CodeGraph 验证无旁路 ingest','图覆盖当前索引符号，不能单独涵盖动态 subprocess、已安装旧副本、外部 scheduler。','insufficient_evidence')])
group('docs/adr/ADR-003-execution-semantics.md',[(8,'至少一次执行，source_id+pipeline_version+claim_id 幂等效果',boundary+' source-only note:17 已改为 source/parser/export effect；不承诺分布式 exactly-once。'),(14,'side effect 有恢复/幂等约束','是合理设计要求；本轮新下载原件存在但注册失败，不能把文件原子写等同端到端幂等已闭合。','insufficient_evidence')])
group('docs/adr/ADR-004-domain-model.md',[(8,'Company/Sector/Theme、SourceRecord/EvidenceSpan 及研究对象','来源路由元数据可以保留；Question/Claim/KnowledgePatch 研究语义明确移交。'),(21,'schema 版本和迁移防止隐式破坏','契约要求可接受，但历史 accepted 不证明当前生产 schema/profile/root 一起迁移。','supported_scoped')])
group('docs/adr/ADR-005-single-writer.md',[(8,'只有 WikiRepository 写正式 Wiki',boundary),(14,'LLM 不能直接写 Wiki','现行责任边界更严格为研究 writer 冻结；本条不应被用作允许通过 Repository 恢复研究写入。')])
group('docs/adr/ADR-006-proposal-evolution.md',[(8,'提议、评估、接受/拒绝分离，重要变更人工审查',boundary+' 仅 collector/parser/schema/source entity 变更仍可采用此模式。'),(18,'author/evaluator 分离及高风险审核','职责分离本身不能保证 oracle 独立；当前 freeze review 明确只审结构/hash，不能替代研究或产品验收。','supported_scoped')])
group('docs/adr/ADR-007-portfolio-promotion.md',[(8,'已索引 portfolio 却被 resolver root kind 排除','历史受限复用问题及 3591/相关测试是当时记录，不宣称当前继续完全相同。','historical_only'),(14,'Strategy A 手工提升到 company_raw 后复用','后继 ADR008 明确舍弃手工提升主路径；不能用于现行新增重复副本。'),(29,'提升一次永久可复用','永久表述超出 hash/location/identity/政策/as-of 的有效期；后继改直接跨根复用。'),(30,'回滚删除 canonical 副本及 sidecar 后 rescan','历史回滚命令与现行 immutable raw/本轮只读边界不同；没有执行。'),(32,'8 tests +39 tests、金山云7份财报零下载复用','范围为当时特定样本和配置；不覆盖本次3家 external-only、新下载注册或当前生产 root 组合。','historical_only')])
group('docs/adr/ADR-008-portfolio-auto-promotion.md',[(8,'手动提升 orphan 命令/锁/无人调用问题','原文诊断解释为什么方法存在而默认路径无效；后继读者不能只引用功能存在。','historical_only'),(13,'只添目录配置即复用，零新增代码','只适用已支持 adapter/profile；生产三个根缺 adapter 且 v2_shadow 开启，doctor 硬编码根名，见 WIKI-GP002 与 readonly_diagnostics。','contradicted'),(22,'company-wiki 与 filing-fetch 两份白名单共同放行','后继 ADR010 ownership 指定 company-wiki 单一 root/policy owner；旧双列表易漂移。'),(25,'有效文件+capture 元数据后直接复用','文件存在不是完整资格；本设计后文 hash 守门属必要补充，实际 FF selector/qualification 需联测。','supported_scoped'),(31,'同字节 hash 检查保护 immutable 复用','合理限定设计；不将一项 hash 验证扩为完整 as-of/identity/review 正确。','supported_scoped'),(40,'安踏 FY2023 portfolio 实测复用通过','是当时单个具备资格的外部根样本，不证明3家公司所有根或未索引文档分支。','historical_only')])
group('docs/adr/ADR-009-catalog-space-governance.md',[(3,'Phase1–2 已完成，2.2/3/4 后续','原文诚实区分已做逻辑治理与未来物理清理；不因后续未做把整份判实现失败。','historical_only'),(9,'D1 retire，D2表治理，D3news未来策略，D4不迁D盘，D5延迟物理清理','保留各项阶段；D盘迁移取消不可因旧空框复活。','supported_scoped'),(23,'9499 stubs retire，77误退删除，mismatch0','历史执行数与范围；本轮不重演删除，也无一致历史snapshot可重新计数。','historical_only'),(24,'25708956 evidence rows归档约4.6GB','历史归档记录不是当前每条待删记录有完好归档的证明。','historical_only'),(37,'删除前必须可靠归档，绝无无保护删除','当前 prune_retired_evidence.py:59 后依据最早归档日期决定全体 retired spans；root 隔离反例已证可跨集合，不符合此全称保证。','contradicted')])
group('docs/adr/ADR-010-fcap-contract-ownership.md',[(3,'Proposed ownership ADR 不等于产品实现','原文状态明确；不得把 Proposed 故意写成一次失败产品验收。','supported_scoped'),(15,'company-wiki 拥有 raw identity/root/GapPlan，filing只执行，revenue只消费','职责划分一致；实现仍需实入口确认。','supported_scoped'),(27,'单一rootpolicy，filing只保存policyhash不另造allowlist','与旧ADR008/OPERATIONS双白名单不同，应指向现行唯一规则；不靠重复文档数量自证。','supported_scoped'),(34,'registry/测试检查重复owner与schema影子','清单测试不能发现藏在运行代码里的第二策略；应增加有效决策差异测试。','supported_scoped'),(39,'本ADR只定义归属，不声称接线已完成','是明确且应保留的限制；避免由 ownership accepted 推整体已实现。','supported_scoped')])

# Source contracts: meaningful bounded design clauses, not blanket runtime acceptance.
group('docs/contracts/source-manifest-v1.md',[(3,'1.0 manifest 用 bytes SHA 和source URN作身份','CodeGraph SourceManifest 与当前 source_manifest.py 校验hash/URN；只证明字节身份，不证明真实财期/发行人。','supported_scoped'),(10,'相同bytes不同路径同sourceid，metadata/path规范化','多location不是多份新原件；需要外部root的实际资格，不能文件名等价代替。','supported_scoped'),(15,'root内相对路径、普通文件及大小/hash校验','当前 SourceExportBundle.build:232–236 调 verify_file；未运行所有 symlink/TOCTOU 攻击矩阵。','supported_scoped'),(21,'verified immutable 状态仅字节和metadata','原文32明确不是投资结论；与capture-ready/usable/review多状态应分层。','supported_scoped'),(32,'manifest不含公司投资判断','边界符合ADR scope；现有准确性不能从manifest通过推导。','supported_scoped')])
group('docs/contracts/evidence-span-v1.md',[(10,'spanID由source/locator/output决定','parser升级输出相同可同ID；这不是遗漏parserversion的自动缺陷，版本元数据仍须保留。','supported_scoped'),(15,'NFC/严格JSON/locator坐标有效','结构合同有助追溯，不能证明抽取表格/金额语义正确。','supported_scoped'),(29,'不同locator或text得到不同span identity','契约确保结构区分；真实PDF定位准确性另需逐页证据。','supported_scoped'),(42,'parser升级与稳定ID规则','版本与内容身份分开是明确设计，不能因同ID猜测缓存已错误复用。','supported_scoped'),(46,'partial/noisy/failed及qualityflags阻断误用','应与具体消费者连线；仅旗标存在不证明consumer拒绝。','supported_scoped'),(51,'homepage_identity_contradiction 质量旗标','root snapshot_mapping中唯一实质不同文本；旧snapshot不能继承此新增条件覆盖。','supported_scoped')])
group('docs/contracts/source-export-v1.md',[(3,'canonical source/evidence stdout export','只读上游契约，不负责投资模型/估值。','supported_scoped'),(23,'失败exit2、stderr且无canonical stdout','这是CLI责任；调用方先建重定向文件仍可能留下空/部分文件，OPERATIONS72已要求tmp再rename。','supported_scoped'),(35,'排序与无runtime字段保证确定性输出','需要确定输入与版本；不应把deterministic输出当实际原始资料质量证明。','supported_scoped'),(42,'add-only merge，冲突/孤儿拒绝','当前 SourceExportBundle.build:218–230 merge+relationships；静态支持限定义务。','supported_scoped'),(53,'base合并也重新verify所有raw','当前 SourceExportBundle.build:232–236循环 merged manifests，支持不是仅验证新增部分。','supported_scoped')])
group('docs/contracts/source-contract-compatibility-v1.md',[(3,'三contract版本协商整体一致','manifest/span/export组合而非任意三版本拼接。','supported_scoped'),(15,'仅稳定exact semver，不支持latest/wildcard/build','当前 compatibility.py:474–499 _stable_semver_key+unique；未将输入grammar通过扩为所有迁移可用。','supported_scoped'),(28,'选择已发布合法组合中双方支持最高集合','当前 compatibility.py:501–513从compatible_version_sets过滤后取末项，不构造笛卡尔积。','supported_scoped'),(37,'patch/minor/major变化规则','规范要求并非所有未来schema变更已测试；需要真实consumer兼容试验。','supported_scoped'),(47,'180天且至少两个minor兼容窗口','是一项时间/发布政策；本轮无180天自然观察证据。','supported_scoped'),(65,'无共同兼容集合明确拒绝','当前501–511明确raise；未来迁移要保留恢复路线，不能只验拒绝。','supported_scoped')])
group('docs/contracts/evidence-query-v1.md',[(3,'精确sourceURN+canonical locator查询','不做fuzzy搜索，不允许同名文档替代精确绑定；契约范围合适。','supported_scoped'),(14,'source locator roundtrip精确匹配','数据库内验证不是重读磁盘原件；必须与消费前byte验证区分。','supported_scoped'),(25,'denormalized span字段一致与版本状态','合理一致性检查；不是金额、财期或经济口径外部真实性验证。','supported_scoped'),(37,'locators稳定分页limit<=500','限定小批次，不等于全库性能或遍历快照一致。','supported_scoped'),(44,'read-only/query_only，WAL需现有SHM，missingDB不建目录','CodeGraph EvidenceQueryService._connection使用mode=ro、无WAL时immutable=1、query_only，缺SHM拒绝；静态支持只读设计。','supported_scoped'),(57,'只输出body-free locator与诊断','隐私/带宽边界，不是消费完整原文的证据。','supported_scoped')])
group('docs/contracts/extraction-quality-v1.md',[(3,'只读确定性提取质量，不作投资review','质量状态只描述来源抽取资格；不继承research accepted。','supported_scoped'),(18,'usable需当前normalizer完成、location可用、有效输出、无review旗标','较raw capture-ready更强。上轮紫金rawready但bundle unusable正说明状态不能互代。','supported_scoped'),(20,'partial/capture等应review_required而非usable','拒绝可正确；还必须有可执行review/reparse流程，原skill实战未闭合。','supported_scoped'),(24,'unavailable情形及诊断理由','不可用不是所有provider错误；须保留源错误分类。','supported_scoped'),(34,'normalizer@version且span完整验证','schema/version满足只是必要条件；当前schemaunsupported实战不是资金模型失效。','supported_scoped'),(40,'span数量、身份和一致性整体验证','不将抽样span合格当所有span合格；静态契约要求。','supported_scoped'),(50,'body-free最多500locator的质量输出','此接口不能证明预测实际读了原文；artifact_read角色列表必须另行命名。','supported_scoped'),(62,'只读DB/文件系统原则','未运行质量检查写入动作；源码/契约符合只读用途，当前完整实际调用由跨项目验收补。','supported_scoped')])
group('docs/contracts/ingest-service-v1.md',[(5,'SourceManifest+ParserResult到span/export的pure source-only core','不承担DB/raw写和LLM；不得以其通过证明生产扫描/注册已实现。','supported_scoped'),(14,'构建export验证原件bytes','当前 SourceExportBundle.build:232–236支持；parser输出是否确实来自此bytes仍由producer契约负责。','supported_scoped'),(24,'canonical locator与parser输出形状约束','定位结构有效≠抽取表格财务含义正确。','supported_scoped'),(43,'source-only emit而非研究知识写入','符合ADR当前边界；旧API IngestPipeline不再是执行指南。','supported_scoped'),(59,'replay字节稳定、冲突定位拒绝','纯输出重放语义，不能推广到canonical_writer下载后DB事务。','supported_scoped'),(73,'announcement receipt贯通原件与证据','必须消费真实receipt而非声明存在；没有在本次发起公告网络采集。','supported_scoped'),(87,'LegacyResearchIngestService仅留历史测试','明确退役，不据保留源码恢复生产执行。','supported_scoped')])
group('docs/contracts/pdf-extract-v3-adapter-v1.md',[(3,'旧聚合Markdown转纯ParserResult adapter','输入缺原始path/hash，因此提供manifest绑定本身不能证明聚合内容来源；这是pure适配边界，不是已发现错绑事故。','supported_scoped'),(15,'严格八字段、扫描失败拒绝','结构验证避免猜测；不证明文本抽取完整。','supported_scoped'),(19,'旧输入已丢page身份，只能全局paragraph/char','不得回造页码或table coordinates；后继page-aware才提供新精度。','supported_scoped'),(23,'page/table字段null，无虚构坐标','正确显式局限；投资证据若必须精确页表应选择真正page-aware源。','supported_scoped'),(25,'TABLE文字不自动认作结构化财表','避免字符串标记被当财务表格事实；新样本需独立表格核验。','supported_scoped'),(29,'truncation部分状态与quality<0.3标记','阈值为启发式，不是测得准确率；预期拒绝和恢复同时验证。','supported_scoped'),(53,'service原件bytes drift拒绝','仅保证manifest绑定文件仍同bytes，不能倒推上游聚合文本生成来源。','supported_scoped')])
group('docs/contracts/pdf-page-aware-parser-v1.md',[(10,'pure core与CW2.20 synthetic PDF/tmp fallback，不宣称生产backlog已跑','原文诚实限定。后继成功不能覆盖全部格式、历史工件和生产worker。','supported_scoped'),(18,'physical页连续且page identity稳定','页码契约有用但表格识别和OCR准确性需真实页对照。','supported_scoped'),(30,'text/paragraph稳定定位','结构确定性不等于抽取信息无遗漏。','supported_scoped'),(42,'tables/cells/bbox坐标和去重','不能仅凭表格非空判断合并单元格、单位、列头正确。','supported_scoped'),(57,'OCR元数据只能来源明确不能虚造','静态设计适当；没有本轮OCR真实运行证据。','supported_scoped'),(65,'table bbox/cell去重不任意丢叠加正文','需要表内外重复以及跨页/跨栏实际PDForacle；目前是规范范围。','supported_scoped'),(70,'find_tables不可用就标歧义，不创造表','可接受降级；不应被消费者作为完整结构化表格使用。','supported_scoped')])
group('docs/contracts/announcement-collector-v1.md',[(3,'只采明确官方URL的公告','不是任意搜索/抓取授权；本轮无外部采集运行。','supported_scoped'),(7,'SSE/SZSE HTTPS与redirect逐跳审查','合理来源边界；历史测试不证明今天交易所可访问。','supported_scoped'),(8,'非空有界PDF且MIME/magic/EOF检查','这些是格式必要条件，不能证明内容真实完整或发行人正确。','supported_scoped'),(10,'content hash create-once hardlink','原件不覆盖设计；文件提交和DB注册仍是两个独立阶段。','supported_scoped'),(11,'replay同输入、conflict不同内容','必须绑定hash而非同文件名；当前实战exactidentity失败不是可以覆盖sidecar的许可。','supported_scoped'),(12,'raw先写、manifest未写的崩溃可恢复','原文承认部分filesystem状态；失败无stdout不能解读为零副作用。','supported_scoped'),(24,'receipt记录URL/时间/hash/path来源','来源链字段存在不能替代实际网络事件；不从receipt推定所有来源许可。','supported_scoped'),(38,'失败没有partial stdout','仅stdout承诺；不扩大为raw/manifest整体atomic transaction。','supported_scoped')])
group('docs/contracts/legacy-caller-reachability-v1.md',[(3,'CW3.1 Phase1 2026-07-19 reachability审计状态','历史清单不是授权执行；新增入口需重新审。','historical_only'),(14,'四个source CLI与三个Windows launcher为canonical入口','静态责任清单；无法凭表单独证明当前安装/常驻加载版本。','supported_scoped'),(23,'Windows/packaged入口不调用research writer','本轮没有重跑launcher或恢复worker，现行读图与文件声明不足以独立重证所有动态路径。','insufficient_evidence'),(29,'50 direct scripts默认failclosed，部分可双env override','默认阻断与永久退役需区分；没有执行任何override。','supported_scoped'),(34,'R1研究编排/写入全部永久退役','结合ADRREADME边界，旧DEPLOY/API/手册应加显著退役标识。','supported_scoped'),(49,'R1拒绝必须早于config/API/net/DB/write/importedpermission','严格验收义务合理；历史报告数量不等于当前全入口攻击路径已重跑。','supported_scoped'),(57,'S1来源兼容脚本默认阻断，迁移前不一刀切删掉','保留有价值来源功能和避免直接生产调用并不矛盾。','supported_scoped'),(76,'RO1只读兼容名目，W1图/测试默认阻断','名字中read/query不证明零写；需检查实际入口副作用，不能靠名称分类。','supported_scoped'),(101,'R2 maintenance通过subprocess漏出旧49扫描需补','历史发现证实只按显式write/API符号扫描覆盖不完；python-S也要拒绝。','historical_only'),(128,'R3 cleanup/raw/log/reset类危险writer退役','导入helper留测试与执行入口阻断可并存；旧排错删除命令不再可用。','supported_scoped'),(146,'R4 link/index/dashboard/lint-fix writer退役','不把输出是Markdown当只读；嵌套--fix也属于写入。','supported_scoped'),(165,'R5 cross_verify数量/标题/链接不能作可信证据','与本次形式验收问题一致，正确应sourceID/locator/hash/独立oracle。','supported_scoped'),(175,'休眠scheduler模块保留，不应有canonicalcaller','保留模块≠部署接线；实际入口需独立测，不能从文档导出当前无旁路。','supported_scoped'),(194,'新增入口维护reachability清单和测试','为未来变更规则；不是本轮已跑完整入口矩阵。','supported_scoped')])

# Legacy operating/reference text: independently dispositioned by each section.
group('docs/ACTION_ITEMS.md',[(5,'2026-04-20清洗+富化已完成记录','历史日期明确，不能当当前catalog/研究质量。','historical_only'),(10,'15674减5038等于10642','独立算术为10636，差6；engineering_context_checks.json，不能据差6推断当前数据库丢失。','contradicted'),(17,'定期一键清理/LLM富化/质量报告',boundary),(37,'maintenance多阶段模块及dry-run','模块说明与预览不证明真实行为只读，旧writer已退役。'),(57,'人工核验3886删除污染项','这是必要未闭合审核任务；当前污染报告4175相对来源链接全部解析出repo，详CTX污染项。','insufficient_evidence'),(62,'为剩余30公司补竞争关系','属于下游研究内容；不因旧行动清单延续公司Wiki写入。'),(83,'35稀缺公司补采集并重新ingest','页面条数不代表关键收入驱动覆盖；原raw source-only采集与旧研究ingest应分开。'),(108,'定期lint矛盾/孤儿/过期','legacy质量语义已下移；只读检查可保留但不能执行旧auto-fix。'),(115,'关键词特异性提高路由精度','词命中分数需标注样本、错漏率与发行人证据，不能把相似度当来源真实性。'),(127,'调评分阈值避免噪声','阈值并无校准证据，不能由主观分数宣称买方质量提高。'),(146,'119页10642条等质量快照','quality_report分类加总119/10642可复算，仅历史总量一致。','historical_only'),(161,'清洗前后减少及改善比较','减总量不自动减少错误率；独立标签/误删核验仍缺。','insufficient_evidence')])
group('docs/API.md',[(7,'Config加载、validate、secretkey/root访问接口','历史接口文档；不读取.env/密钥，当前生产catalog effectivepolicy需要专用doctor而非旧Config.validate。'),(67,'Logger/setup/context日志接口','合理基础工具说明，不是所有exception出口已脱敏的保证。','supported_scoped'),(112,'utils文件/YAML/path/text/数据转换/验证工具','函数演示不表示生产调用；IO helper可能写，不能因为出现在utils当只读。','historical_only'),(299,'Graph公司行业查找与相关实体匹配','legacy图查询与source身份层不同；模糊文本不能替代证券主数据身份。'),(355,'IngestPipeline.run按公司/limit/dryrun处理',boundary),(394,'WikiSearcher/AnswerSynthesizer搜索后生成答案',boundary+' 检索结果数量与综合文本不是正式source evidence。'),(432,'Config/PipelineResult/SearchResult/QueryAnswer数据模型','这些为旧研究接口，与新manifest/span/export类型不等价。'),(486,'配置检查CLI','旧Config检查不覆盖runtime_policy与adapter生产组合。'),(491,'采新闻/下载财报命令','来源采集需canonical source CLI与明确目标；旧directscript为S1默认阻断。'),(500,'ingest/classify命令','旧直接处理入口不可因API手册存在绕过退役。'),(509,'产业链/公司查询CLI','阅读/显示可能仍有价值，但不能称当前source contract API全合格。'),(518,'pytest全部与单元测试命令','示例可用来定位历史测试，不是本次运行记录。','historical_only')])
group('docs/ARCHITECTURE.md',[(5,'上游raw/evidence系统总体定位','与ADR scope一致，架构图不是生产每条路径完成证明。','supported_scoped'),(31,'采集只保存来源与身份','应由真实provider/receipt/注册验证；实战下载后注册失败证实链未闭合。','supported_scoped'),(44,'parse/normalize职责及解析质量','与source-only边界一致；未完成工件必须保留状态。','supported_scoped'),(55,'检索/只读export交付下游','export build原件验证有当前静态支持；RF消费者实际读工件另审。','supported_scoped'),(71,'基础配置/日志/错误/指标','模块存在并不保证统一策略；doctor未读policy是当前反例。','insufficient_evidence'),(85,'canonical manifest/span/export模型','当前source_contract符号和导出校验有限支持；不继承legacyDB例子。','supported_scoped'),(98,'实体关系图作路由元数据','可以保留Company/Sector/Theme标记，不能从边自动产生投资判断。','supported_scoped'),(141,'采集到raw的流程图','是目标流程；真实写raw成功但索引失败，不是图即运行。','insufficient_evidence'),(159,'canonical规范化/解析流程','单个pure IngestService不能证明后台worker实际接入。','insufficient_evidence'),(176,'query/export流程','必须用source identity/locator验证，当前纯对象与真实消费者链分开。','supported_scoped'),(195,'配置层次与文件单一来源','历史层次与当前双allowlist/doctor硬编码root有漂移风险；effective决策需单一化。','insufficient_evidence'),(218,'raw/parsed/catalog文件布局','布局为契约，不代表旧存量全迁移；本轮不迁盘。','supported_scoped'),(248,'legacy DB示例非canonical','原文明确提示历史边界，不应将例表作为新实现要求。','historical_only'),(281,'错误分类/重试/熔断器','通用示例不能覆盖CN403实际retryable被包装为fatal false的路径。','insufficient_evidence'),(324,'日志/metrics/health endpoints','不是生产doctor与用户旅程均绿；要检查测量对象和实际collector接线。','insufficient_evidence'),(356,'数据源/parser/query扩展点','扩展须合同与adapter/profile能力，不能承诺任意目录config-only。','supported_scoped'),(378,'单机与未来分布式部署','future分布式明确未实施；不是当前缺陷。','not_deployed'),(407,'并发、缓存、批处理优化','旧建议未考虑当前单实例worker与预算/暂停；不得照此增加生产并发。'),(432,'secret/env、文件权限、输入验证','合理一般原则；当前安全状态需专门证据，未检查密钥内容。','supported_scoped')])
group('docs/DEPLOYMENT.md',[(6,'Python/OS/内存等系统要求','历史需求规格，无法证明本机生产吞吐满足。','historical_only'),(15,'clone/venv/pip安装步骤','安装命令不证明三个项目可执行模块来源一致；实际安装加载版本需单测。','insufficient_evidence'),(38,'env与API配置','不要由示例推断真实凭据已轮换；本轮不读取.env或发keycheck。','supported_scoped'),(64,'mkdir/graph初始化','旧图writer边界已收窄；不得自动重建现有graph。'),(76,'scheduler/LLM/search/path YAML示例','旧配置不能作为当前effective runtime policy，尤其同目录多个版本。'),(162,'manual collect/ingest/产业链命令',boundary),(175,'cron采集、ingest、财报任务',boundary+' 旧scheduler保持禁用；不创建定时任务。'),(192,'systemd常驻服务','未纳入实际Windows paused intent；旧脚本已退役，不执行。'),(247,'日志、healthcheck、metrics查看','healthcheck示例不验证active policy/root的兼容性。','insufficient_evidence'),(284,'备份DB/YAML并恢复','live WAL须一致性快照；复制单文件和直接覆盖不证明可恢复。'),(320,'API/内存/磁盘/网络通用排错','历史通用建议不是本次provider403或adapter缺失的具体根因。','historical_only'),(352,'DEBUG/dry-run调试','dry-run有不同policy路径，不能用无写预览替真实scan接线证明。','insufficient_evidence'),(365,'async并发/数据库/缓存优化','与当前预算、单实例、immutable输入不同；不要执行示例改变生产策略。'),(391,'安全建议','仅一般性政策；没有当前独立安全/密钥外部轮换证据。','supported_scoped'),(400,'git pull/迁移/升级步骤','升级不能只更新源码；安装副本、配置/DB epoch、worker加载态要作为同一组合验证。','insufficient_evidence')])
group('docs/GATE_SYSTEM.md',[(11,'full_pipeline Gate执行、跳过、preview',boundary),(32,'Stage/Gate架构和Gate清单','旧研究门系统，非source extraction quality或revenue validation同一对象。'),(118,'按doc类型规则配置和修改即生效','示例没有常驻loadedconfig证据；不推广为热加载已生效。'),(164,'五维权重30/25/20/15/10','与使用说明书273–277的25/25/20/15/15冲突；两套均不作为投资结论充分证明。','contradicted'),(174,'七类金融风险LLM必审','主观LLM清单不能自动推可信投资结论；需要source/单位/财期/合并边界独立oracle。'),(184,'LLM JSON输出和评分','JSON合法与评分值不是统计准确率。'),(204,'平均分>=阈值自动通过','缺校准/误报漏报验证；门通过不能替代买方原始证据复核。'),(214,'DiagnosticsEngine诊断与RetryOrchestrator修复','历史设计描述未提供当前可执行的source review/repair路径。'),(250,'代码结构与Gate测试','模块/测试目录存在不表示生产canonical接入；只作历史。','historical_only'),(282,'用真实数据手动验Gate','示例指令未执行；当前原件不可因此写review通过。','insufficient_evidence'),(311,'检查太严时调阈值','改变阈值要重新测误差和业务损失，不为绿色调门。'),(316,'提高阈值从4.0到3.5','数值实际降低；属于文档说明错误，不据此推运行一定降低。','contradicted'),(320,'review queue积压处理','队列需实际可达、可消费、可恢复，而非只列管理指令。','insufficient_evidence'),(333,'v1.0开发完成记录','2026-05-17版本记录是历史，不是现行端到端验收。','historical_only')])
group('docs/OPERATIONS.md',[(6,'source-only边界与旧研究链禁止','开头原则正确，后文混入旧自动运行/恢复命令需一致清理。','supported_scoped'),(15,'AnnouncementCollector create-once运行','契约输入合理；本轮未执行网络采集或create。','supported_scoped'),(33,'IngestService纯只读运行','可产出stdout，调用方输出文件仍写；不等于整个shell命令零副作用。','supported_scoped'),(63,'SourceExport tmp再rename防半成品','正确消费者责任，与failure no stdout区分；未实跑export事务。','supported_scoped'),(94,'205A股/35Tier1批量下载和强制重下','旧S1脚本默认阻断；当前需canonical显式授权，不按时间估算开批任务。'),(132,'只添目录config后直接跨根复用','当前prodroot缺adapter与doctor硬编码root使全称不成立；见GP002fixture/prod对照。','contradicted'),(142,'两白名单共同管理root种类','后继ADR010指向单一policyowner，旧名单需显式退役。'),(164,'新闻采集现状及均衡化建议','重复垃圾/少数公司集中为历史观察；本轮没有重新采集业务正文核验。','historical_only'),(200,'旧Ingest读取Layer3未来模式',boundary),(221,'legacy维护禁止写入','与现行边界一致；后文任务表不可重新授权writer。','supported_scoped'),(230,'健康检查与lint只读/禁止fix','只读标注正确，但actor是否真只读仍要实入口审。','supported_scoped'),(244,'Scheduler保持禁用','是现行限制，旧DEPLOY cron/systemd与之冲突。','supported_scoped'),(250,'建议任务计划表','不得依据建议自动安装/启用；实际暂停意图有更高约束。'),(268,'每周检查和备份/清理','检查可读；删除和重新处理需要当前计划与确切恢复设计。'),(282,'VACUUM INTO备份方案','一致snapshot优于拷活DB；本轮未运行，空间容量依实际DB/WAL/临时量计算。','supported_scoped'),(303,'保留最近3份/阈值15或25GB','历史20GB估计不能覆盖后来的46GiB DB+同量备份；自动删除旧副本不能当通用现行策略。'),(311,'不得覆写/随意压缩生产DB','一般禁止正确；必须与后继归档集合核验及不可删未备份项连用。','supported_scoped'),(318,'documents retire治理与审计','逻辑retire不等于raw删除；当前不做治理写入。','supported_scoped'),(344,'worker gitshort与HEAD一致就新版','dirty文件/已加载module不能由gitshort完全证明；应记录loaded build/configfingerprint。','insufficient_evidence'),(352,'stop→治理→start→scan恢复协议','无条件start可能覆盖用户原paused意图，旧协议应保存恢复base状态。'),(370,'documents restore语义','需明确撤销范围与审计，不可由历史示例执行生产restore。','supported_scoped'),(386,'新fixture默认capture-ready','有助正例但会隐藏生产元数据缺项；GP002 fixture显式adapter而prod缺失是独立反例。','supported_scoped'),(394,'改resolver/ingest要更新所有测试直到绿','必须同时测未迁移配置/旧数据反例；只迁fixture使其合格会失去回归发现力。','supported_scoped'),(401,'worker依赖注入避免调用漂移','注入可测不等于真实入口加载同一实现；安装/常驻态需实证。','supported_scoped'),(407,'identity断言/更正supersedes链','需要来源证据和明确失效，不能因同名或文件名猜issuer。','supported_scoped'),(417,'issuer anchoring与resolve诊断','安全主数据映射是必要非充分条件，原件注册失败要保留阶段根因。','supported_scoped')])
group('docs/TROUBLESHOOTING.md',[(9,'Q1/Q2配置验证和示例config','旧Config无法诊断v2 flag×root缺adapter；示例替换可能丢production字段。'),(57,'Q3错误目录调整配置','原件不应直接迁移去迎合resolver；先核hash/location/rootpolicy，保留immutable。'),(84,'Q4超时重试','重试须共享总deadline；当前filing reviewer隔离反例显示最小10秒可超预算。','insufficient_evidence'),(109,'Q5下载失败重试/代理','CN403属于provider/runtime需结构化上报，不全部判代码bug或盲目重复。','supported_scoped'),(140,'Q6规则分类','文件名分类不能替代财期/issuer/page证据；旧人工关键词目标范围有限。'),(170,'Q7 shutil.move修分类','直接移动raw与immutable原件/索引location职责冲突；不执行。'),(196,'Q8重跑Ingest解决失败',boundary),(226,'Q9生成索引解决无结果','source-catalog索引与legacy图/query索引不同，不能运行旧writer生成research。'),(251,'Q10清缓存/跳过失败测试','删pytestcache不证明缺陷解决；测试预期失败须保留raw rc独立判定。'),(280,'配置/覆盖/状态/测试诊断命令','目录数和覆盖率只度量枚举范围；不能推用户研究闭环。','supported_scoped'),(328,'日志分类查询','日志存在不是错误保密/完整性保证，需实际exception出口测试。','supported_scoped'),(356,'backlog大但waiting的调度解释','历史状态分类不能替代当前SQL阶段诊断；worker调查显示enqueue前耗时902秒。','historical_only'),(374,'LLM401/deferred排错','本轮不读key/发测试；鉴权、预算和队列可达需分别判定。','supported_scoped'),(382,'active模式资源参数','资源建议不代表高负载已通过；应在隔离副本按原query测全候选集合等价。','insufficient_evidence'),(386,'Pause/Stop WinError5重试','权限或process状态需保留原错误；不能自动resume用户paused。','supported_scoped'),(394,'缓存/并发/批处理优化','旧建议与单writer/暂停/预算约束须统一，不直接增加生产线程。'),(428,'从备份cp恢复/重下载/删.ingested重处理','可能覆写raw或重启退役链，与现行边界冲突；不执行。')])

group('docs/source-acquisition-dedup-design.md',[(3,'设计已实现并于8/7核验','过强整体完成描述：当前canonical_writer先copy+sidecar后scan且忽略失败report，真实07/08注册失败；须按层修订完成状态。','contradicted'),(6,'raw只属于company-wiki，query-first，禁止重复副本','正确目标，不能用设计摘要证明所有安装入口已遵守。','supported_scoped'),(19,'现状重复、多目录、下载路由问题','历史问题描述；不要用今天架构反推当时都已解决。','historical_only'),(33,'原件/目录/下载器/消费方四方所有权','与ADR010单owner方向相容；需消除旧allowlist影子与绕过入口。','supported_scoped'),(61,'逻辑报告/版本/provider/bytes/location/处理六层身份','分层合理；已有表/类型不等于这六层在新下载事务全部注册。','supported_scoped'),(76,'市场/证券/财期/类型/版本组成规范identity','需覆盖非日历财年/更正版/总额净额；字典序accession不能判断新旧。','supported_scoped'),(96,'实体别名归一','需主数据证据而非模糊相似度强行唯一。','supported_scoped'),(107,'exact/semantic版本关系分开显示','semantic normalized text不保证完整视觉语义相同；仅显示不得据此删raw。','supported_scoped'),(124,'jsonl/csv/md索引导出','输出文件存在不保证catalog刚写raw已注册；需同一源identity内容验证。','supported_scoped'),(149,'SourceRequest明确公司/财期/类型','资格不完整必须拒绝或补缺；不能默选未来文档。','supported_scoped'),(165,'resolve first再经明确授权下载','方向正确；已下载未索引应恢复注册而非再下载，真实failure暴露第三状态。','supported_scoped'),(179,'Adapter discover/download合同','接口存在不等于实际provider可达；403单列外部访问阻断。','supported_scoped'),(211,'下载后提交hash/metadata/注册/re-resolve','copy+sidecar成功后scan失败使注册为空；当前链未满足完整承诺。','contradicted'),(222,'provider/version/blob/location/receipt和task在一个catalog事务提交','当前 canonical_writer.py:181–211 文件先写、scan返回未审查、再resolver失败；不能将该设计称整体事务已实现。','contradicted'),(223,'崩溃重放保持幂等且无孤儿','真实已写文件无注册，缺可验证恢复阶段；不能通过重新下载覆盖。','insufficient_evidence'),(225,'CN用StockInfo，HK/US用dayu','本轮真实路由方向与日志相符；不推广为三个provider均运行成功。','supported_scoped'),(235,'canonical path与immutable provenance','小米/MSFT raw+sidecar确已保留，错误是后续注册，不声称原件损坏。','supported_scoped'),(262,'revenue消费handle而非自己保存raw','目标合理，实际source-preparation阻断前后职责和artifact消费仍需联测。','supported_scoped'),(291,'canonical版本选择与未来信息控制','策略需要明确定义period/revision/as-of，不由文件名或排序隐式决定。','supported_scoped'),(304,'后台资源控制与用户暂停优先','当前worker仍paused；FF显式下载临时scope需文档明确，不视为未授权绕过。','supported_scoped'),(315,'LLM不负责identity/hash/去重事实','正确确定性边界，与旧全面计划“关键必须LLM禁Regex”冲突需收敛。','supported_scoped'),(335,'PhaseA可见性','索引枚举范围与资格/可消费性要分别证。','supported_scoped'),(343,'PhaseB身份回填','回填是设计工作；不能将缺元数据文件自动视为已合格。','supported_scoped'),(350,'PhaseC adapter/dryrun','dryrun shadowfalse与actual shadowpolicy不同，预览不能覆盖生产路由。','supported_scoped'),(356,'PhaseD query-first集成','存在helper/caller不足以证明默认入口到达并真正读取。','supported_scoped'),(362,'PhaseE受控下载','provider成功不等于canonical注册与复用闭环，当前实战失败。','insufficient_evidence'),(368,'PhaseF可选空间治理','后继取消迁盘保留；未做可选阶段不是本次失败本身。','not_applicable'),(374,'三项目改动清单','owner清单和实现状态分离，不能从责任分配推已部署。','supported_scoped'),(404,'必须通过的验收矩阵','原义务要保留真实双分支/跨根/as-of/错误恢复，fixture不能全代。','supported_scoped'),(419,'本轮不做内容边界','不得把明确排除误判为缺陷，也不由未来阶段闭合原未完成项。','supported_scoped')])
group('docs/source-catalog.md',[(3,'跨目录原件保留、只维护目录/派生物','source-only边界正确，复制/删除非本轮授权。','supported_scoped'),(7,'worker常驻且scan后即可query全部资料','当前paused非故障；实际active scan缺adapter返回errors，新raw查不到，不能将无条件表述当当前能力保证。','contradicted'),(9,'配置root/profile实现多目录','必须有对应adapter和policy组合；缺字段即失败不由YAML可解析发现。','supported_scoped'),(24,'source/document/location/derived关系','模型存在不能证明下载后真实四层均写；上轮注册为空。','supported_scoped'),(39,'exact字节相同与semantic copy分组','概念分开正确；semantic仅候选显示，不删源。','supported_scoped'),(42,'semantic_copy零误报','相同规范文本可能遗漏图片/表格/OCR，不能保证原始语义零误报；没有声称已发生误删。','contradicted'),(48,'dayu sidecar兼容','格式兼容不保证新文件注册/issuer资格，需真实producer输出消费。','supported_scoped'),(59,'scan/normalize/summarize/export/query命令','写入型命令不是只读诊断；本轮不执行。','supported_scoped'),(86,'evidence/locators/quality只读精确查询','源契约和限定只读实现支持，不能误称预测已读工件。','supported_scoped'),(95,'official security master refresh/identify','刷新可能写/联网，不因identify示例而运行；已缓存身份与当前资料期分开。','supported_scoped'),(102,'ensure默认只读，显式allow-download后路由','根真实调用遵守；已有原件尚未注册需第三分支恢复。','supported_scoped'),(116,'source-only scheduler不研究写入','正确边界；旧手册并行pipeline不再适用。','supported_scoped'),(128,'Pause会拒绝统一下载','filing reviewer已确认显式下载PausedWorkerScope临时允许并恢复basepaused，属有意设计；此绝对文档需对齐，不报安全绕过。','contradicted'),(130,'自动登录/启停/暂停/恢复指令','状态命令与安装/启动/恢复副作用明确分开，不照文档自动resume。','supported_scoped'),(192,'索引/manifest/normalized/summary输出','输出存在≠usable/capture/review/actualread；应该分层状态。','supported_scoped'),(220,'size+mtime复用与失败续跑','优化不能替代消费前byte校验；未变化stat不保证任何威胁模型下内容没变。','supported_scoped'),(230,'多格式支持列表','格式列举不是覆盖每类复杂表格/OCR准确性及生产backlog证据。','insufficient_evidence')])

group('docs/使用说明书.md',[(26,'状态查看/单公司pipeline/测试快速开始',boundary),(65,'七阶段研究系统架构','已退役研究架构，不是现行source-only技术合同。'),(101,'文件结构和Dashboard入口','历史路径导航可用性需实际文件；不代表当前数据健康。','historical_only'),(128,'HTML/Markdown dashboard查看和更新','查看与generate写行为不同；旧dashboardwriter R4退役。'),(173,'pipeline阶段、dryrun、skip-gates、limit','旧研究编排不可执行；skipgates不是正式收入研究授权。'),(214,'doc类型prompt配置','配置模板不能证明实际LLM调用与来源绑定。'),(235,'Gate列表与配置','旧Gate通过范围不等于当前source/forecast验证。'),(273,'五维权重25/25/20/15/15','GATE_SYSTEM168–172不同权重；文档相互冲突，均缺准确性校准。','contradicted'),(283,'自动审核机制与测试套件','研究review不同于prompt-injection/extraction审核，不能用同一accepted字段通用。'),(297,'运行测试/报告与90%类阈值','命令例子不是已执行；关键必过项不能由总体比例替代。','insufficient_evidence'),(340,'自动综合/信息熵减','属于下游研究，旧writer退役；压缩不代表知识更正确。'),(361,'365/90/180天过期启发式','固定年龄不能确定财务披露失效，最新更正版/财政期/长期事实有不同语义。'),(386,'核心问题动态进化','研究状态移交下游，不能在company-wiki自动改投资问题。'),(409,'Tier1批量处理与报告','列表/批处理不证明代表性与默认路径可用，不执行。'),(445,'投资估值引擎','company-wiki现行明确不估值；交给下游 validated revenue/financials。'),(472,'配置/Prompt/添加公司','identity需证券主数据与issuer证据，不能只加图节点和字符串。'),(521,'pipeline/Gate/LLM/encoding排错','encoding可作参考；重启/LLM调用/旧pipeline均不依手册执行。'),(573,'命令参考及快捷卡','保留为历史导航，需显著退役标识以免代理按旧指令操作。'),(648,'文档类型、Wiki页型、指标','历史taxonomy不代表规范财务period/数据质量；page/entrycounts不是准确性。','historical_only')])
group('docs/可视化使用指南.md',[(32,'Obsidian安装、打开vault','阅读展示层说明，不是数据摄取或source资格验收。','supported_scoped'),(64,'图谱、Wikilinks、Dataview、搜索','可视化节点/命中不证明来源完整或投资结论可信；本轮无UI渲染验证。','supported_scoped'),(149,'推荐插件','历史建议，不安装、不将插件可用性当当前已验证。','historical_only'),(161,'WebClipper到inbox等待LLM','剪藏不能绕过immutable provenance/身份/许可/审核；不属于已验证canonical admission。','insufficient_evidence'),(184,'乱码/链接/图谱常见问题','演示建议不是实际已修运行结果。','historical_only'),(197,'Web浏览/搜索/产业链图谱','阅读呈现与生成writer不同；未启动server或build。','supported_scoped'),(204,'双击离线页面即可交互图谱','图谱inlineJS fetch 数据/graph_data.json，file协议是否成功需浏览器验证；本轮未验证，不能判定已成功或必失败。','insufficient_evidence'),(274,'重新build与开发模式','会写output/启动服务，不执行；旧writer边界须先澄清。'),(300,'两种展示方式对比','只是产品界面能力描述，不是生产端到端测试。','supported_scoped')])
group('docs/知识库全面审查与系统性改进计划.md',[(9,'五个尖锐发现与此前计划全部未执行','单日/日志缺席不足推出所有升级均未执行；保留历史质疑而不认可全称。','insufficient_evidence'),(19,'对照LLM Wiki理念结构差距','理念不等于来源事实准确性，合理追溯/闭环目标可保留到各owner。','historical_only'),(49,'设计意图偏离与零LLM调用','调用0不必然坏，确定性identity/date/hash应不依LLM；健康目标不是每日LLM次数。','supported_scoped'),(78,'改进报告执行断层','本轮很多helper/接线差证实这种机制风险，但不能回溯证明该日每条断言。','historical_only'),(101,'东方电缆页面过压缩导致买方不可用','历史单公司样例诊断；未重审业务事实，不扩为所有公司。','historical_only'),(115,'半导体行业page缺乏深度','历史业务案例，正文证据不在本次工程审查范围。','historical_only'),(122,'估值页没有投资判断/可信数值','后继明确投资研究移交下游，不能为修此例恢复company-wiki估值writer。'),(140,'缺少验证/压缩/淘汰熵减机制','验证和证伪合理，压缩/删除不可自动等同质量，须保护raw与独立误删评估。','supported_scoped'),(159,'零成本替代LLM导致所有失败','因果全称未被控制对照证明；错误规则/实现可坏，但LLM也需独立验证。','insufficient_evidence'),(174,'配置碎片化导致错误','本轮policy/root/doctor范围断裂有具体独立反例，可支持机制层风险而非全部旧历史数字。','supported_scoped'),(189,'全覆盖变零深度','关键需求覆盖比条目数合理；实际覆盖率应按source×driver×period定义。','supported_scoped'),(207,'三层数据架构必须执行','后继source manifest/span/export职责取代旧research三层，不重复造生产链。'),(222,'关键模块必须LLM，禁止正则替代','全称过宽；identity/hash/单位/日期/结构校验需确定性，LLM仅在证据适用场景且测误差。','contradicted'),(233,'压缩/去重/淘汰提高质量','不能据保留条数/压缩比自动推准确率，raw不可按semanticcopy自动删除。','supported_scoped'),(248,'从全覆盖转20核心公司深覆盖','可作研究抽样策略；不证明跨行业泛化，要声明样本/排除/生命周期。','supported_scoped'),(261,'废弃幽灵模块重建闭环','原则与实战一致，但已退役研究writer不可复活，闭环按source职责接下游。','supported_scoped'),(276,'统一配置单一事实来源','必要；要校验effective配置与policy一起，不能只统一配置文件名。','supported_scoped'),(283,'dashboard真实指标且LLM>50次/日','calls次数不是质量KPI，可鼓励无用/重复调用；改为用户journey/错误/准确性测量。','contradicted'),(298,'文档→代码转化和阶段验证','需保留原义务/缩范围/后继未做，不能再次只验文件/卡片存在。','supported_scoped'),(310,'P0本周/P1两周/P2一月/P3持续排程','旧期限已过不等于每条实施失败；后继scope/移交优先，未获执行证据部分历史处理。','historical_only'),(342,'文档多但改进失败的结语','作为问题陈述不反转成产品通过；本轮区分真实修复与误扩通过。','supported_scoped')])
group('docs/系统审查与改进计划.md',[(3,'唯一权威且整合/删除旧报告','后继ADR/BOUNDARY取代其权威，历史汇总不能覆盖后来的scope。'),(11,'数据/运行/代码状态计数','2026-04-25快照，当前没有该时点一致性DB重建；保留历史。','historical_only'),(47,'信息流熵增为根本瓶颈','定性诊断有启发，但不是所有当前故障的唯一根因。','historical_only'),(69,'三层raw/Markdown/tag内容架构','后继source contract职责保留原件/证据，旧研究tag/自动ingest链不重建。'),(135,'三层优势与重算/溯源','优势要通过实际byte/locator/版本/最小重算验证，不由架构图推出。','supported_scoped'),(146,'原则/配置驱动/LLM优先','LLM不能替代确定性身份/日期/单位，要求需按实际领域缩窄。'),(159,'修classify_pdf，非季/半年日期一律12-31','报告类型不能推出全球财政年末；Q4/非日历财年/修订报告必须读真实period。','contradicted'),(164,'修配置key','小修是否有效看原测试范围；不把后续系统故障全推该key未修。','historical_only'),(169,'URL黑名单防污染','黑名单是防线而非完整issuer/source正面证据，需不误伤/不漏过对照。','supported_scoped'),(174,'重处理损坏条目','旧writer退役；现代目标为source重新parse/consumer重算，不覆盖raw。'),(179,'删明显垃圾','主观明显须独立证据，污染清单来源链接不可靠，未授权删除。'),(188,'Layer2批处理','后继新parser/source workflow替代旧研究流程。'),(193,'Layer3标签化','metadata可留，上游不自动产投资判断标签。'),(202,'适配ingest_v2','R1已永久退役，不复活。'),(207,'接入scheduler','legacy scheduler禁用，不因旧计划启动。'),(216,'压缩超大Wiki页','研究writer移交下游；压缩质量需关键事实保真。'),(222,'LLM投资判断','不属于company-wiki现行责任。'),(227,'补综合评估','应由下游买方研究生成，不在source系统自动写结论。'),(231,'新闻均衡化','均衡采集是策略目标，不证明来源可信或收入驱动覆盖。','supported_scoped'),(240,'矛盾检测→标记→审核','完整闭环是合理要求；不只helper返回dict，需实际可达review。','supported_scoped'),(246,'lint发现自动修复','旧maintenance/writer退役，不执行自动写。'),(251,'state_store写入','计数状态不能代替真实userjourney，不为报表好看写人工绿色。'),(256,'废弃无价值模块','已退役策略保留；具体能力先检查有没有source-only用途，不按名字删除。','supported_scoped'),(264,'关键路径测试50段>90%','50段便利样本缺分层/误差范围，不能推出跨行业全库准确性。','insufficient_evidence'),(274,'5+10+8+7天总排程','总30天是计划估计不是自然观察/完成证据。','historical_only'),(287,'验证终点数据量/运行/用户价值','用户价值有必要，但不得把页数/entries/LLM次数代替准确性与可用性。','supported_scoped'),(303,'整合的旧文件清单','内容迁移保留版本映射，不能让被整合旧未完项消失。','historical_only')])

group('docs/quality_report_final.md',[(3,'2026-04-20 final质量快照','final仅当时报告名，无后续审计/删除复核closure证明。','historical_only'),(5,'119页10642条全局数','三类页91+25+3=119，条3166+6893+583=10642可复算；不验证底层当前DB。','supported_scoped'),(18,'公司91/3166、行业25/6893、主题3/583','历史计数无时点snapshot独立重数，仅加总自洽。','historical_only'),(29,'Top10条目过多可能污染','原文为可能，不误判为已证污染或立即删除依据。','supported_scoped'),(44,'最少条目公司数据缺口','条目少不直接等于关键问题缺覆盖，需driver/source需求映射。','supported_scoped'),(59,'31页缺综合评估','当时研究任务，现行职责已移交下游。'),(80,'行业覆盖统计','页面覆盖不等于可用证据、行业经济模型或生命周期覆盖。','historical_only')])
group('docs/SECURITY_REMEDIATION.md',[(3,'活动文件0、历史3指纹与.env2处匹配','历史扫描结果；本轮不读取.env/打印任何secret，也未重新扫描全git历史。','historical_only'),(15,'清除明文与改环境变量','仓库整改和外部凭据轮换是不同义务，文件不再出现不证明令牌撤销。','supported_scoped'),(27,'外部服务轮换仍需完成','缺外部轮换回执，不能发整体安全已关闭声明。','insufficient_evidence'),(37,'hooks/git历史处理选择','未被新任务授权执行历史改写或密钥操作，不将文档建议当本轮指令。','supported_scoped')])
add('docs/contaminated_entries_review.md',1,'3886污染项待逐条人工核验','insufficient_evidence','工程头/分组计数已核：分组总3886、污染源heading3886。业务原文31958行未逐事实重审，不能据标题证明所有项污染、被删正确或审核完成。','先修复条目边界和可访问来源，再由业务owner逐项核验；本轮不删/恢复任何数据。')
add('docs/contaminated_entries_review.md',17,'删除审查清单来源链接可追溯','contradicted','engineering_context_checks.json 独立解析全部4175个[来源]相对链接，以当前docs位置解析全部越出company-wiki。只证明基址错误，不声称目标文件被删或原件不存在。','按原件身份和正确相对基址重建审查引用；保留旧清单及映射。','P2')
add('docs/contaminated_entries_review.md',38,'每个污染条目有稳定日期/来源边界','contradicted','现行行17/38/31954链接与下一条日期文本直接拼接；边界损坏使3886个标题计数不足以保证3886条独立可审记录。','先恢复独立记录ID/边界再核清理正当性；禁止用计数自证。','P2')
group('web/docs/index.md',[(1,'首页和公司/行业导航','展示目录，不是来源合同或投资结论。','supported_scoped'),(14,'45公司27行业879news4597PDF123页统计','历史2026-04-19呈现数字，不视为当前有效coverage/质量。','historical_only'),(36,'公司/行业研究导航内容','只审工程导航/模板边界，未验证链接后业务文章事实。','supported_scoped')])
group('web/docs/tags.md',[(1,'标签索引模板','7行呈现模板可全文审；未跑站点构建，不声明动态标签已渲染。','supported_scoped')])
group('web/docs/产业链导航.md',[(1,'产业链导航及核心问题列表','表格问题是研究提纲，不是已有可信答案或source coverage。','supported_scoped'),(65,'导航链接和研究入口','链接/页存在不证明公司研究已完成；未核每份业务正文。','supported_scoped')])
group('web/docs/图谱.md',[(1,'交互网络图谱页面','全文126行静态读，filter/search/reset确有代码；未做浏览器视觉/交互验收。','supported_scoped'),(36,'加载数据/graph_data.json并渲染vis图','相对fetch依赖部署和资源加载；未据静态代码称离线file协议必成功。','insufficient_evidence'),(95,'搜索/重置/类型筛选行为','静态存在对应handlers只证明实现意图；不能证明UI与真实图数据运行一致。','supported_scoped')])
add('companies/亿华通/raw/news/2026-04-25_1ed46181_CelestialMind_Community_B1_Reviews_Proje.md',1,'被工程关键词命中的raw/news业务文本','not_applicable','root明确批准排除raw/news业务正文；不是company-wiki工程规划，不声称全文事实核验。','保留inventory排除原因，若以后业务真实性任务再另行审。')

rows.extend(new)
(H/'item_ledger.jsonl').write_text(''.join(json.dumps(r,ensure_ascii=False)+'\n' for r in rows),encoding='utf-8')
(H/'engineering_context_items.json').write_text(json.dumps(new,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'new_context_items':len(new),'total_items':len(rows),'context_paths':len({r['original']['path'] for r in new})},ensure_ascii=False))
