"""Declare and prove the single append-only annotation applied to a frozen cases.json.

Review finding (c) of 2026-09-20 asked for the invalid observation to be marked inside
``cases.json`` rather than only in prose. Rule 10 of the execution pack allows a declared repack
of a frozen fixture if the scope is stated and the difference is proven. This script does exactly
that, and nothing else:

  * old bytes come from ``recovery/before_fixes/cases.json`` (the frozen revision),
  * new bytes come from ``evidence/<CARD>/cases.json`` (regenerated by the card's oracle
    generator, which now writes the annotation),
  * a full recursive structural diff is computed and must consist ONLY of added keys on the
    observation named in ``--expect-observation``,
  * the result, including the old/new sha256 and byte counts, is written to
    ``evidence/<CARD>/cases_annotation_repack.json``.

Exit codes: 0 the difference is exactly the annotation, 8 an unexpected difference was found.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import time


def sha256_file(path):
    with open(path, "rb") as handle:
        return hashlib.sha256(handle.read()).hexdigest()


def diff(old, new, path="$", out=None):
    if out is None:
        out = []
    if type(old) is not type(new):
        out.append({"path": path, "kind": "type_changed", "old": repr(old), "new": repr(new)})
        return out
    if isinstance(old, dict):
        for key in sorted(set(old) | set(new)):
            if key not in new:
                out.append({"path": "%s.%s" % (path, key), "kind": "key_removed",
                            "old": repr(old[key])})
            elif key not in old:
                out.append({"path": "%s.%s" % (path, key), "kind": "key_added",
                            "new": repr(new[key])})
            else:
                diff(old[key], new[key], "%s.%s" % (path, key), out)
    elif isinstance(old, list):
        if len(old) != len(new):
            out.append({"path": path, "kind": "length_changed", "old": len(old), "new": len(new)})
            return out
        for index, (a, b) in enumerate(zip(old, new)):
            diff(a, b, "%s[%d]" % (path, index), out)
    elif old != new:
        out.append({"path": path, "kind": "value_changed", "old": repr(old), "new": repr(new)})
    return out


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--card", required=True)
    parser.add_argument("--attempt", required=True)
    parser.add_argument("--expect-observation", required=True)
    parser.add_argument("--allowed-added-keys", default="not_executable_as_frozen,construction_error")
    args = parser.parse_args()

    card = args.card
    attempt = os.path.abspath(args.attempt)
    evidence = os.path.join(attempt, "evidence", card)
    old_path = os.path.join(attempt, "recovery", "before_fixes", "cases.json")
    new_path = os.path.join(evidence, "cases.json")
    allowed = set(args.allowed_added_keys.split(","))

    old = json.load(open(old_path, "r", encoding="utf-8"))
    new = json.load(open(new_path, "r", encoding="utf-8"))
    differences = diff(old, new)

    observation_marker = "extra_observations"

    def resolves_to_expected_observation(path):
        """$.extra_observations[2].construction_error -> check the id at that index really is the
        observation we declare, instead of string-matching the id inside the path."""
        parts = path.split(".")
        if len(parts) != 3 or not parts[1].startswith(observation_marker + "["):
            return False
        index = int(parts[1][len(observation_marker) + 1:-1])
        try:
            return new[observation_marker][index]["id"] == args.expect_observation
        except (KeyError, IndexError, TypeError):
            return False

    unexpected = []
    for item in differences:
        path = item["path"]
        if item["kind"] != "key_added":
            unexpected.append(item)
            continue
        if not resolves_to_expected_observation(path):
            unexpected.append(item)
            continue
        if path.rsplit(".", 1)[-1] not in allowed:
            unexpected.append(item)

    doc = {
        "card_id": card,
        "file": "evidence/%s/cases.json" % card,
        "old_revision": {
            "path": "recovery/before_fixes/cases.json",
            "sha256": sha256_file(old_path),
            "bytes": os.path.getsize(old_path),
        },
        "new_revision": {
            "path": "evidence/%s/cases.json" % card,
            "sha256": sha256_file(new_path),
            "bytes": os.path.getsize(new_path),
        },
        "repack_scope": "append-only annotation on one observation: the keys %s on the observation "
                        "with id %s" % (sorted(allowed), args.expect_observation),
        "difference_is_only_the_declared_annotation": not unexpected,
        "all_differences_found": differences,
        "unexpected_differences": unexpected,
        "what_did_NOT_change": {
            "input.json": "regenerated by the same generator run; byte-identical (see "
                          "recovery/before_fixes/input.json)",
            "oracle.json": "regenerated by the same generator run; byte-identical (see "
                           "recovery/before_fixes/oracle.json)",
            "positive_continuity_defaults_expectations": "unchanged",
            "tolerances": "unchanged",
            "case_expectations_and_refusal_conditions": "unchanged - every pre-existing key of "
                                                        "every case and observation kept its value",
            "oracle_selfcheck.json": "freeze-time hashes regenerated so they describe the annotated "
                                     "file; that is bookkeeping, not an expectation change",
        },
        "rule_reference": "execution pack rule 10: a declared repack of a frozen fixture must state "
                          "the scope, the old/new hashes and the proof that the difference is only "
                          "the declared change",
        "written_at_unix": time.time(),
        "written_at_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    out = os.path.join(evidence, "cases_annotation_repack.json")
    with open(out, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(doc, handle, ensure_ascii=True, indent=1)
        handle.write("\n")
    print("cases.json old sha256=%s bytes=%d" % (doc["old_revision"]["sha256"],
                                                 doc["old_revision"]["bytes"]))
    print("cases.json new sha256=%s bytes=%d" % (doc["new_revision"]["sha256"],
                                                 doc["new_revision"]["bytes"]))
    print("differences: %d, unexpected: %d" % (len(differences), len(unexpected)))
    for item in differences:
        print("  %s %s" % (item["kind"], item["path"]))
    return 0 if not unexpected else 8


if __name__ == "__main__":
    raise SystemExit(main())
