"""GUARD-MERGE deliverable generator: changes.diff + binding.json.

No git anywhere — python difflib only (per card 「no git」).
"""
from __future__ import annotations

import difflib
import hashlib
import json
import pathlib
import sys
from datetime import datetime, timezone

A = pathlib.Path(sys.argv[1])
PLAN = A.parents[2]  # .../2026-09-19-three-project-history-audit
RUNS = PLAN / "execution_runs"
CW_REPO = pathlib.Path(r"C:\Users\郑曾波\Projects\company-wiki")
RF_REPO = pathlib.Path(r"C:\Users\郑曾波\Projects\revenue-forecast")
CW_SRC = "src/company_wiki/source_catalog"

FACES = [
    ("prompt_injection_guard.py",
     "company-wiki",
     CW_REPO / CW_SRC / "prompt_injection_guard.py",
     "TTL-30D-POLICY/a20260922-01 (REJECT form, rule 1) + FIX-W06-GAPS/a20260922-01 "
     "(C7 state_domain face, rule 2) + I-06-A/a20260922-02 union point (rule 4)"),
    ("prompt_injection.py",
     "company-wiki",
     CW_REPO / CW_SRC / "prompt_injection.py",
     "FIX-W06-GAPS/a20260922-01 byte-identical (rule 3)"),
    ("readiness_graph.py",
     "company-wiki",
     CW_REPO / CW_SRC / "readiness_graph.py",
     "FIX-W06-GAPS/a20260922-01 byte-identical (rule 2)"),
]

SOURCES = [
    ("TTL-30D-POLICY", "a20260922-01", RUNS / "TTL-30D-POLICY/a20260922-01",
     [("iso/prompt_injection_guard.py", "142ae84838960d500528f2bd3bee1742758152e0518e061a67ed3997ca6dd7dd")],
     "review ACCEPT scope-limited (3fda9125)"),
    ("FIX-W06-GAPS", "a20260922-01", RUNS / "FIX-W06-GAPS/a20260922-01",
     [("iso/pi_pkg/prompt_injection_guard.py", "17f0dc58f6530f0f0f8dbe5099cd655edfe3b7b4404300e3e594ef38534ed31b"),
      ("iso/pi_pkg/prompt_injection.py", "88154de4ab7630606c2545cdcdf9c3ac44faf32bcae0f83f33a1cebc6d490f33"),
      ("iso/pi_pkg/readiness_graph.py", "50c94de28f328d125bd4834b2cda8a46794cba5f5f3f01c5415b4060b2d8c97b")],
     "review IN FLIGHT (4d710b79); GREEN evidence 12/12 mutations"),
    ("I-06-A", "a20260922-02", RUNS / "I-06-A/a20260922-02",
     [("iso/cw/src/company_wiki/source_catalog/prompt_injection_guard.py",
       "cf9174b538288f71349f3d33b46f96eacb6a16f5df4906764b08439230119c03")],
     "review = changes_required (NaN) + fix round running; its guard face SUPERSEDED by this ruling "
     "(store.py / processing_demand.py face stays its own)"),
]

# start-of-attempt live pins (transcribed from the first hash run, see
# evidence/raw/live_pins_start.json); compared against the CLOSE-time live hash.
START_LIVE = {
    "TTL-30D-POLICY/a20260922-01/iso/prompt_injection_guard.py":
        "142ae84838960d500528f2bd3bee1742758152e0518e061a67ed3997ca6dd7dd",
    "FIX-W06-GAPS/a20260922-01/iso/pi_pkg/prompt_injection_guard.py":
        "17f0dc58f6530f0f0f8dbe5099cd655edfe3b7b4404300e3e594ef38534ed31b",
    "FIX-W06-GAPS/a20260922-01/iso/pi_pkg/prompt_injection.py":
        "88154de4ab7630606c2545cdcdf9c3ac44faf32bcae0f83f33a1cebc6d490f33",
    "FIX-W06-GAPS/a20260922-01/iso/pi_pkg/readiness_graph.py":
        "50c94de28f328d125bd4834b2cda8a46794cba5f5f3f01c5415b4060b2d8c97b",
    "I-06-A/a20260922-02/iso/cw/src/company_wiki/source_catalog/prompt_injection_guard.py":
        "cf9174b538288f71349f3d33b46f96eacb6a16f5df4906764b08439230119c03",
}


def sha(p: pathlib.Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


# ---------------------------------------------------------------- changes.diff
sections = []
for name, repo, prod_path, origin in FACES:
    before = A / "before" / name
    after = A / "iso" / name
    b_lines = before.read_text(encoding="utf-8").splitlines(keepends=True)
    a_lines = after.read_text(encoding="utf-8").splitlines(keepends=True)
    diff = list(difflib.unified_diff(
        b_lines, a_lines,
        fromfile=f"{repo}:{CW_SRC}/{name} (before {sha(before)})",
        tofile=f"GUARD-MERGE/a20260922-01:iso/{name} (after {sha(after)})",
        n=3))
    hunks = [l for l in diff if l.startswith("@@")]
    sections.append(
        f"==== REPO {repo} :: {CW_SRC}/{name} ====\n"
        f"==== source card(s): {origin} ====\n"
        f"==== before sha256: {sha(before)}  after sha256: {sha(after)} ====\n"
        + "".join(diff)
        + f"==== hunks: {len(hunks)} ====\n\n")
header = (
    "GUARD-MERGE/a20260922-01 — changes.diff (production face)\n"
    "generated by python difflib (scripts/gen_changes_diff.py) — NO GIT\n"
    f"generated_utc: {datetime.now(timezone.utc).isoformat()}\n"
    "before = live production bytes (re-verified == each card's before pin)\n"
    "after  = this attempt's merged iso faces\n\n")
(A / "changes.diff").write_text(header + "".join(sections), encoding="utf-8",
                                newline="\n")

# ---------------------------------------------------------------- binding.json
source_rows = []
for card, attempt, root, files, note in SOURCES:
    rows = []
    for rel, expected in files:
        p = root / rel
        close = sha(p)
        key = f"{card}/{attempt}/{rel}"
        start = START_LIVE.get(key)
        entry = {
            "path": f"execution_runs/{card}/{attempt}/{rel}",
            "expected_from_binding": expected,
            "start_of_attempt_live_sha256": start,
            "start_matched_binding": start == expected,
            "close_live_sha256": close,
            "close_matched_binding": close == expected,
            "input_used_by_this_merge": start == expected,
        }
        if start != close:
            entry["drift_observed"] = (
                "the sibling card's OWN fix round is running concurrently "
                "(card I-06-A: review=changes_required + fix round running); "
                "mtime of the changed file is inside this attempt's window. "
                "This attempt never wrote to that path (zero writes outside "
                "GUARD-MERGE/a20260922-01 and %TEMP%). The card-pinned face "
                f"({start}) was live-verified at attempt start and READ for the "
                "rule-4 side-by-side before the rewrite; its bytes were then "
                "overwritten by their fix round and are no longer on disk, so "
                "the archival copy here is the POST-fix face "
                "(sources/I06A_guard_live_at_copy_c2af11b3.py = c2af11b3...). "
                "No merge decision depends on the difference: both versions "
                "carry CLIP + effective_receipt_ttl/effective_review_instant + "
                "RECEIPT_TTL_POLICY_CAP_SECONDS + state_domain default-accept "
                "(all re-verified by marker grep, decision.md §0)."
            )
        rows.append(entry)
    source_rows.append({"card": card, "attempt": attempt, "note": note,
                        "after_files": rows,
                        "read_only_respected": True,
                        "live_hash_method": "Get-FileHash SHA256 / hashlib.sha256"})

# snapshot of the I-06-A tree copy actually used by the rule-4 side battery
i06_snap = {}
snap_root = A / "i06a_check"
if snap_root.exists():
    for rel in ("iso/cw/src/company_wiki/source_catalog/prompt_injection_guard.py",
                "iso/cw/src/company_wiki/source_catalog/store.py",
                "iso/cw/src/company_wiki/source_catalog/processing_demand.py",
                "before/cw/src/company_wiki/source_catalog/prompt_injection_guard.py"):
        p = snap_root / rel
        if p.exists():
            i06_snap[rel] = sha(p)

before_rows = []
for name, repo, prod_path, _ in FACES:
    before_rows.append({
        "face": name,
        "production_path": str(prod_path),
        "prod_live_sha256": sha(prod_path),
        "attempt_before_copy": f"before/{name}",
        "attempt_before_sha256": sha(A / "before" / name),
        "matches_card_before_pin": {
            "prompt_injection_guard.py": "f900a13d7c22fe3bd742485c6b603de11b92a56d2414a2a046216ccd3b0b9c08",
            "prompt_injection.py": "7b22f23918d5e6b083a3c5272de2ed26c8a0c420b007f1268c664c0c86139618",
            "readiness_graph.py": "3f4c43b0049eca71fde4f7d9152b02674a26679b4470f6607383eb1820685acc",
        }[name],
        "production_unchanged": sha(prod_path) == sha(A / "before" / name),
    })

merged_rows = []
for name, repo, prod_path, origin in FACES:
    p = A / "iso" / name
    merged_rows.append({"face": name, "path": f"iso/{name}",
                        "sha256": sha(p), "bytes": p.stat().st_size,
                        "provenance": origin,
                        "identical_to_sibling_source": {
                            "prompt_injection.py":
                                sha(p) == "88154de4ab7630606c2545cdcdf9c3ac44faf32bcae0f83f33a1cebc6d490f33",
                            "readiness_graph.py":
                                sha(p) == "50c94de28f328d125bd4834b2cda8a46794cba5f5f3f01c5415b4060b2d8c97b",
                            "prompt_injection_guard.py": False,  # composed face
                        }[name]})

binding = {
    "card": "GUARD-MERGE",
    "attempt": "a20260922-01",
    "authority": "U-3 = parent (OPEN-5 / OPEN-6 / TTL all three reviews: "
                 "「clip-vs-REJECT + mechanism choice = parent」)",
    "binding_rule": "every merge decision binds to (a) the parent composition rule "
                    "(oracle.md §1, verbatim), (b) the source card + its binding.json pins, "
                    "(c) the frozen battery expectation, (d) the evidence artifact. "
                    "Nothing composed outside these rows.",
    "oracle": {"path": "oracle.md",
               "sha256": json.loads((A / "oracle_freeze.json").read_text(encoding="utf-8-sig"))["sha256"]},
    "sources_read_only": source_rows,
    "rule4_side_battery_snapshot_i06a_check": i06_snap,
    "close_time_live_pins": {
        "evidence": "evidence/raw/live_pins_start.json (start) + this file (close)",
        "note": "re-hashed at deliverable generation",
    },
    "before_faces": before_rows,
    "merged_faces": merged_rows,
    "dropped": [
        "I-06-A CLIP line: `ttl_seconds = effective_receipt_ttl(ttl_seconds)` (rule 1/5)",
        "I-06-A CLIP line: `now = effective_review_instant(now)` (rule 1/5)",
        "I-06-A helpers: effective_receipt_ttl / effective_review_instant / _policy_clock / _iso_of (rule 5, no face needs them)",
        "I-06-A constant spelling RECEIPT_TTL_POLICY_CAP_SECONDS (TTL's POLICY_RECEIPT_TTL_CAP_SECONDS is the pinned name, battery i case TTL-C0)",
        "I-06-A helper state_domain_of (rule 5 minimality; its strictness is kept as the "
        "merged ReviewEvaluation cache_state-legal check, rule 4 union point)",
    ],
    "production_writes": "ZERO — company-wiki and revenue-forecast product trees were never "
                         "opened for write; hashes above are live re-verified at close",
    "git": "ZERO — no git command executed; changes.diff is python difflib",
    "generated_utc": datetime.now(timezone.utc).isoformat(),
}
(A / "binding.json").write_text(json.dumps(binding, ensure_ascii=False, indent=2),
                                encoding="utf-8")
print(json.dumps({"changes_diff_sha256": sha(A / "changes.diff"),
                  "merged": {r["face"]: r["sha256"] for r in merged_rows},
                  "prod_unchanged": all(r["production_unchanged"] for r in before_rows),
                  "sources_start_matched": all(m["start_matched_binding"]
                                               for s in source_rows
                                               for m in s["after_files"]),
                  "sources_close_matched": all(m["close_matched_binding"]
                                               for s in source_rows
                                               for m in s["after_files"])},
                 ensure_ascii=False, indent=2))
