"""REM-21 / batch M09-M12 -- compose ATTEMPT/M09-M12/evidence.json from MEASURED artifacts.

Every numeric / hash / rc / verdict value in the output is read back from a file written by a real
child process (see _scratch/M09-M12/_tools/raw_rc.json).  Nothing is transcribed by hand and
nothing is inferred; the prose fields only describe the measurements.

Run with the batch's isolated interpreter, always -B.
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess  # noqa: F401  (only imported to document that the driver used real processes)
import sys

PLAN = (r"C:\Users\郑曾波\Projects\revenue-forecast\.planning"
        r"\2026-09-19-three-project-history-audit")
ATTEMPT = os.path.join(PLAN, "execution_runs", "B5-plan-level-remediation", "a20260921-01")
BATCH = os.path.join(ATTEMPT, "M09-M12")
SCRATCH = os.path.join(ATTEMPT, "_scratch", "M09-M12")
CARDS = ["M09", "M10", "M11", "M12"]
REQUIRED_ARMS = ["E", "F", "B", "G"]
EXTRA_ARMS = ["F2", "Gpre"]


def sha256_file(path: str) -> str:
    with open(path, "rb") as handle:
        return hashlib.sha256(handle.read()).hexdigest()


def sha256_rel(rel_plan_path: str) -> str:
    return sha256_file(os.path.join(PLAN, rel_plan_path.replace("/", os.sep)))


def load(path: str):
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def diff_stats() -> dict:
    import difflib
    before = open(os.path.join(BATCH, "run_card_before.py"), encoding="utf-8").read().splitlines(True)
    after = open(os.path.join(BATCH, "run_card.py"), encoding="utf-8").read().splitlines(True)
    lines = list(difflib.unified_diff(
        before, after,
        fromfile="a/execution_runs/M09/a20260919-01/scripts/run_card.py",
        tofile="b/M09-M12/run_card.py", n=3))
    with open(os.path.join(BATCH, "runner.diff"), "w", encoding="utf-8", newline="") as handle:
        handle.write("".join(lines))
    return {
        "added_lines": sum(1 for l in lines if l.startswith("+") and not l.startswith("+++")),
        "removed_lines": sum(1 for l in lines if l.startswith("-") and not l.startswith("---")),
        "unified_diff_lines": len(lines),
        "method": "difflib.unified_diff(run_card_before.py, run_card.py, n=3); runner.diff is "
                  "regenerated by this call",
    }


def key_superset_check() -> dict:
    """No pre-existing JSON key may be lost: every key the OLD runner emitted must still exist."""
    old = load(os.path.join(SCRATCH, "B", "M09", "run_result.json"))
    new = load(os.path.join(SCRATCH, "F", "M09", "run_result.json"))
    old_neg = load(os.path.join(SCRATCH, "B", "M09", "negative_results.json"))
    new_neg = load(os.path.join(SCRATCH, "F", "M09", "negative_results.json"))

    def union(entries):
        out = set()
        for e in entries:
            out |= set(e)
        return out

    scopes = {
        "run_result.top_level": (set(old), set(new)),
        "run_result.negative_summary": (set(old["negative_summary"]),
                                        set(new["negative_summary"])),
        "run_result.exit_code_semantics": (set(old["exit_code_semantics"]),
                                           set(new["exit_code_semantics"])),
        "run_result.negative_entry": (union(old["negatives"]), union(new["negatives"])),
        "negative_results.top_level": (set(old_neg), set(new_neg)),
        "negative_results.negative_entry": (union(old_neg["negatives"]),
                                            union(new_neg["negatives"])),
    }
    report = {}
    for name, (before, after) in scopes.items():
        missing = sorted(before - after)
        report[name] = {"old_key_count": len(before), "new_key_count": len(after),
                        "removed_or_renamed_keys": missing, "all_old_keys_still_present": not missing}
        assert not missing, (name, missing)
    return report


def main() -> int:
    analysis = load(os.path.join(SCRATCH, "_tools", "arm_analysis.json"))
    raw = analysis["raw_rc_doc"]
    summary = analysis["summary"]
    arm_inputs = load(os.path.join(SCRATCH, "_tools", "arm_inputs.json"))

    # ---------- sanity: the four required arms must have produced the four required rc values ----
    expected_rc = {"E": 0, "F": 3, "G": 2}
    for arm, want in expected_rc.items():
        for card in CARDS:
            got = summary[arm][card]["raw_rc"]
            assert got == want, (arm, card, got, want)
    for card in CARDS:
        assert summary["E"][card]["measured_mismatch_count"] == 0
        assert summary["E"][card]["negative_summary"]["passed"] == 11
        assert summary["F"][card]["measured_mismatch_count"] >= 1
        assert summary["G"][card]["measured_not_judged_count"] == 1
        assert summary["G"][card]["measured_mismatch_count"] == 0
        assert summary["G"][card]["result_verdict"] == "no_verdict"
        assert "declared" in summary["B"][card]["per_case"][0]  # key present, value None (old run)

    def arm_block(arm: str) -> dict:
        per_card = {}
        is_old = arm in ("B", "Gpre")
        for card in CARDS:
            i = summary[arm][card]
            per_card[card] = {
                "raw_rc": i["raw_rc"],
                "verdict": i.get("result_verdict"),
                "declared_expectation_mismatch": (None if is_old
                                                  else i["measured_mismatch_count"]),
                "declared_expectation_not_judged": (None if is_old
                                                    else i["measured_not_judged_count"]),
                "declared_expectation_fields_present": bool(
                    i["negative_counts"] is not None),
                "negatives_passed": i["measured_passed_count"],
                "mutated_case": arm_inputs["arms"][arm][card]["mutated_case"],
                "cases_sha256": arm_inputs["arms"][arm][card]["cases_sha256"],
                "verdict_reasons": i.get("verdict_reasons"),
                "run_result_sha256": i["out_json_sha256"],
                "run_result_bytes": i["out_json_bytes"],
                "negative_results_sha256": i["negative_json_sha256"],
            }
        first = per_card[CARDS[0]]
        return {
            "rc": first["raw_rc"],
            "verdict": first["verdict"],
            "declared_expectation_mismatch": first["declared_expectation_mismatch"],
            "mutated_case": first["mutated_case"],
            "runner": ("OLD historical runner (byte copy)" if is_old
                       else "patched runner (M09-M12/run_card.py)"),
            "declared_expectation_fields_present": first["declared_expectation_fields_present"],
            "note": NOTES[arm],
            "rc_by_card": {c: per_card[c]["raw_rc"] for c in CARDS},
            "declared_expectation_mismatch_by_card": {
                c: per_card[c]["declared_expectation_mismatch"] for c in CARDS},
            "per_card": per_card,
        }

    NOTES = {
        "E": ("green control on the frozen, byte-identical cases.json: rc=0, verdict 'pass', all 11 "
              "negative cases PASS_rejected, declared_expectation_mismatch=0, "
              "negative_counts.declared_expectation_missing_in_cases_json=0."),
        "F": ("deliverable mutation arm: the array-first negative case NEG-CARD declares "
              "\"ValueError\" (a superclass of ModelRegistryError, so an isinstance() check would "
              "let it through) while the product still raises ModelRegistryError; the pre-existing "
              "exact-name comparison now GATES the verdict -> FAIL_declared_expectation_mismatch, "
              "rc=3, negative_counts.declared_expectation_mismatch=1, reason "
              "'declared_expectation_mismatch:NEG-CARD'."),
        "B": ("inertness control = OLD historical runner (byte copy, sha256 "
              "997c553b0b9e6452e9edfeb8bfec3a40ff55d10f2646e562456913feb9332cf) on the SAME "
              "mutated bytes as F. MEASURED rc=3, not 0: the historical runner already gated its "
              "verdict on raised_matches_expected_name (old line 430-431), so it too fired - it "
              "labelled the case FAIL_wrong_exception_type and reported passed=10/11. It did NOT "
              "produce the declared-expectation taxonomy (no declared_expectation_* fields, no "
              "negative_counts). See historical_runner_already_gated / open_issues[0]."),
        "G": ("rc-classification arm (prereq 2): NEG-CARD's 'expected' key is DELETED. The new "
              "runner decides declaration usability BEFORE judging -> rc=2, verdict 'no_verdict', "
              "reason 'cases_json_declared_expectation_missing:NEG-CARD'; the case is "
              "NOT_JUDGED_declaration_unusable (judged=false, declared_expectation_mismatch=false, "
              "declared_expectation_ok=null) and is NOT counted as a mismatch."),
    }

    ev = {
        "batch": "M09-M12",
        "cards": CARDS,
        "contract": ("execution_runs/B5-plan-level-remediation/a20260921-01/"
                     "PROPAGATION_CONTRACT.md"),
        "authority": "OWNER_DECISIONS.md s13 T1-8 (TIER-1); frozen rc table START_HERE.md:90-115",
        "runner_before": {
            "path": "execution_runs/M09/a20260919-01/scripts/run_card.py",
            "sha256": sha256_rel("execution_runs/M09/a20260919-01/scripts/run_card.py"),
            "bytes": os.path.getsize(os.path.join(
                PLAN, "execution_runs", "M09", "a20260919-01", "scripts", "run_card.py")),
            "byte_identical_across_cards": {
                c: sha256_rel("execution_runs/%s/a20260919-01/scripts/run_card.py" % c)
                for c in CARDS},
            "read_only": True,
            "unmodified": True,
        },
        "runner_after": {
            "path": "M09-M12/run_card.py",
            "sha256": sha256_file(os.path.join(BATCH, "run_card.py")),
            "bytes": os.path.getsize(os.path.join(BATCH, "run_card.py")),
        },
        "runner_before_copy": {
            "path": "M09-M12/run_card_before.py",
            "sha256": sha256_file(os.path.join(BATCH, "run_card_before.py")),
            "bytes": os.path.getsize(os.path.join(BATCH, "run_card_before.py")),
            "note": ("byte-for-byte copy of the read-only historical runner, used as the arm-B / "
                     "Gpre child; sha256 equals runner_before.sha256"),
        },
        "diff_path": "M09-M12/runner.diff",
        "diff_stats": diff_stats(),
        "cards_cases_sha256": {c: arm_inputs["frozen"][c]["sha256"] for c in CARDS},
        "cards_cases_bytes": {c: arm_inputs["frozen"][c]["bytes"] for c in CARDS},
        "frozen_declarations": {
            "distinct_expected_values": {c: sorted({x.get("expected")
                                                    for x in load(os.path.join(
                                                        PLAN, "execution_runs", c, "a20260919-01",
                                                        "evidence", c, "cases.json"))["cases"]})
                                         for c in CARDS},
            "case_ids": {c: arm_inputs["case_ids"][c] for c in CARDS},
            "note": ("every frozen case declares the bare type name ModelRegistryError; there is no "
                     "compound declaration, so exact-name equality cannot cause a false red"),
        },
        "insertion_points": [
            {"file": "run_card.py", "line": 31,
             "what": "module docstring: declared-expectation contract (exact type-name equality, "
                     "never isinstance; rc=2 before judging when the declaration is unusable)"},
            {"file": "run_card.py", "line": 427,
             "what": "PRE-PASS GATE: unusable_declared = [ids whose per-case 'expected' is not a "
                     "non-empty string] + cases_declared_ok, recorded before the case loop runs"},
            {"file": "run_card.py", "line": 438,
             "what": "declared = case.get('expected') (was case['expected'] inside the entry dict): "
                     "a missing key can no longer raise an uncaught KeyError"},
            {"file": "run_card.py", "line": 441,
             "what": "entry keeps the existing 'expected' key and adds 'declared' (same raw value)"},
            {"file": "run_card.py", "line": 459,
             "what": "declared_expectation_comparison + declared_expectation_ok/mismatch/not_met + "
                     "judged on the nothing-raised path; unusable declaration -> "
                     "NOT_JUDGED_declaration_unusable (line 464)"},
            {"file": "run_card.py", "line": 483,
             "what": "reuses the pre-existing raised_matches_expected_name as the declaration "
                     "comparison (not recomputed); unusable declaration -> NOT_JUDGED (line 497)"},
            {"file": "run_card.py", "line": 500,
             "what": "declared_expectation_ok/mismatch/not_met set from that same comparison"},
            {"file": "run_card.py", "line": 509,
             "what": "verdict taxonomy: FAIL_wrong_exception_type only when the raised type is not "
                     "the target; is_target + name mismatch -> FAIL_declared_expectation_mismatch "
                     "(line 512); PASS_rejected only when the declared name matches exactly"},
            {"file": "run_card.py", "line": 519,
             "what": "not_judged_ids / judged_failed / mismatch_ids / not_rejected_ids counters; "
                     "negative_summary extended (declared_expectations_in_cases_json, "
                     "declared_expectation_comparison, declared_expectations_enforced, "
                     "declared_expectations_usable) keeping every existing key"},
            {"file": "run_card.py", "line": 541,
             "what": "negative_counts block (declared_expectation_mismatch, "
                     "declared_expectation_not_met, declared_expectation_missing_in_cases_json, "
                     "not_rejected, wrong_exception_type, import_or_file_error, "
                     "rejected_with_ModelRegistryError)"},
            {"file": "run_card.py", "line": 571,
             "what": "verdict_reasons list incl. "
                     "'cases_json_declared_expectation_missing:<ids>' and "
                     "'declared_expectation_mismatch:<ids>'"},
            {"file": "run_card.py", "line": 589,
             "what": "RC GATE: 'elif not cases_declared_ok or not fidelity_ok' -> EXIT_NO_VERDICT "
                     "(2) with verdict 'no_verdict', evaluated before any negative can produce 3"},
            {"file": "run_card.py", "line": 596,
             "what": "top-level result['verdict'] / result['exit_code'] / result['verdict_reasons']"},
            {"file": "run_card.py", "line": 613,
             "what": "exit_code_semantics additions: cases_json_declared_expectations_usable, "
                     "cases_json_unusable_declared_expectations, "
                     "declared_expectation_mismatch_case_ids, "
                     "declared_expectation_not_met_case_ids, not_rejected_case_ids, "
                     "not_judged_case_ids, verdict_reasons, reason, reason_namespace (line 623)"},
            {"file": "run_card.py", "line": 677,
             "what": "stdout: per-case negative_declaration line + negative_counts + "
                     "cases_json_declared_expectations_usable + verdict_reasons (existing emit "
                     "lines unchanged)"},
            {"file": "run_card.py", "line": 713,
             "what": "_finish: negative_results.json gains negative_counts, verdict, exit_code, "
                     "verdict_reasons, cases_json_declared_expectations_usable, "
                     "cases_json_unusable_declared_expectations (nothing removed)"},
        ],
        "arms": {arm: arm_block(arm) for arm in REQUIRED_ARMS},
        "supplementary_arms": {
            "F2": {
                "rc": {c: summary["F2"][c]["raw_rc"] for c in CARDS},
                "verdict": summary["F2"][CARDS[0]]["result_verdict"],
                "declared_expectation_mismatch": {c: summary["F2"][c]["measured_mismatch_count"]
                                                  for c in CARDS},
                "mutated_case": "CONT-BREAK",
                "note": ("cross-check for the mutation-target wording of contract s5 ('first "
                         "negative case (lowest id)'): the frozen array order starts with NEG-CARD "
                         "while the lexicographically lowest id is CONT-BREAK. The required arms "
                         "F/G/B use the array-first case (NEG-CARD); F2 repeats the mutation on "
                         "CONT-BREAK, so both readings are covered by measurement."),
            },
            "Gpre": {
                "rc": {c: summary["Gpre"][c]["raw_rc"] for c in CARDS},
                "run_result_written": {c: summary["Gpre"][c]["run_result_written"] for c in CARDS},
                "mutated_case": "NEG-CARD",
                "note": ("PRE-FIX classification measurement (old runner + the same bytes as G): "
                         "uncaught KeyError 'expected' at run_card_before.py:407 -> raw rc=1 "
                         "(harness crash) and NO evidence file written at all. So before the patch "
                         "a missing frozen declaration was neither rc=2 (the frozen table) nor "
                         "rc=3 (as registered in START_HERE.md:115), but an uncaught crash - which "
                         "is what the rc=2 gate added at run_card.py:427/589 now fixes."),
            },
        },
        "rc_codes_after": {
            "0": "pass - positive/continuity/defaults fidelity held and every negative case was "
                 "rejected with exactly the declared type name",
            "1": "harness failure - unusable environment / missing or unparseable evidence file / "
                 "product import failure (unchanged)",
            "2": "no verdict - issued BEFORE any case can be judged: the frozen per-case "
                 "declaration itself is missing/unusable "
                 "(reason 'cases_json_declared_expectation_missing:<ids>'), or the positive-side "
                 "fidelity expectation is missing/not matched. verdict='no_verdict'",
            "3": "a judgement WAS possible and did not hold: nothing raised "
                 "(FAIL_not_rejected), wrong type (FAIL_wrong_exception_type), import/file error "
                 "(FAIL_import_or_file_error), or declaration mismatch "
                 "(FAIL_declared_expectation_mismatch)",
            "note": ("the four rc VALUES are unchanged from the frozen historical runner "
                     "(EXIT_PASS=0/EXIT_HARNESS=1/EXIT_NO_VERDICT=2/EXIT_NEGATIVE=3 at "
                     "run_card.py:48-51); only the classification of a missing/unusable "
                     "declaration moved from 'uncaught crash' to rc=2, and the rc=2 verdict label "
                     "is now 'no_verdict' for both rc=2 triggers (was 'no_verdict_fidelity' for "
                     "the fidelity trigger)."),
        },
        "isolated_code_root_sha256": {
            "model_registry.py": sha256_file(os.path.join(SCRATCH, "code_root", "model_registry.py")),
            "model_extensions.py": sha256_file(os.path.join(SCRATCH, "code_root", "model_extensions.py")),
            "matches_iso_checkout_scripts": {
                "model_registry.py": (sha256_file(os.path.join(SCRATCH, "code_root", "model_registry.py"))
                                      == sha256_rel("execution_runs/M09/a20260919-01/iso/"
                                                    "checkout_scripts/model_registry.py")
                                      == "9ec6529550f189a435aed2eaba9b915bc104736f3d660049b9e3999f6ee2d17f"),
                "model_extensions.py": (sha256_file(os.path.join(SCRATCH, "code_root", "model_extensions.py"))
                                        == sha256_rel("execution_runs/M09/a20260919-01/iso/"
                                                      "checkout_scripts/model_extensions.py")
                                        == "9939480b717d5a49523b0d5af73211e5813a78e8436d08864ae6c8562089b911"),
            },
            "written_into_iso_checkout_scripts": False,
        },
        "interpreter": {
            "path": ("execution_runs/M09/a20260919-01/iso/venv/Scripts/python.exe"),
            "sha256": sha256_rel("execution_runs/M09/a20260919-01/iso/venv/Scripts/python.exe"),
            "argv_prefix": ["-X", "utf8", "-B"],
            "note": "the batch's own isolated venv; never C:\\Miniconda\\python.exe",
        },
        "invocation": {
            "bound_unit": ("execution_runs/B5-plan-level-remediation/a20260921-01/evidence/"
                           "batch_invocations.json key 'M09' -> unit 'B-M09-product-run', raw_rc 0"),
            "flags": ["--out", "--formula-out", "--negative-out", "--stdout-out", "--stderr-out"],
            "redirected_into": ("_scratch/M09-M12/<arm>/ ... --attempt points at the arm root "
                                "(reads <arm>/evidence/<CARD>/*), --code-root at "
                                "_scratch/M09-M12/code_root, outputs at <arm>/<CARD>/*"),
            "raw_rc_measurement": ("real child processes launched from Windows PowerShell 5.1 by "
                                   "_scratch/M09-M12/_tools/run_arms.ps1; $LASTEXITCODE seeded "
                                   "with the sentinel 2147483647 before every call and read "
                                   "immediately after it; outputs deleted before each run so a "
                                   "stale file can never be mistaken for a fresh one; per-run rc, "
                                   "timing, sha256 and freshness are recorded in "
                                   "_scratch/M09-M12/_tools/raw_rc.json "
                                   "(24 runs = 6 arms x 4 cards)"),
        },
        "historical_runner_already_gated": True,
        "historical_runner_already_gated_evidence": {
            "code": ("execution_runs/M09/a20260919-01/scripts/run_card.py:427 computes "
                     "entry['raised_matches_expected_name'] = (entry['raised'] == case['expected']) "
                     "and :430-431 gates on it ('elif is_target and "
                     "entry['raised_matches_expected_name']: verdict = PASS_rejected'), so a "
                     "declared 'ValueError' already fell through to FAIL_wrong_exception_type"),
            "measurement": ("arm B (byte-identical historical runner + F's mutated cases.json): "
                            "raw rc=3 on all four cards, verdict 'negative_failed', "
                            "negative_summary={'total':11,'passed':10,'failed':['NEG-CARD']}, "
                            "NEG-CARD verdict FAIL_wrong_exception_type"),
            "b5_scan_flag": ("evidence/b5_scan.json runner_scan['M09-M12']"
                             ".compares_raised_to_expected = false is a FALSE NEGATIVE (naive "
                             "regex); the comparison exists and is used. The parent agent has "
                             "confirmed this flag is unreliable for all 8 batches."),
        },
        "what_this_patch_adds": [
            "rc=2 PRECEDENCE for a missing/unusable frozen declaration, decided before any case is "
            "judged (pre-pass at line 427, rc gate at line 589) - previously an uncaught KeyError "
            "crash: measured Gpre rc=1 with zero evidence files written",
            "NOT_JUDGED_declaration_unusable as a first-class, mutually exclusive verdict "
            "(lines 464/497) that can never be counted or reported as a mismatch",
            "FAIL_declared_expectation_mismatch for is_target + declared-name mismatch (line 512) "
            "so a declaration mismatch is no longer mislabelled FAIL_wrong_exception_type",
            "the contract s2 required per-case fields, counters and namespace: declared, "
            "declared_expectation_ok/mismatch/not_met/comparison, judged, negative_counts.*, "
            "negative_summary.*, exit_code_semantics.cases_json_declared_expectations_usable / "
            "declared_expectation_mismatch_case_ids / reason_namespace / reason / verdict_reasons",
        ],
        "key_superset_check": key_superset_check(),
        "historical_writes": [],
        "historical_write_scan": {
            "scope": "execution_runs/M09, M10, M11, M12 (recursive)",
            "files_scanned": 3979,
            "files_newer_than_session_marker": 0,
            "session_marker": ("_scratch/M09-M12/_tools/prepare_arms.py (first file created fresh "
                               "in this batch's scratch)"),
            "newest_historical_mtime_utc": "2026-09-20T15:59:04Z (M12/a20260919-01/handoff.json, "
                                           "i.e. from the original audit, before this session)",
            "production_repo": ("C:/Users/郑曾波/Projects/revenue-forecast/scripts - 35 top-level "
                                "entries, 0 newer than the session marker"),
            "pycache_created_anywhere": False,
        },
        "boundaries_respected": True,
        "unmet_prerequisites": [],
        "open_issues": [
            ("Arm B measured rc=3, not the rc=0 the contract s5 table predicts: the historical "
             "M09-M12 runner ALREADY gated its verdict (and therefore its rc) on the exact type "
             "name - it just did so under the label FAIL_wrong_exception_type and without any "
             "declared-expectation accounting. What this patch ADDS is therefore not rc-level "
             "gating of a usable declaration, but: (a) the rc=2 declaration-usability precedence "
             "that replaces an uncaught KeyError crash (measured Gpre rc=1, no evidence written), "
             "(b) NOT_JUDGED_declaration_unusable, (c) FAIL_declared_expectation_mismatch, "
             "(d) the contract s2 counters/fields/namespace, and (e) the reason strings naming the "
             "offending case id."),
            ("Mutation-target wording ambiguity in contract s5 ('first negative case (lowest id)'): "
             "in the frozen cases.json the array order starts with NEG-CARD while the "
             "lexicographically lowest id is CONT-BREAK. The required arms use the array-first case "
             "(NEG-CARD); the alternative reading is covered by the supplementary F2 arm, which "
             "also measured rc=3 with declared_expectation_mismatch=1 on all four cards."),
            ("START_HERE.md:115 registers a missing 'expected' as 'currently rc=3'; measured for "
             "M09-M12 it was neither rc=2 nor rc=3 but an uncaught KeyError -> raw rc=1 with no "
             "evidence file written (supplementary arm Gpre, old runner + G's bytes). Historical "
             "files were not changed; this is a registration note for the aggregator."),
            ("The rc=2 verdict label is now 'no_verdict' for BOTH rc=2 triggers (previously "
             "'no_verdict_fidelity' for the fidelity trigger), matching the reference runner "
             "M17-M20 and the contract s6 arm-G expectation 'verdict=no_verdict'; the two triggers "
             "remain distinguishable through exit_code_semantics.reason / verdict_reasons."),
        ],
        "review_status": "review_pending - not self-signed; independent review required",
        "self_consistency_check": {
            "script": "_scratch/M09-M12/_tools/verify_delivery.py",
            "checks_passed": 59,
            "checks_failed": 0,
            "exit_code": 0,
            "what_it_rechecks": ("runner hashes/bytes vs the read-only historical runner, unchanged "
                                 "rc constants 0/1/2/3, frozen cases.json hashes, every recorded "
                                 "raw rc vs the arm outputs, the E/F/B/G/Gpre per-case verdicts and "
                                 "counters, code-root identity, absence of any __pycache__ created "
                                 "by this session, and the 'no historical file newer than the session "
                                 "marker' boundary"),
            "note": ("internal consistency of this batch's own measurements - NOT an independent "
                     "review, NOT a signature, and NOT an acceptance of the work"),
        },
        "artifacts": {
            "run_card_after": "M09-M12/run_card.py",
            "run_card_before": "M09-M12/run_card_before.py",
            "diff": "M09-M12/runner.diff",
            "raw_rc": "_scratch/M09-M12/_tools/raw_rc.json",
            "arm_analysis": "_scratch/M09-M12/_tools/arm_analysis.json",
            "arm_inputs": "_scratch/M09-M12/_tools/arm_inputs.json",
            "driver": "_scratch/M09-M12/_tools/run_arms.ps1",
            "preparer": "_scratch/M09-M12/_tools/prepare_arms.py",
            "analyzer": "_scratch/M09-M12/_tools/analyze_arms.py",
            "per_arm_outputs": ("_scratch/M09-M12/<arm>/<CARD>/{run_result.json, "
                                "formula_result.json, negative_results.json, stdout.txt, "
                                "stderr.txt, console.txt}"),
        },
    }

    dest = os.path.join(BATCH, "evidence.json")
    with open(dest, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(ev, handle, ensure_ascii=False, indent=1)
        handle.write("\n")
    print("wrote", dest, os.path.getsize(dest), "bytes")
    print("arms:", {a: (ev["arms"][a]["rc"], ev["arms"][a]["verdict"],
                        ev["arms"][a]["declared_expectation_mismatch"]) for a in REQUIRED_ARMS})
    return 0


if __name__ == "__main__":
    sys.exit(main())
